<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'Calendar' => 'Darbai',
	'Checkbox' => 'Žymimasis langelis',
	'Currency'=>'Piniginė reikšmė',
	'Date'=>'Data',
	'Decimal'=>'Dešimtainė trupmena',
	'Email'=>'El. paštas',
	'Integer'=>'Sveikasis skaičius',
	'LayoutEditor' => 'Išdėstymo redaktorius',
	'LBL_ACTIONS' => 'Veiksmai',
	'LBL_ACTIVE' => 'Aktyvus',
	'LBL_ADD_AFTER' => 'Pridėti po',
	'LBL_ADD_CUSTOM_BLOCK' => 'Pridėti tinkintą bloką',
	'LBL_ADD_CUSTOM_FIELD' => 'Pridėti tinkintą lauką',
	'LBL_ADD_MODULE_INFO' => 'Pasirinkite modulį iš pašalintųjų, kurį norite grąžinti atgal į sąrašą',
	'LBL_ALWAYS_SHOW' => 'Visada rodyti',
	'LBL_ARRANGE_RELATED_LIST' => 'Tvarkyti susijusius sąrašus',
	'LBL_ARRANGE_RELATED_TABS' => 'Tvarkyti susijusias žymes',
	'LBL_BLOCK_NAME' => 'Bloko pavadinimas',
	'LBL_CLICK_HERE_TO_EDIT' => 'Spustelėkite čia, jei norite redaguoti',
	'LBL_CREATE_CUSTOM_FIELD' => 'Tinkinto lauko kūrimas',
	'LBL_DECIMALS' => 'Skaitmenys po kablelio',
	'LBL_DEFAULT_VALUE' => 'Numatytojji reikšmė',
	'LBL_DELETE_CUSTOM_BLOCK' => 'Pašalinti tinkintą bloką',
	'LBL_DETAILVIEW_LAYOUT' => 'Išsamios informacijos rodinio išdėstymas',
	'LBL_DUPLICATE_FIELD_EXISTS' => 'Aptikti vienodi laukai',
	'LBL_DUPLICATES_EXIST' => 'Blokas tokiu pavadinimu jau egzistuoja',
	'LBL_ENTER_PICKLIST_VALUES' => 'Įveskite išskleidžiamojo sąrašo reikšmes',
	'LBL_FIELDS_AND_LAYOUT_EDITOR' => 'Laukų ir išdėstymų tvarkytuvė',
	'LBL_INACTIVE_FIELDS' => 'Neaktyvūs laukai', //Duplicated key-value pairs
	'LBL_LABEL_NAME' => 'Etiketė',
	'LBL_LENGTH' => 'Ilgis',
	'LBL_MANDATORY_FIELD' => 'Privalomas laukas',
	'LBL_MASS_EDIT' => 'Dauginis redagavimas',
	'LBL_NON_ROLE_BASED_PICKLIST' => 'Išskleidžiamasis sąrašas ne pagal vaidmenį',
	'LBL_NO_RELATED_INFORMATION' => 'Susijusios informacijos nėra',
	'LBL_PICKLIST_VALUES' => 'Išskleidžiamojo sąrašo reikšmės',
	'LBL_QUICK_CREATE' => 'Greitasis kūrimas',
	'LBL_REACTIVATE' => 'Pakartotinai aktyvinti',
	'LBL_RELATED_LIST_INFO' => 'Tempkite modulius, jei norite pertvarkyti sąrašą.',
	'LBL_REMOVE_INFO' => 'Spustelėkite užvėrimo piktogramą, jei norite pašalinti modulį iš sąrašo',
	'LBL_ROLE_BASED_PICKLIST' => 'Išskleidžiamasis sąrašas pagal vaidmenį',
	'LBL_SAVE_FIELD_SEQUENCE' => 'Įrašyti laukų seką',
	'LBL_SELECT_FIELD_TYPE' => 'Pasirinkite lauko tipą',
	'LBL_SELECT_MODULE' => 'Pasirinkite modulį…',
	'LBL_SELECT_MODULE_TO_ADD' => 'Pasirinkite norimą pridėti modulį',
	'LBL_SUMMARY_FIELD' => 'Santrauka',
	'LBL_WRONG_FIELD_TYPE' => 'Netinkamas lauko tipas',
	'MultiSelectCombo'=>'Daugiareikšmis jungtinis langelis',
	'Percent'=>'Procentinė reikšmė',
	'Phone'=>'Telefonas',
	'PickList'=>'Išskleidžiamasis sąrašas',
	'Skype'=>'„Skype“',
	'TextArea' => 'Tekstas (kelios eilutės)',
	'Text'=>'Tekstas (viena eilutė)',
	'Time'=>'Laikas',
	'URL' => 'URL',
);

$jsLanguageStrings = array(
	'JS_BLOCK_NAME_EXISTS' => 'Blokas tokiu pavadinimu jau egzistuoja',
	'JS_BLOCK_SEQUENCE_UPDATED' => 'Blokų eilės tvarka atnaujinta',
	'JS_BLOCK_VISIBILITY_HIDE' => 'Blokų slėpimas įjungtas',
	'JS_BLOCK_VISIBILITY_SHOW' => 'Blokų rodymas įjungtas',
	'JS_CUSTOM_BLOCK_ADDED' => 'Naujas tinkintas blokas pridėtas',
	'JS_CUSTOM_BLOCK_DELETED' => 'Tinkintas blokas pašalintas',
	'JS_CUSTOM_FIELD_ADDED' => 'Naujas tinkintas laukas pridėtas',
	'JS_CUSTOM_FIELD_DELETED' => 'Tinkintas laukas pašalintas',
	'JS_DUPLICATES_VALUES_FOUND' => 'Rastos vienodos reikšmės',
	'JS_FIELD_DETAILS_SAVED' => 'Lauko informacija įrašyta',
	'JS_FIELD_SEQUENCE_UPDATED' => 'Laukų eilės tvarka atnaujinta',
	'JS_LENGTH_SHOULD_BE_LESS_THAN_EQUAL_TO' => 'Ilgis turi būti ne didesnis nei',
	'JS_NO_HIDDEN_FIELDS_EXISTS' => 'Nėra neaktyvių laukų',
	'JS_NOT_ALLOWED' => 'yra neleidžiami',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_2TO5' => 'Trupmeninė dalis turi būti nuo 2 iki 5 skaitmenų ilgio',
	'JS_RELATED_INFO_SAVED' => 'Susijusi informacija įrašyta',
	'JS_SAVE_THE_CHANGES_TO_UPDATE_FIELD_SEQUENCE' => 'Jei norite atnaujinti laukų eilės tvarką, įrašykite pakeitimus',
	'JS_SELECTED_FIELDS_REACTIVATED' => 'Pažymėti laukai pakartotinai aktyvinti',
	'JS_SPECIAL_CHARACTERS' => 'Ypatingi simboliai kaip',
);
