<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LayoutEditor' => 'Išdėstymo redaktorius',
	'LBL_FIELDS_AND_LAYOUT_EDITOR' => 'Laukų ir išdėstymų tvarkytuvė',
	'LBL_CREATE_CUSTOM_FIELD' => 'Tinkinto lauko kūrimas',
	'LBL_DETAILVIEW_LAYOUT' => 'Išsamios informacijos rodinio išdėstymas',
	'LBL_ARRANGE_RELATED_TABS' => 'Tvarkyti susijusias žymes',
	'LBL_ADD_CUSTOM_FIELD' => 'Pridėti tinkintą lauką',
	'LBL_ADD_CUSTOM_BLOCK' => 'Pridėti bloką',
	'LBL_SAVE_FIELD_SEQUENCE' => 'Įrašyti laukų seką',
	'LBL_BLOCK_NAME' => 'Bloko pavadinimas',
	'LBL_ADD_AFTER' => 'Pridėti po',
	'LBL_ACTIONS' => 'Veiksmai',
	'LBL_ALWAYS_SHOW' => 'Visada rodyti',
    'LBL_SHOW_INACTIVE_FIELDS' => 'Rodyti neaktyvius laukus',
	'LBL_SHOW_HIDDEN_FIELDS' => 'Žiūrėti paslėptus laukus',
	'LBL_DELETE_CUSTOM_BLOCK' => 'Pašalinti tinkintą bloką',
	'LBL_MANDATORY_FIELD' => 'Privalomas laukas',
	'LBL_ACTIVE' => 'Aktyvus',
	'LBL_QUICK_CREATE' => 'Greitasis kūrimas',
	'LBL_SUMMARY_FIELD' => 'Santrauka',
    'LBL_KEY_FIELD_VIEW' => 'Pagrindinio lauko vaizdas',
	'LBL_MASS_EDIT' => 'Dauginis redagavimas',
	'LBL_DEFAULT_VALUE' => 'Numatytoji reikšmė',
	'LBL_SELECT_FIELD_TYPE' => 'Pasirinkite lauko tipą',
	'LBL_LABEL_NAME' => 'Etiketė',
	'LBL_LENGTH' => 'Ilgis',
	'LBL_DECIMALS' => 'Skaitmenys po kablelio',
	'LBL_ENTER_PICKLIST_VALUES' => 'Įveskite išskleidžiamojo sąrašo reikšmes',
	'LBL_PICKLIST_VALUES' => 'Išskleidžiamojo sąrašo reikšmės',
	'LBL_INACTIVE_FIELDS' => 'Neaktyvūs laukai',
	'LBL_REACTIVATE' => 'Pakartotinai aktyvinti',
	'LBL_ARRANGE_RELATED_LIST' => 'Tvarkyti susijusius sąrašus',
	'LBL_SELECT_MODULE_TO_ADD' => 'Pasirinkite norimą pridėti modulį',
    'LBL_SELECT_HIDDEN_MODULE' => 'Pasirinti paslėptą modulį',
	'LBL_NO_RELATED_INFORMATION' => 'Susijusios informacijos nėra',
	'LBL_RELATED_LIST_INFO' => 'Tempkite modulius, jei norite pertvarkyti sąrašą.',
	'LBL_REMOVE_INFO' => 'Spustelėkite ištrynimo piktogramą, jei norite visam pašalinti santykius iš sąrašo',
	'LBL_ADD_MODULE_INFO' => 'Pasirinkite modulį iš pašalintųjų, kurį norite grąžinti atgal į sąrašą',
    'LBL_MANY_MANY_TEXT' => 'Daugelis-daugelis santykių šiuo metu yra prieinami tik %s ir %s',
	'LBL_SELECT_MODULE' => 'Pasirinkite modulį…',
	'LBL_DUPLICATES_EXIST' => 'Blokas tokiu pavadinimu jau egzistuoja',
	'LBL_NON_ROLE_BASED_PICKLIST' => 'Išskleidžiamasis sąrašas ne pagal vaidmenį',
	'LBL_DUPLICATE_FIELD_EXISTS' => 'Aptikti vienodi laukai',
	'LBL_WRONG_FIELD_TYPE' => 'Netinkamas lauko tipas',
	'LBL_ROLE_BASED_PICKLIST' => 'Išskleidžiamasis sąrašas pagal vaidmenį',
	'LBL_CLICK_HERE_TO_EDIT' => 'Spustelėkite čia, jei norite redaguoti',
    'LBL_EDIT_FIELD' => 'Redaguoti laukų nustatymus: %s',

	//Field Types
	'Text'=>'Tekstas (viena eilutė)',
	'Decimal'=>'Dešimtainė trupmena',
	'Integer'=>'Sveikasis skaičius',
	'Percent'=>'Procentinė reikšmė',
	'Currency'=>'Piniginė reikšmė',
	'Date'=>'Data',
	'Email'=>'El. paštas',
	'Phone'=>'Telefonas',
	'PickList'=>'Išskleidžiamasis sąrašas',
	'MultiSelectCombo'=>'Daugiareikšmis jungtinis langelis',
	'URL' => 'URL',
	'Checkbox' => 'Žymimasis langelis',
	'TextArea' => 'Tekstas (kelios eilutės)',
	'Skype'=>'„Skype“',
	'Time'=>'Laikas',
	
	//Translation for module
	'Calendar' => 'Užduotis',
	'LBL_FIELD_COULD_NOT_BE_CREATED'=>'Laukas %s nesukurtas',
	'SELECT_MODULE' => 'Pasirinkite modulį',
    
    //Related Lists 
    'LBL_RELATION_SHIPS' => 'Santykiai',
    'LBL_ADD_RELATIONSHIP' => 'Pridėti santykį',
    'LBL_RELATED_MODULE' => 'Susiję moduliai',
    'LBL_ADDING_RELATIONSHIP' => 'Pridedamas santykis %s',
    'LBL_SELECTED_RELATED_MODULE' => 'Pasirinkite susijusį modulį',
    'LBL_SELECTED_RELATION_TYPE' => 'Pasirinti santykio tipą',
    'ONE_ONE_AND_MANY_ONE_RELATIONSHIP' => 'Vieno-vieno ir daugelio-daugelio santykiai',
    'ONE_MANY_RELATIONSHIP' => 'Vieno-daugelio ir daugelio-daugelio santykiai',
    '1-1' => 'Vienas prie vieno',
    '1-N' => 'Vienas prie daugelio',
    'N-1' => 'Daugelis prie vieno',
    'N-N' => 'Daugelis prie daugelio',
    
	
	//New layout translations
	'LBL_FIELD_TYPES'                   => 'Laukų tipai', 
	'LBL_BASIC_FIELDS'             => 'Pagrindiniai laukai', 
	'LBL_MANDATORY'                => 'Privalomas laukas', 
	'LBL_PROPERTIES'               => 'Nustatymai', 
	'LBL_DRAG_UI_TYPE'             => 'Vilkite ir įmeskite lauką čia', 
	'LBL_RELATION_FIELDS'          => 'Santykio laukas', 
	'LBL_SELECT_BLOCK'             => 'Pasirinkti bloką', 
    'LBL_RELATION_ADDED_SUCCESS'   => 'Santykis pridėtas sėkmingai',
    
    'FIELD_NAME_IN_PRIMARY_MODULE' => 'Santykio laukas %s',
    'FIELD_NAME_IN_RELATED_MODULE' => 'Santykio laukas %s',
    'TAB_IN_PRIMARY_MODULE'        => 'Lentelė/skiltis %s',
    'TAB_IN_RELATED_MODULE'        => 'Lentelė/skiltis %s',
    
    'LBL_DETAIL_VIEW'              => 'Išsamus vaizdas',
    'LBL_EXPANDED'                 => 'Išplėstas',
    'LBL_COLLAPSED'                => 'Sutrauktas',
    
    'LBL_FILED_IN_PRIMARY_HELP_TEXT' => 'Palyginimo laukas %s modulio',
    'LBL_TAB_IN_PRIMARY_HELP_TEXT'   => 'Lentelė/skiltis %s modulio',
    'LBL_FILED_IN_RELATED_HELP_TEXT' => 'Palyginimo laukas %s modulio',
    'LBL_TAB_IN_RELATED_HELP_TEXT'   => 'Lentelė/skiltis %s modulio',
    'LBL_NO_RELATION_TYPE'         => 'Tokio tipo santykis neegzistuoja',

	'LBL_CREATE_ITEM_CUSTOM_FIELD' => 'Sukurti pasirinktinį lauką eilutės elementui',
	'LBL_MAP_PRODUCT_FIELD' => 'Susieti su produkto lauku',
	'LBL_MAP_SERVICE_FIELD' => 'Susieti su paslaugos lauku',
	'LBL_ENABLE_TO_MAP_PRODUCT_FIELD' => 'Įgalinti produkto lauko susiejimą',
	'LBL_ENABLE_TO_MAP_SERVICE_FIELD' => 'Įgalinti paslaugos lauko susiejimą',
    
    //Vtiger7 Strings
    'LBL_NO_RELATED_INFO' => 'Santykis neegzistuoja',
    'LBL_ADD_NEW_FIELD_HERE' => 'Pridėti naują lauką čia',
    'LBL_SAVE_LAYOUT' => 'Išsaugoti išdėstymą',
    'LBL_SHOW_FIELD' => 'Rodyti lauką',
    'LBL_ENABLE_OR_DISABLE_FIELD_PROP' => 'Įgalinti / išjungti lauko nustatymus',
    'LBL_PROP_MANDATORY' => 'privalomas',
    'LBL_DEFAULT_VALUE_NOT_SET' => 'Nepasirinkta numatytoji reikšmė',
    'LBL_INFO' => 'Informacija',
    'LBL_PRODUCTFIELDDEFAULTVALUE' => '(Produktai)',
    'LBL_SERVICEFIELDDEFAULTVALUE' => '(Paslaugos)',
    'LBL_SHOW_THIS_FIELD_IN' => 'Spauskite čia norėdami pamatyti šį lauką %s vaizde',
    'LBL_MAKE_THIS_FIELD' => 'Spauskite čia norėdami padaryti šį lauką %s',
    'LBL_HIDE_THIS_FIELD_IN' => 'Spauskite čia norėdami paslėpti šį lauką %s vaizde',
    'LBL_NOT_MAKE_THIS_FIELD' => 'Spauskite čia norėdami padaryti šį lauką ne-%s',
    'LBL_TAB_NAME_HELP_TEXT' => '%s sąrašas rodomas %s įraše',
    'LBL_TAB_NAME_TEXT' => '%s skilties pavadinimas %s įraše',
    'LBL_FILED_NAME_HELP_TEXT' => '%s palyginimo laukas %s įraše bus pridėtas',
    'LBL_FIELD_NAME_TEXT' => '%s lauko pavadinimas %s įraše',
	'LBL_COLLAPSE_BLOCK' => 'Sutraukti bloką',
	'LBL_COLLAPSE_BLOCK_DETAIL_VIEW' => 'Sutraukti bloką išsamiame vaizde',
    'LBL_HEADER' => 'Antraštė',
    'LBL_DETAIL_HEADER' => 'Įrašo antraštė',
    'LBL_HEADER_FIELD' => 'Antraštės rodinys',

	'LBL_DUPLICATE_HANDLING' => 'Duplicate Prevention',
	'LBL_DUPLICATE_CHECK' => 'Enable duplicate check',
	'LBL_DUPLICATION_INFO_MESSAGE' => 'Duplicate prevention feature only prevents new duplicate records from getting created by users and external applications. Records created from Import, and from Workflows will not be checked for duplicates.<br><br>Existing duplicate records can be removed using “Find Duplicates” feature from the module page.',
	'LBL_SELECT_FIELDS_FOR_DUPLICATION' => 'Select the unique fields on which duplicate records are to be checked',
	'LBL_SELECT_FIELDS' => 'Select Fields',
	'LBL_MAX_3_FIELDS' => 'Max 3 Fields',
	'LBL_SELECT_RULE' => 'Select rule for handling duplicates',
	'LBL_ALLOW_DUPLICATES' => 'Allow Duplicates',
	'LBL_DO_NOT_ALLOW_DUPLICATES' => 'Do not allow Duplicates',
	'LBL_DUPLICATES_IN_SYNC_MESSAGE' => 'Action to take if duplicate record is found while syncing with external application',
	'LBL_PREFER_LATEST_RECORD' => 'Prefer latest record',
	'LBL_PREFER_INTERNAL_RECORD' => 'Prefer internal record',
	'LBL_PREFER_EXTERNAL_RECORD' => 'Prefer external record',
	'LBL_SYNC_TOOLTIP_MESSAGE' => 'Prefer latest record - Most recently modified record data will be retained<br>Prefer internal record - Existing record will be retained as it is<br>Prefer external record - Data from the external application will be copied',
);

$jsLanguageStrings = array(
	'JS_BLOCK_VISIBILITY_SHOW' => 'Blokų rodymas įjungtas',
	'JS_BLOCK_VISIBILITY_HIDE' => 'Blokų slėpimas įjungtas',
	'JS_CUSTOM_BLOCK_ADDED' => 'Naujas tinkintas blokas pridėtas',
	'JS_BLOCK_SEQUENCE_UPDATED' => 'Blokų eilės tvarka atnaujinta',
	'JS_SELECTED_FIELDS_REACTIVATED' => 'Pažymėti laukai pakartotinai aktyvinti',
	'JS_FIELD_DETAILS_SAVED' => 'Lauko informacija įrašyta',
	'JS_CUSTOM_BLOCK_DELETED' => 'Tinkintas blokas pašalintas',
	'JS_CUSTOM_FIELD_ADDED' => '%s laukas pridėtas',
	'JS_CUSTOM_FIELD_DELETED' => 'Tinkintas laukas pašalintas',
	'JS_LENGTH_SHOULD_BE_LESS_THAN_EQUAL_TO' => 'Ilgis turi būti ne didesnis nei',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_2TO5' => 'Trupmeninė dalis turi būti nuo 2 iki 5 skaitmenų ilgio',
	'JS_SAVE_THE_CHANGES_TO_UPDATE_FIELD_SEQUENCE' => 'Jei norite atnaujinti laukų eilės tvarką, įrašykite pakeitimus',
	'JS_RELATED_INFO_SAVED' => 'Susijusi informacija įrašyta',
	'JS_BLOCK_NAME_EXISTS' => 'Blokas tokiu pavadinimu jau egzistuoja',
	'JS_NO_HIDDEN_FIELDS_EXISTS' => 'Nėra neaktyvių laukų',
	'JS_SPECIAL_CHARACTERS' => 'Ypatingi simboliai kaip',
	'JS_NOT_ALLOWED' => 'yra neleidžiami',
	'JS_FIELD_SEQUENCE_UPDATED' => 'Laukų eilės tvarka atnaujinta',
	'JS_DUPLICATES_VALUES_FOUND' => 'Rastos vienodos reikšmės',
    'JS_FIELD_IN_RELATED_MODULE'  => 'Santykio laukas %s',
    'JS_TAB_IN_RELATED_MODULE' => 'Lentelė/skiltis %s',
    'JS_FILED_IN_RELATED_HELP_TEXT' => 'Palyginimo laukas %s modulio',
    'JS_TAB_IN_RELATED_HELP_TEXT'   => 'Lentelė/skiltis %s modulio',
    'JS_TAB_FIELD_DELETION'   => 'Santykio ištrynimas pašalins %s lauką %s modulyje ir ištrins %s lentelę/skiltį %s. Ar tikrai norite tęsti?',
    'JS_ONE_ONE_RELATION_FIELD_DELETE' => 'Tai pašalins %s lauką %s modulyje ir ištrins %s lauką %s modulyje. Ar tikrai norite tęsti?',
	'JS_CUSTOM_FIELDS_MAX_LIMIT' => 'Galite pridėti ne daugiau kaip %s pasirinktinų laukų %s bloke',
    'JS_DEFAULT_VALUE_NOT_SET' => 'Nepasirinkta numatytoji reikšmė',
    'JS_DEFAULT_VALUE' => 'Numatytoji reikšmė',
    'JS_SAVE_MODULE_SEQUENCE' => 'Jei norite atnaujinti susijusių modulių eilės tvarką, įrašykite pakeitimus',
    'JS_PRODUCTFIELDDEFAULTVALUE' => '(Produktai)',
    'JS_SERVICEFIELDDEFAULTVALUE' => '(Paslaugos)',
    'JS_TAB_TAB_DELETION' => 'Tai ištrins %s skiltį %s modulyje ir visą informaciją joje. Ar tikrai norite tęsti?',
    'JS_SHOW_THIS_FIELD_IN' => 'Spauskite čia norėdami pamatyti šį lauką %s vaizde',
    'JS_MAKE_THIS_FIELD' => 'Spauskite čia norėdami padaryti šį lauką %s',
    'JS_HIDE_THIS_FIELD_IN' => 'Spauskite čia norėdami paslėpti šį lauką %s vaizde',
    'JS_NOT_MAKE_THIS_FIELD' => 'Spauskite čia norėdami padaryti šį lauką ne-%s',
    'JS_TAB_NAME_HELP_TEXT' => '%s sąrašas rodomas %s įraše',
    'JS_TAB_NAME_TEXT' => '%s skilties pavadinimas %s įraše',
    'JS_FILED_NAME_HELP_TEXT' => '%s palyginimo laukas %s įraše bus pridėtas',
    'JS_FIELD_NAME_TEXT' => '%s lauko pavadinimas %s įraše',
    'JS_PROP_MANDATORY' => 'privalomas',
    'JS_SUMMARY' => 'Santrauka',
    'JS_KEY_FIELD' => 'Pagrindinis laukas',
    
    'JS_QUICK_CREATE' => 'Greitasis kūrimas',
    'JS_MASS_EDIT' => 'Išplėstinis redagavimas',
    'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Ši operacija įvykdys negražinamą duomenų ištrynimą.
 Kai laukas yra ištrinamas, vertės saugomos šiame lauke bus ištryntos negražinamai.
 Jeigu neesate tikri ir galbūt norėsite peržiūrėti informaciją ateityje, galite pažymėti lauką kaip neaktyvų vietoj to, kad jį ištrynti. Neaktyvūs laukai vėliau gali būti aktyvuoti bet kokiu metu. 
 Ar tikrai norite ištrynti šį lauką?',
    'JS_FIELD_DELETE_CONFIRMATION' => 'Ištrinti - informacija šiame lauke yra nereikalinga.',
	'JS_STATUS_CHANGED_SUCCESSFULLY' => 'Būsena pakeista sėkmingai',
    'JS_FIELD_CAN_EITHER_BE_HEADER_OR_SUMMARY_ENABLED' => 'Laukas gali būti lauko antraštė arba pagrindinis laukas',
    'JS_DETAIL_HEADER' => 'Įrašo antraštė',
    'JS_MAXIMUM_HEADER_FIELDS_ALLOWED' => 'Leidžiama nedaugiau kaip %s lauko antraščių',
    'JS_NAME_FIELDS_APPEAR_IN_HEADER_BY_DEFAULT' => 'Pavadinimo laukai antraštėje pasirodo pagal numatymą',
    'JS_FIELD_IS_HEADER_ENABLED_FOR_VTIGER7' => 'Šis laukas tai antraštė įgalinta Vtiger7, ji pasirodys santraukos rodinyje',

	'JS_DUPLICATE_HANDLING_SUCCESS_MESSAGE' => 'Successfully updated to consider selected fields in duplicates prevention',
	'JS_DUPLICATE_HANDLING_FAILURE_MESSAGE' => 'Failed to consider selected fields in duplicates prevention',
	'JS_DUPLICATE_CHECK_DISABLED' => 'Duplicate check is disabled',
);
