<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'action' => 'Veiksmas',
	'ADD_RULES' => 'Pridėti taisykles',
	'After Scan'                   => 'Nuskaičius žymėti kaip'                  ,
	'ALL' => 'visus',
	'Begins With' => 'Pradėti',
	'body' => 'Pagrindinė dalis',
	'Connect URL'                  => 'Jungimosi URL'                 , 
	'Contains' => 'yra tekstas',
	'CREATE_Accounts_SUBJECT' => 'Sukurti organizaciją',
	'CREATE_Contacts_SUBJECT' => 'Sukurti adresatą',
	'CREATE_HelpDesk_FROM' => 'Sukurti užduoties kortelę',
	'CREATE_Leads_SUBJECT' => 'Sukurti potencialų klientą',
	'Do Not Validate SSL Certificate'=> 'netikrinti liudijimų',
	'Ends With' => 'Pabaiga',
	'Equals' => 'lygu',
	'fromaddress' => 'Nuo',
	'LBL_ACTION' => 'Veiksmas',
	'LBL_ACTIONS' => 'Veiksmai',
	'LBL_ADDING_NEW_MAILBOX' => 'Naujos pašto dėžutės pridėjimas',
	'LBL_ADD_RECORD' => 'Pridėti pašto dėžutę',
	'LBL_ADD_RULE' => 'Pridėti taisyklę',
	'LBL_ALL_CONDITIONS' => 'Visos sąlygos',
	'LBL_ALL_MESSAGES_FROM_LAST_SCAN' => 'Visi pastarąjį kartą nuskaityti laiškai',
	'LBL_ANY_CONDITIOn' => 'Bet kuri sąlyga',
	'LBL_BACK_TO_MAILBOXES' => 'Grįžti į pašto dėžučių sąrašą',
	'LBL_BODY' => 'Pagrindinė dalis',
	'LBL_CONDITIONS' => 'Sąlygos',
	'LBL_CONNECTION_ERROR' => 'Prisijungti prie pašto dėžutės nepavyko. Patikrinkite nurodytus parametrus bei tinklo veikimą ir bandykite iš naujo.', 
	'LBL_CONNECTION_TO_MAILBOX_FAILED' => 'Prisijungti prie pašto dėžutės nepavyko!<br>Serverio varde negali būti specialiųjų simbolių.',
	'LBL_CONVERT_EMAILS_TO_RESPECTIVE_RECORDS' => 'Konvertuoti laiškus į atitinkamus įrašus',
	'LBL_CREATE_MAILBOX' => 'Kurti pašto dėžutę',
	'LBL_CREATE_MAILBOX_NOW' => 'Kurti pašto dėžutę dabar',
	'LBL_DELETED_SUCCESSFULLY' => 'Pašalinta sėkmingai', //Duplicated key-value pair
	'LBL_DELETE_RULE' => 'Pašalinti taisyklę',
	'LBL_DISABLE' =>'Išjungti',
	'LBL_DO_NOT_VALIDATE_SSL_CERTIFICATE' => 'netikrinti liudijimų',
	'LBL_DRAG_AND_DROP_BLOCK_TO_PRIORITISE_THE_RULE' => 'Taisyklės numeris nurodo jos prioritetą. Pertempkite taisykles, jei norite keisti jų prioritetus.',
	'LBL_EDIT_MAILBOX' => 'Redaguoti pašto dėžutę',
	'LBL_ENABLE' => 'Įjungti',
	'LBL_FINISH' => 'Pabaigti',
	'LBL_FOLDERS_INFO_IS_EMPTY' => 'Duomenų apie aplankus nėra',
	'LBL_FOLDERS_SCANNED' => 'Aplankai nuskaityti',
	'LBL_FROM' => 'Nuo',
	'LBL_I_DONT_KNOW' => "nežinau",
	'LBL_IS_IN_RUNNING_STATE' => 'Veikimo būsenoje', //Duplicated key-value pair
	'LBL_MAILBOX' => 'Pašto dėžutė',
	'LBL_MAILCONVERTER_DESCRIPTION' => "Laiškų keitiklis suteikia galimybę nuskaityti laiškus, gaunamus į nurodytą pašto dėžutę, ir pagal juos kurti reikiamus įrašus šioje sistemoje.<br/>Sukonfigūravę pašto dėžutę, turėsite aprašyti taisykles, pagal kurias bus vykdomi veiksmai su laiškais.<br/>Laiškai bus nuskaitomi automatiškai, nebent Tvarkaraštyje išjungsite „Mail Scanner“ periodinį darbą.<br/><br/><br/>",
	'LBL_MARK_MESSAGE_AS' => 'Žymėti žinutę kaip',
	'LBL_MARK_MESSAGES_AS_READ' => 'Žymėti žinutes kaip skaitytas',
	'LBL_MARK_READ' => 'Žymėti kaip skaitytą',
	'LBL_MATCH' => 'Pritaikyti',
	'LBL_MAX_LIMIT_ONLY_TWO' => 'Viršytas didžiausias leistinas pašto dėžučių kiekis!',
	'LBL_NEXT' => 'Toliau',
	'LBL_PRIORITY' => 'Prioritetas', //Duplicated key-value pair
	'LBL_RULE_DELETION_FAILED' => 'Taisyklės pašalinti nepavyko', //Duplicated key-value pair
	'LBL_RULE' => 'Taisyklė',
	'LBL_RULES_LIST' => 'Taisyklių sąrašas',
	'LBL_RULES_SEQUENCE_INFO_IS_EMPTY' => 'Neužpildyta informacija apie taisyklių eilės tvarką', //Duplicated key-value pair
	'LBL_SAVED_SUCCESSFULLY' => 'Įrašyta sėkmingai',
	'LBL_SCANED_SUCCESSFULLY' => 'Nuskaityta sėkmingai',
	'LBL_SCANNED_SUCCESSFULLY' => 'Nuskaityta sėkmingai',
	'LBL_SCAN_NOW' => 'Nuskaityti dabar',
	'LBL_SELECT_FOLDERS' => 'Pasirinkite aplankus',
	'LBL_SEQUENCE_UPDATED_SUCCESSFULLY' => 'Eilės tvarka atnaujinta sėkmingai',
	'LBL_STATUS_MESSAGE' => 'Pažymėkite, kad taptų aktyvus',
	'LBL_UNREAD_MESSAGES_FROM_LAST_SCAN' => 'Neskaityti po paskutinio nuskaitymo',
	'LBL_UNSELECT_ALL' => 'Nežymėti nieko',
	'LBL_UPDATE_FOLDERS' => 'Atnaujinti aplankus',
	'LBL_VALIDATE_SSL_CERTIFICATE' => 'tikrinti liudijimus',
	'LINK_Accounts_FROM' => 'Pridėti prie organizacijos [NUO]',
	'LINK_Accounts_TO' => 'Pridėti prie organizacijos [KAM]',
	'LINK_Contacts_FROM' => 'Pridėti prie adresato [NUO]',
	'LINK_Contacts_TO' => 'Pridėti prie adresato [KAM]',
	'LINK_Leads_FROM' => 'Pridėti prie potencialaus kliento [NUO]',
	'LINK_Leads_TO' => 'Pridėti prie potencialaus kliento [KAM]',
	'Look For'                     => 'Nuskaityti laiškus'                    , 
	'MAILBOX_DETAILS' => 'Pašto dėžutės informacija',
	'MAILBOX' => 'Pašto dėžutė',
	'MailConverter_Description' => 'Konvertuoti laiškus į atitinkamus įrašus',
	'MailConverter' => 'Laiškų keitiklis',
	'markas'                       => 'Nuskaičius žymėti kaip'                  ,
	'matchusing' => 'Pritaikyti',
	'Not Contains' => 'nėra teksto',
	'Not Equals' => 'nelygu',
	'Password'                     => 'Slaptažodis'                    , 
	'PRIORITISE_MESSAGE' => 'Tempkite blokus, jei norite keisti taisyklių prioritetus prioritetus',
	'Protocol'                     => 'Protokolas'                    , 
	'Regex' => 'Reguliarusis reiškinys',
	'RULE' => 'Taisyklė',
	'Scanner Name'                 => 'Skaitytuvo vardas'                , 
	'SEEN' => 'skaitytus',
	'SELECT_FOLDERS' => 'Pasirinkite aplankus',
	'Server'                       => 'Serverio vardas'                 , 
	'SSL Method'                   => 'Liudijimų patikra'                  , 
	'SSL Type'                     => 'Ryšio šifravimas'                    , 
	'Status'                       => 'Būklė'                      ,
	'subject' => 'Tema ',
	'Time Zone'                    => 'Laiko juosta'                   ,
	'toaddress' => 'Kam',
	'TO_CHANGE_THE_FOLDER_SELECTION_DESELECT_ANY_OF_THE_SELECTED_FOLDERS' => 'Jei norite pakeisti pasirinktus aplankus, pirma pašalinkite bent vieno aplanko pasirinkimą',
	'UNSEEN' => 'neskaitytus',
	'UPDATE_HelpDesk_SUBJECT' => 'Atnaujinti užduoties kortelę',
	'User Name'                    => 'Naudotojo vardas'                   , 
	'Validate SSL Certificate'     => 'tikrinti liudijimus'    ,
);

$jsLanguageStrings = array(
	'JS_MAILBOX_DELETED_SUCCESSFULLY' => 'Pašto dėžutės įrašas sėkmingai pašalintas',
	'JS_MAILBOX_LOADED_SUCCESSFULLY' => 'Pašto dėžutės įrašas sėkmingai įkeltas',
);	
