<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	// Basic Strings
	'Settings' => 'Nuostatos',
	'LBL_MAILROOM'=>'Pašto skyrius',
	'LBL_SEARCH_SETTINGS_PLACEHOLDER' => 'Ieškoti nuostatose',
	'LBL_SUMMARY' => 'Faktai',
	'LBL_ACTIVE_USERS' => 'Naudotojai',
	'LBL_WORKFLOWS_ACTIVE' => 'Darbo procesai',
	'LBL_MODULES' => 'Moduliai',
	'LBL_SETTINGS_SHORTCUTS' => 'Sparčiosios nuostatos',
	'LBL_UNPIN' => 'Nusegti',
	'LBL_PIN' => 'Prisegti',

	// Blocks
	'LBL_STUDIO' => 'Studija',
	'LBL_COMMUNICATION_TEMPLATES' => 'Šablonai',
	'LBL_USER_MANAGEMENT' => 'Naudotojai ir prieiga',
	'LBL_ACCESS_MANAGEMENT' => 'Prieigos valdymas',
	'LBL_MODULE_MANAGER' => 'Modulių tvarkymas',
	'LBL_NOTIFICATIONS' => 'Pranešimai',
	'LBL_EXTERNAL_SERVER_SETTINGS' => 'Išorinio serverio nuostatos',
	'LBL_OTHER_SETTINGS' => 'Kitos nuostatos',
	'LBL_EXTENSIONS_PLACE' => 'Priedų vieta',
	'LBL_EXTENSIONS' => 'Priedai',
	'LBL_PBXMANAGER' => 'PBX tvarkytuvė',
    'LBL_INTEGRATION' => 'Integracija',
    'LBL_EXCHANGE_CONNECTOR' => 'Exchange Connector',
    
    // Fields
	'LBL_DESCRIPTION' => 'Aprašymas',
    
	// Other Strings
	'LBL_USER_DESCRIPTION' => 'Tvarkyti šios sistemos naudotojus',
	'LBL_ROLES' => 'Vaidmenys',
	'LBL_ROLE_DESCRIPTION' => 'Redaguoti vaidmenų hierarchiją ir priskyrimą naudotojams',

	'LBL_PROFILES' => 'Profiliai',
	'LBL_PROFILE_DESCRIPTION' => 'Tvarkyti modulių prieigą skirtingų vaidmenų naudotojams',

	'USERGROUPLIST' => 'Grupės',
	'LBL_GROUP_DESCRIPTION' => 'Tvarkyti skirtingus komandų tipus pagal vaidmenis, naudotojus ir profilius',

	'LBL_SHARING_ACCESS' => 'Prieigos taisyklės',
	'LBL_SHARING_ACCESS_DESCRIPTION' => 'Tvarkyti modulių prieigos taisykles',

	'LBL_WORKFLOW_LIST' => 'Darbo procesų sąrašas',
	'LBL_AVAILABLE_WORKLIST_LIST' => 'Galimi darbo procesai',
	'LBL_FIELDFORMULAS' => 'Laukų formulės',
	'LBL_FIELDFORMULAS_DESCRIPTION' => 'Pridėti tinkintas lygtis pasirinktiems laukams',

	'VTLIB_LBL_MODULE_MANAGER' => 'Moduliai',
	'VTLIB_LBL_MODULE_MANAGER_DESCRIPTION' => 'Valdyti modulių elgseną CRM sistemoje',
	'LBL_PICKLIST_EDITOR' => 'Parinkčių sąrašo laukų reikšmės',
	'LBL_PICKLIST_DESCRIPTION' => 'Redaguoti visų modulių parinkčių sąrašų reikšmes',
	'LBL_PICKLIST_DEPENDENCY_SETUP' => 'Parinkčių sąrašų priklausomybės',
	'LBL_PICKLIST_DEPENDENCY_DESCRIPTION' => 'Konfigūruoti visų modulių parinkčių sąrašų reikšmių priklausomybes',

	'LBL_FIELDFORMULAS' => 'Laukų formulės',
	'LBL_FIELDFORMULAS_DESCRIPTION' => 'Pridėti tinkintas lygtis pasirinktiems laukams',

	'LBL_MENU_EDITOR' => 'Pagrindinis meniu',
	'LBL_MENU_DESC' => 'Tvarkyti meniu juostos elementus',
	'LBL_MENU_EDITOR_MESSAGE' => 'Priklausomai nuo ekrano dydžio, meniu gali būti matoma mažiau elementų, nei čia pasirinkta.',

	'EMAILTEMPLATES' => 'Laiškų šablonai',
	'LBL_EMAIL_TEMPLATE_DESCRIPTION' => 'Tvarkyti pašto dėžutės modulio šablonus',

	'LBL_COMPANY_DETAILS' => 'Įmonės informacija',
	'LBL_COMPANY_DESCRIPTION' => 'Įvesti įmonės adresą',

	'LBL_MAIL_MERGE' => 'Laiškų komponavimas',
	'LBL_MAIL_MERGE_DESCRIPTION' => 'Tvarkyti laiškų komponavimo šablonus',

	'LBL_TAX_SETTINGS' => 'Mokesčių tvarkytuvė',
	'LBL_TAX_DESCRIPTION' => 'Tvarkyti mokesčius ir jų dydžius',

	'LBL_MAIL_SERVER_SETTINGS' => 'Laiškų išsiuntimo serveris',
	'LBL_MAIL_SERVER_DESCRIPTION' => 'Konfigūruoti laiškų išsiuntimo serverį',

	'INVENTORYTERMSANDCONDITIONS' => 'Inventorius: terminai ir sąlygos',
	'LBL_INV_TANDC_DESCRIPTION' => 'Redaguoti terminus ir sąlygas, naudojamus pasiūlymuose, sąskaitose faktūrose ir pardavimų užsakymuose',

	'LBL_ANNOUNCEMENT_DESCRIPTION' => 'Tvarkyti įmonės darbuotojams rodomus pranešimus',

	'LBL_CURRENCY_SETTINGS' => 'Valiutos',
	'LBL_CURRENCY_DESCRIPTION' => 'Tvarkyti valiutas ir jų kursus',

	'LBL_CUSTOMIZE_MODENT_NUMBER' => 'Modulių numeravimas',
	'LBL_CUSTOMIZE_MODENT_NUMBER_DESCRIPTION' => 'Tinkinti modulių įrašų numeravimą',

	'LBL_MAIL_SCANNER' => 'Laiškų keitiklis',
	'LBL_MAIL_SCANNER_DESCRIPTION' => 'Konfigūruoti el. pašto dėžutę, naudojamą laiškų nuskaitymui ir įrašų priedams',

	'LBL_LIST_WORKFLOWS' => 'Darbo procesai',
	'LBL_LIST_WORKFLOWS_DESCRIPTION' => 'Kurti ir redaguoti darbo procesus',
    'LBL_SELECT_DATE' => 'Pasirinkite datas',

	'Configuration Editor' => 'Konfigūracijos rengyklė',
	'LBL_CONFIG_EDITOR_DESCRIPTION' => 'Atnaujinti programos konfigūracijos failą',
	'Update configuration file of the application' => 'Atnaujinti programos konfigūracijos failą',
	'LBL_PERSONAL_EMAIL_TRACKING_INFO' => "Jei norite stebėti tiesioginių el. laiškų, siunčiamų kontaktams, atidarymą, įgalinkite šį žymimąjį laukelį. Atkreipkite dėmesį, kad elektroninis paštas, išsiųstas iš modulio el. pašto kampanijos, visuomet yra stebimas ir nepaveiktas šio nustatymo",
	'LBL_CUSTOMER_PORTAL' => 'Klientų portalas',
	'PORTAL_EXTENSION_DESCRIPTION' => 'Konfigūruoti klientų portalo įskiepį',
	
	'LBL_LAYOUT_EDITOR_DESCRIPTION' => 'Projektuoti ir redaguoti visų modulių rodinius',
	'LBL_WEBFORMS_DESCRIPTION' => 'Kurti ir tvarkyti žiniatinklio formas, naudojamas potencialių klientų užklausoms, kontaktams, užduočių kortelėms ir t.t. pritraukti',
	'LBL_TO_ADD_NEW_USER_PLEASE_CLICK_ON' => 'Jei norite pridėti naują naudotoją, spustelėkite',
	'LBL_SETTINGS_ICON' => 'Nuostatų piktograma',
	'LBL_ADD_OR_DELETE_USERS' => 'Pridėti / šalinti naudotojus',
	'LBL_ADD_USER' => 'Pridėti naudotoją',
	'LBL_LABELS_EDITOR' => 'Žymių redaktorius',
	'LBL_LABELS_EDITOR_DESCRIPTION' => 'Galite keisti modulių pavadinimus, laukų žymes ir kitas eilutes pagal savo verslo reikalavimus',

	'Scheduler' => 'Tvarkaraštis',
	'Allows you to Configure Cron Task' => 'Konfigūruoti automatinius periodinius darbus',

	'Webforms' => 'Saityno formos',
	'Allows you to manage Webforms' => 'Tvarkyti saityno formas',
	'LBL_CREATING_NEW' => 'Kuriamas naujas įrašas',
	'LBL_EDITING' => 'Redagavimas: ',
	'LBL_EDIT_RECORD' => 'Redaguoti  ',
	'LBL_DELETE_RECORD' => 'Šalinti',

	//Menu Editor
	'LBL_ADD_MOVE_MENU_ITEMS' => 'Pridėti / tvarkyti meniu elementus',
	'LBL_ADD_MENU_ITEM' => 'Pridėti meniu elementą',
	'LBL_MAX' => 'Maks.',
	
	//Tax Calculations
	'LBL_TAX_CALCULATIONS' => 'Mokesčių tvarkytuvė',
	'LBL_TAX_DESC'=>'Tvarkyti mokesčius (tokius, kaip PVM ar akcizai) ir jų dydžius',
	'LBL_PRODUCT_SERVICE_TAXES' => 'Prekių ir paslaugų mokesčiai',
	'LBL_SHIPPING_HANDLING_TAXES' => 'Pristatymo ir tvarkymo mokesčiai',
	'LBL_ADD_NEW_TAX' => 'Pridėti naują mokestį',
	'LBL_EDIT_TAX' => 'Mokesčio redagavimas',
	'LBL_TAX_NAME' =>  'Mokesčio pavadinimas',
	'LBL_TAX_VALUE' => 'Mokesčio dydis',
	'LBL_STATUS' => 'Būsena',
	'LBL_TAX_STATUS_DESC' => 'pažymėkite varnelę, kad mokestis būtų aktyvus',
	'LBL_ENTER_TAX_NAME' => 'Įveskite mokesčio pavadinimą',
	'LBL_ENTER_TAX_VALUE' => 'Įveskite mokesčio dydį',
	'LBL_TAX_NAME_EXIST' => 'Mokestis tokiu pavadinimu jau egzistuoja',
	'LBL_TAXES' => 'Mokesčiai',
	'LBL_CHARGES_AND ITS_TAXES' => 'Rinkliava(su mokesčiais)',
	'LBL_TAX_REGIONS' => 'Mokesčių regionai',
	'LBL_NO_REGION_EXISTS' => 'Nėra regiono',
	'LBL_TYPE' => 'Tipas',
	'LBL_CALCULATION' => 'Skaičiavimas',
	'LBL_ADD_NEW_CHARGE' => 'Pridėti naują rinkliavą',
	'LBL_ADD_NEW_TAX_FOR_CHARGE' => 'Pridėti naują mokestį rinkliavai',
	'LBL_CHARGE_NAME' => 'Rinkliavos pavadinimas',
	'LBL_CHARGE_NAME_EXIST' => 'Rinkliava tokiu pavadinimu jau egzistuoja',
	'LBL_VALUE' => 'Vertė',
	'LBL_IS_TAXABLE' => 'Apmokestinamas',
	'LBL_AVAILABLE_REGIONS' => 'Galimi regionai',
	'LBL_ADD_NEW_REGION' => 'Pridėti naują regioną',
	'LBL_TAX_REGION_DESC' => 'Mokesčių regionai bus rodomi sukuriant kintamuosius mokesčius ir gali būti pasirenkami kuriant kainas, sąskaitas faktūras, pardavimo užsakymus, pirkimo užsakymą',
	'LBL_TAX_CALCULATION' => 'Mokesčių apskaičiavimas',
	'LBL_SIMPLE' => 'Paprastas',
	'LBL_COMPOUND' => 'Sudėtinis',
	'LBL_DEDUCTED' => 'Atskaičiuotas',
	'LBL_TAX_TYPE' => 'Mokesčio tipas',
	'LBL_FIXED' => 'Fiksuotas',
	'LBL_VARIABLE' => 'Kintamasis',
	'LBL_COMPOUND_ON' => 'Sudėtas',
	'LBL_DEFAULT_VALUE' => 'Numatytas',
	'LBL_ADD_TAX_BRACKET' => 'Pridėti mokesčių rėmus',
	'LBL_TAX_BRACKETS_DESC' => 'Jei nepasirinksite mokesčių vertės regionui, bus naudojama numatytoji vertė',
	'LBL_SELECT_SIMPLE_TAXES' => 'Pasirinkti paprastus mokesčius',
	'LBL_REGION_NAME' => 'Regiono pavadinimas',
	'LBL_ENTER_REGION_NAME' => 'Įrašykite regiono pavadinimą',
	'LBL_EDIT_REGION' => 'Redaguoti regioną',
	'LBL_TAX_REGION_EXIST' => 'Regionas tokiu pavadinimu jau egzistuoja',
	'LBL_EDIT_CHARGE' => 'Redaguoti rinkliavą',
	'LBL_CHARGE_FORMAT' => 'Rinkliavos formatas',
	'LBL_FLAT' => 'Vienodo dydžio',
	'LBL_DIRECT_PRICE' => 'Tiesioginė kaina',
	'LBL_PERCENT' => 'Procentas',
	'LBL_CHARGE_TYPE' => 'Rinkliavos tipas',
	'LBL_CHARGE_VALUE' => 'Rinkliavos reiksmė',
	'LBL_ENTER_CHARGE_NAME' => 'Įrašykite rinkliavos pavadinimą',
	'LBL_ENTER_CHARGE_VALUE' => 'Įrašykite rinkliavos vertę',
	'LBL_REGIONS' => 'Regionai',
	'LBL_ENABLE_TAXES_FOR_CHARGE' => 'Įgalinti jeigu rinkliava apmokestinama',
	'LBL_SELECT_TAX' => 'Pasirinkite mokestį',
	'LBL_SELECT_TAXES' => 'Pasirinkite mokesčius',
	'LBL_SELECT_REGIONS' => 'Pasirinkite regionus',
	'LBL_SELECT_TAX_DESC' => 'Pateikiami mokesčiai tik už rodomą rinkliavą',
	'LBL_CHARGE_STORE_DISC' => 'Rinkliavos vertė visada saugoma bazine valiuta',
	'LBL_DEDUCTED_TAX_DISC' => 'Išskaičiuojami mokesčiai apskaičiuojami visoms prekėms ir yra išskaičiuojami iš visos sumos',

	//Terms & conditions
	'LBL_TERMS_AND_CONDITIONS' => 'Terminai ir sąlygos',
	'LBL_SPECIFY_TERMS_AND_CONDITIONS' => 'Įveskite terminus ir sąlygas čia',
	//Announcements
	'LBL_ANNOUNCEMENTS' => 'Pranešimai',
	'LBL_ENTER_ANNOUNCEMENT_HERE' => 'Įveskite pranešimą čia',
	'LBL_ANNOUNCEMENT_DESC' => 'Pakeisti tekstą, rodomą pranešimo skiltyje visų tinklalapių viršuje',

	//Outgoing Server
	'LBL_RESET_TO_DEFAULT' => 'Atstatyti numatytąsias reikšmes',
	'LBL_SERVER_NAME' => 'Serverio vardas',
	'LBL_USER_NAME' => 'Naudotojo vardas',
	'LBL_PASSWORD' => 'Slaptažodis',
	'LBL_FROM_EMAIL' => 'Siuntėjo el. pašto adresas',
    'LBL_SERVER_TYPE' => 'Serverio tipas',
    'LBL_OTHERS' => 'Kitas',
    'LBL_GMAIL' => 'Gmail',
    'LBL_HOTMAIL' => 'Hotmail',
    'LBL_YAHOO' => 'Yahoo',
    'LBL_OFFICE365' => 'Office365',
    'LBL_VTIGER' => 'Vtiger',
	'LBL_REQUIRES_AUTHENTICATION' => 'Reikalinga autentikacija',
	'LBL_OUTGOING_SERVER' => 'Laiškų išsiuntimo serveris',
	'LBL_OUTGOING_SERVER_DESC' => 'Įveskite savo laiškų išsiuntimo serverio duomenis',
	'LBL_DEFAULT'=>'Numatytai SMTP paskyros nuostatose nurodomas laiškų išsiuntimo serveris od1.vtiger.com. Siekiant išvengti laiškų sulaikymo jūsų laiškų gavėjų naudojamų serverių brukalo filtruose, siūlome atlikti vieną iš toliau aprašytų veiksmų.',
	'LBL_OPTIONS1'=>'Siųskite laiškus iš savo pašto serverio<br>
- Įveskite „SMTP“ duomenis (serverio vardą, vartotojo vardą, slaptažodį) to patčio vartotojo, kaip nurodyta nuo lauke el. pašto adrese.',
	'LBL_OPTIONS2'=>"Pridėkite „vtiger.com“ serverį kaip įgaliotą jūsų domeno el. pašto siuntėją <b> (jūsų_įmonė.lt)</b> Kai naudojate savo <b> Nuo el. paštą (pvz.: pagalba@jūsų_įmonė.lt)</b>.<br>
						-Kad užtikrintumėte, kad jūsų el. laiškai gavėjo serveryjė nebūtų atmesti kaip šlamštas, 
						žemiau paminėtas „TXT“ įrašas turėtų būti pridėtas prie jūsų domeno „DNS“ įrašo",
	'LBL_MAIL_SERVER_SMTP'=>'Laiškų išsiuntimo serverio nuostatos (SMTP)',
	'LBL_OUTGOING_SERVER_FROM_FIELD'=>'PASTABA: jei laukas „Nuo el. pašto“ yra tuščias, bus naudojamas vartotojo el. pašto adresas.',
	'LBL_TESTMAILSTATUS'=>'Bandomojo laiško būsena: ',
	'LBL_MAILSENDERROR'=>'Laiško administratoriui išsiųsti nepavyko. Patikrinkite administratoriaus el. pašto adresą ir serverio nuostatas',
	
	//Configuration Editor
	'LBL_CONFIG_EDITOR' => 'Konfigūracijos rengyklė',
	'LBL_CONFIG_DESCRIPTION' => 'Pataisykite reikiamus CRM konfigūracijos laukus',
	'LBL_CONFIG_FILE' => 'config.inc.php',
	'LBL_MB' => 'MB',

	//Config Editor Fields
	'LBL_MINI_CALENDAR_DISPLAY' => 'Mini kalendoriaus rodinys',
	'LBL_WORLD_CLOCK_DISPLAY' => 'Rodyti pasaulio laikrodį',
	'LBL_CALCULATOR_DISPLAY' => 'Skaičiuotuvo rodymas',
	'LBL_USE_RTE' => 'Naudoti RTE',
	'LBL_HELPDESK_SUPPORT_EMAILID' => 'Pagalbos tarnybos el. pašto adresas',
	'LBL_HELPDESK_SUPPORT_NAME' => 'Pagalbos tarnybos pavadinimas',
	'LBL_MAX_UPLOAD_SIZE' => 'Maksimalus leistinas įkeliamo failo dydis (iki %sMB)',
	'LBL_MAX_HISTORY_VIEWED' => 'Registro limitas peržiūrai',
	'LBL_DEFAULT_MODULE' => 'Numatytasis modulis',
	'LBL_MAX_TEXT_LENGTH_IN_LISTVIEW' => 'Didžiausias teksto eilutės ilgis sąrašo rodinyje',
	'LBL_MAX_ENTRIES_PER_PAGE_IN_LISTVIEW' => 'Eilučių kiekis viename sąrašo puslapyje',
	'LBL_EMAIL_TRACKING' => 'Įjungti el. pašto sekimą',
	'LBL_INVALID_EMAILID' => 'Netinkamas el. pašto adresas',
	'LBL_INVALID_SUPPORT_NAME' => 'Netinkamas pagalbos tarnybos pavadinimas',
	'LBL_INVALID_MODULE' => 'Netinkamas modulis',
	'LBL_INVALID_NUMBER' => 'Netinkamas skaičius',
	'LBL_FIELDS_INFO_IS_EMPTY' => 'Laukų reikšmės nepateiktos',

	//CustomRecordNumbering
	'LBL_SUCCESSFULLY_UPDATED' => 'Sėkmingai atnaujinta',
	'LBL_CUSTOMIZE_RECORD_NUMBERING' => 'Modulių numeravimas',
	'LBL_MODULE_ENTITY_NUMBER_CUSTOMIZATION' => 'Modulių objektų numerių tinkinimas',
	'LBL_UPDATE_MISSING_RECORD_SEQUENCE' => 'Atnaujinti trūkstamų įrašų seką',
	'LBL_USE_PREFIX' => 'Naudoti prefiksą',
    'LBL_PREFIX_IN_USE' => 'Priešdėlis jau naudojamas',
	'LBL_START_SEQUENCE' => 'Numeruoti nuo',

	//Company Details
	'organizationname' => 'Įmonės pavadinimas',
	'logoname' => 'Įmonės logotipas',
	'address' => 'Adresas',
	'city' => 'Miestas',
	'state' => 'Savivaldybė / valstija',
	'code'  => 'Pašto kodas',
	'country' => 'Šalis',
	'phone' => 'Telefonas',
	'fax' => 'Faksas',
	'website' => 'Svetainė',
	'vatid' => 'PVM kodas',
	'facebook' => 'Facebook',
    'twitter' => 'Twitter',
    'linkedin' => 'LinkedIn',
	'LBL_IMAGE_CORRUPTED' => 'Aptiktas virusas arba įkeltas sugadintas paveikslas',
	'LBL_LOGO_RECOMMENDED_MESSAGE' => 'Leidžiamas dydis  150X40 taškų( .jpeg , .jpg , .png , .gif , .pjpeg , .x-png failų tipai ).',
	'LBL_COMPANY_INFORMATION' => 'Įmonės informacija',
	'LBL_UPDATE' => 'Atnaujinti',
	'LBL_UPDATE_LOGO' => 'Atnaujinti logotipą',
	'LBL_COMPANY_LOGO' => 'Įmonės logotipas',
    'LBL_NO_LOGO_EDIT_AND_UPLOAD' => 'Nėra paveiksliuko, redaguoti ir įkelti paveiksliuką',
	'LBL_EDIT_COMPANY_DETAILS_MESSAGE' => 'Kai norėsite koreguoti įmonės informaciją, spustelėkite nuostatų piktogramą, tuomet pasirinkite nuostatų meniu punktą „Šablonai“ > „Įmonės informacija“',
    
    'LBL_ACTIVE' => 'Aktyvus',
    'LBL_INACTIVE' => 'Neaktyvus',
    
    //show last scan in workflows and mailconverter
    'LBL_DISABLED' => 'Išjungta',
    'LBL_RUNNING' => 'Vykdomas',
    'LBL_LAST_SCAN_TIMED_OUT' => 'Paskutinis nuskaitymas nepavyko (baigėsi laikas)',
    'LBL_LAST_SCAN_AT' => 'Paskutinis nuskaitymas vyko ',
    'LBL_TIME_TAKEN' => 'užtrukta laiko ',
    'LBL_SHORT_SECONDS' => 'sek.',
	
	//Email Templates
	'EmailTemplate' => 'Laiško šablonas',
	'LBL_TEMPLATE_NAME' => 'Šablono pavadinimas',
	'LBL_DESCRIPTION' => 'Aprašymas',
	'LBL_SUBJECT' => 'Tema ',
	
	//User Login History
	'LoginHistory' => 'Naudotojo prisijungimų žurnalas',
	'LBL_LOGIN_HISTORY_DETAILS' => 'Prisijungimų registras',
	'LBL_LOGIN_HISTORY_DESCRIPTION' => 'Peržiūrėti naudotojų prisijungimo registrą',
	'LBL_USER_NAME'=> 'Naudotojo vardas',
	'LBL_USER_IP_ADDRESS'=> 'Naudotojo IP adresas', 
	'LBL_LOGIN_TIME' => 'Prisijungimo laikas',
	'LBL_LOGGED_OUT_TIME' => 'Atsijungimo laikas', 
	'LBL_STATUS' => 'Būsena',
    
    // Leads and Potentials Mapping 
    'LBL_SAVED_SUCCESSFULLY' => 'Įrašyta sėkmingai',
	'LBL_DELETED_SUCCESSFULLY' => 'Pašalinta sėkmingai',
	'LBL_INVALID_MAPPING' => 'Netinkamas susiejimas',
    'LBL_FIELD_LABEL' => 'Lauko etiketė',
	'LBL_FIELD_TYPE' => 'Lauko tipas',
	'LBL_MAPPING_WITH_OTHER_MODULES' => 'Susiejimas su kitais moduliais',
    'LBL_ADD_MAPPING' => 'Pridėti susiejimą',
	'LBL_NONE' => 'Nėra',
    
    //Field Type Translation
	'phone' => 'Telefonas',
	'picklist' => 'Parinkčių sąrašas',
	'email' => 'El. paštas',
	'text' => 'Eilutė',
	'currency' => 'Valiuta',
	'multiSelectCombo' => 'Daugiareikšmis jungtinis langelis',
	'time' => 'Laikas',
	'textArea' => 'Teksto vieta',
	'url' => 'Nuoroda',
	'string' => 'Eilutė',
	'checkBox' => 'Žymimasis langelis',
	'date' => 'Data',
	'decimal' => 'Dešimtainis',
	'percent' => 'Procentas',
	'skype' => 'Skype',
	'image' => 'Atvaizdas',
	'LBL_DEFAULT_TAX_MODE' => 'Numatytoji mokesčių forma',
	'LBL_RELATIONSHIPS' => 'Santykiai',
    
    'LBL_MODULE_BUILDER_DESCRIPTION' => 'Kuriami nauji moduliai',
    
	'LBL_EXTENSION_STORE' => 'Priedų krautuvė',
    'LBL_GATEWAY_CONFIGURATION' => 'Mokėjimo šliuzo konfigūracija',
    'MAIN_PRODUCT_WHITELABEL' => '„CRM“ balta etiketė',
    'LBL_WHITE_LABELING_INFO' => 'Įjungus šią funkciją  „CRM“ pašalins atsiliepimų piktogramą, vaizdo įrašų nuorodas, naujus vaizdo įrašus ir poraštę.',
    'LBL_WHITE_LABELING_INFO_MSG' => 'Įjungus šią funkciją, iš „CRM“ pašalinamas pagalbos mygtukas ir poraštė.',
	/*Vtiger7 Language Strings*/
    'LBL_USER_MANAGEMENT' => 'Naudotojai ir prieiga',
    'LBL_MODULE_MANAGEMENT' => 'Modulių tvarkyklė',
    'LBL_AUTOMATION' => 'Automatika',
    'LBL_CONFIGURATION' => 'Konfigūracija',
    'LBL_MARKETING_SALES' => 'Rinkodara ir pardavimai',
    'LBL_INVOICES' => 'Sąskaitos faktūros',
    'LBL_SUPPORT' => 'Pagalba',
    'LBL_TEMPLATES' => 'Šablonai',
    'LBL_MODULE_CUSTOMIZATION' => 'Modulių išdėstymas ir laukai',
    'LBL_TAX_MANAGEMENT' => 'Mokesčių valdymas',
    'LBL_TERMS_AND_CONDITIONS' => 'Terminai ir sąlygos',
    'LBL_GATEWAY_CONFIGURATION' => 'Mokėjimo šliuzo konfigūracija',
    'LBL_LEAD_MAPPING' => 'Užklausų konversijų duomenų žymėjimas',
    'LBL_OPPORTUNITY_MAPPING' => 'Galimybės į projektą susiejimas',
    'LBL_PICKLIST_DEPENDENCY' => 'Parinkčių sąrašų priklausomybė',
    'LBL_MY_TAGS' => 'Mano žymos',
	'LBL_ADD_MODULE' => 'Pridėti modulį',
    'LBL_SMART_NOTIFICATIONS' => 'Protingi pranešimai',
    'LBL_FORECAST_SETTINGS' => 'Prognozės nustatymai',
    'LBL_SEARCH_FOR_SETTINGS' => 'Paieškos nustatymai ',
    'LBL_GOOGLE' => 'Google',
    'LBL_QUICKBOOKS' => 'QuickBooks',
    'LBL_XERO' => 'Xero',
    'LBL_TALLY' => 'Tally',
    'LBL_SHOPPINGCART' => 'ShoppingCart',
	'LBL_PHONE_CONFIGURATION' => 'Telefono konfigūracija',
);

$jsLanguageStrings = array(
	'JS_PLEASE_SELECT_ATLEAST_ONE_MEMBER_FOR_A_GROUP' => 'Pasirinkite bent vieną narį grupei',
	'JS_GROUP_DELETED_SUCCESSFULLY' => 'Grupė pašalinta sėkmingai',
	'JS_TAX_SAVED_SUCCESSFULLY' => 'Mokestis įrašytas sėkmingai',
	'JS_TAX_DISABLED' => 'Mokestis išjungtas',
	'JS_TAX_ENABLED' => 'Mokestis įgalintas',
	'JS_SELECT_SIMPLE_TAXES' => 'Pasirinkti paprastus mokesčius',
	'JS_TAX_REGION_SAVED_SUCCESSFULLY' => 'Mokesčių regionas išsaugotas sėkmingai',
	'JS_TAX_REGION_DELETED_SUCCESSFULLY' => 'Mokesčių regionas pašalintas sėkmingai',
	'JS_INVENTORY_CHARGE_SAVED_SUCCESSFULLY' => 'Inventoriaus rinkliava išsaugota sėkmingai',
	'JS_INVENTORY_CHARGE_DELETED_SUCCESSFULLY' => 'Inventoriaus rinkliava pašalinta sėkmingai',
	'JS_DELETE_CHARGE_DESC' => 'Pašalinus šią rinkliavą, tai paveiks visus inventoriaus įrašus su šia rinkliava. Ar norite tęsti?',
	'JS_DELETE_REGION_DESC' => 'Pašalinus šį regioną, tai paveiks visus inventoriaus mokesčių įrašus naudojančius šį regioną. Ar norite tęsti?',
	'JS_SELECT_REGIONS' => 'Pasirinkite regionus',
	'JS_DELETE' => 'Pašalinti',
	'JS_EDIT' => 'Redaguoti  ',
	'JS_ANNOUNCEMENT_SAVED' => 'Pranešimas įrašytas',
	'JS_CONFIRM_DEFAULT_SETTINGS' => 'Ar tikrai norite pakeisti esamas serverio nuostatas į numatytąsias',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_1TO5' => 'Įrašykite skaičių nuo 1-%sMB',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_1TO100' => 'Įrašykite skaičių nuo 1 iki 100',
	'JS_RECORD_NUMBERING_SAVED_SUCCESSFULLY_FOR' => 'Įrašų numeravimo nuostatos sėkmingai įrašytos:',
	'JS_RECORD_NUMBERING_UPDATED_SUCCESSFULLY_FOR' => 'Įrašų numeravimo nuostatos sėkmingai atnaujintos:',
	'JS_SEQUENCE_NUMBER_MESSAGE' => 'Pradinis numeris turi būti didesnis arba lygus',
	'LBL_WRONG_IMAGE_TYPE' => 'Nepalaikomas paveikslo tipas',
	'LBL_MAXIMUM_SIZE_EXCEEDS' => 'Didžiausias leistinas įkeliamo failo dydis yra 1 MB',
	'LBL_NO_LOGO_SELECTED' => 'Logotipas nepasirinktas',
	'JS_CONFIGURATION_DETAILS_SAVED' => 'Konfigūracija įrašyta',
	'JS_TERMS_AND_CONDITIONS_SAVED' => 'Terminai ir sąlygos įrašyti',
	'JS_DEFAULT_TAX_MODE_SET_AS' => 'Numatytoji mokesčių forma pasirinkta kaip',
    'JS_INVALID_URL' => 'Neteisingas adresas',
    'JS_LBL_TAX_REGION_EXIST' => 'Regionas tokiu pavadinimu jau egzistuoja',
    'JS_LOGO_IMAGE_DIMENSIONS_WRONG' => 'Logotipo išmatavimai neatitiko leidžiamų išmatavimų. Pakeiskite paveiksliuko išmatavimus ir bandykite dar kartą.',
);
