<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	//Basic Field Names
	'LBL_NEW' => 'Naujas',
	'LBL_WORKFLOW' => 'Darbo procesas',
	'LBL_CREATING_WORKFLOW' => 'Darbo proceso kūrimas',
	'LBL_EDITING_WORKFLOW' => 'Darbo proceso redagavimas',
	'LBL_ADD_RECORD' => 'Naujas darbo procesas',

	//Edit view
	'LBL_STEP_1' => '1 žingsnis',
	'LBL_ENTER_BASIC_DETAILS_OF_THE_WORKFLOW' => 'Įveskite pagrindinę darbo proceso informaciją',
	'LBL_SPECIFY_WHEN_TO_EXECUTE' => 'Nurodykite, kada vykdyti šį procesą',
	'ON_FIRST_SAVE' => 'tik pirmą kartą įrašant',
	'ONCE' => 'iki pirmą kartą bus patenkinta sąlyga',
	'ON_EVERY_SAVE' => 'kiekvieną kartą įrašant',
	'ON_MODIFY' => 'kaskart atnaujinant įrašą',
	'ON_SCHEDULE' => 'pagal tvarkaraštį',
	'MANUAL' => 'Sistema',
	'SCHEDULE_WORKFLOW' => 'Suplanuoti darbo procesą',
	'ADD_CONDITIONS' => 'Pridėti sąlygas',
	'ADD_TASKS' => 'Pridėti veiksmus',

	//Step2 edit view
	'LBL_EXPRESSION' => 'Išraiška',
	'LBL_FIELD_NAME' => 'Laukas',
	'LBL_SET_VALUE' => 'Nustatyti reikšmę',
	'LBL_USE_FIELD' => 'Naudoti lauką',
	'LBL_USE_FUNCTION' => 'Naudoti funkciją',
	'LBL_RAW_TEXT' => 'Grynasis tekstas',
	'LBL_ENABLE_TO_CREATE_FILTERS' => 'Įgalinkite, jei norite kurti filtrus',
	'LBL_CREATED_IN_OLD_LOOK_CANNOT_BE_EDITED' => 'Šis darbo procesas sukurtas naudojantis ankstesne sąsaja. Taip sukurtų sąlygų negalima redaguoti. Galite sąlygas sukurti iš naujo arba palikti esamas, jų nekeisdami.',
	'LBL_USE_EXISTING_CONDITIONS' => 'Palikti esamas sąlygas',
	'LBL_RECREATE_CONDITIONS' => 'Kurti sąlygas iš naujo',
	'LBL_SAVE_AND_CONTINUE' => 'Įrašyti ir tęsti',

	//Step3 edit view
	'LBL_ACTIVE' => 'Aktyvi',
	'LBL_TASK_TYPE' => 'Veiksmo tipas',
	'LBL_TASK_TITLE' => 'Veiksmo pavadinimas',
	'LBL_ADD_TASKS_FOR_WORKFLOW' => 'Pridėti veiksmą darbo procesui',
	'LBL_EXECUTE_TASK' => 'Vykdyti veiksmą',
	'LBL_SELECT_OPTIONS' => 'Pažymėti parinktis',
	'LBL_ADD_FIELD' => 'Pridėti lauką',
	'LBL_ADD_TIME' => 'Pridėti laiką',
	'LBL_TITLE' => 'Pavadinimas',
	'LBL_PRIORITY' => 'Prioritetas',
	'LBL_ASSIGNED_TO' => 'Priskirta',
	'LBL_TIME' => 'Laikas',
	'LBL_DUE_DATE' => 'Įvykdymo terminas',
	'LBL_THE_SAME_VALUE_IS_USED_FOR_START_DATE' => 'Reikšmė sutampa su pradžios data',
	'LBL_EVENT_NAME' => 'Įvykio pavadinimas',
	'LBL_TYPE' => 'Tipas',
	'LBL_METHOD_NAME' => 'Metodo pavadinimas',
	'LBL_RECEPIENTS' => 'Gavėjai',
	'LBL_ADD_FIELDS' => 'Pridėti laukus',
	'LBL_SMS_TEXT' => 'SMS žinutės tekstas',
	'LBL_SET_FIELD_VALUES' => 'Nustatyti laukų reikšmes',
	'LBL_ADD_FIELD' => 'Pridėti lauką',
	'LBL_IN_ACTIVE' => 'Neaktyvus',
	'LBL_SEND_NOTIFICATION' => 'Siųsti pranešimą',
	'LBL_START_TIME' => 'Pradžios laikas',
	'LBL_START_DATE' => 'Pradžios data',
	'LBL_END_TIME' => 'Pabaigos laikas',
	'LBL_END_DATE' => 'Pabaigos data',
	'LBL_ENABLE_REPEAT' => 'Įgalinti kartojimą',
	'LBL_NO_METHOD_IS_AVAILABLE_FOR_THIS_MODULE' => 'Šis modulis neturi galimų metodų.',
	
	'LBL_NO_TASKS_ADDED' => 'Jokių veiksmų',
	'LBL_CANNOT_DELETE_DEFAULT_WORKFLOW' => 'Numatytojo darbo proceso pašalinti negalima',
	'LBL_MODULES_TO_CREATE_RECORD' => 'Sukurti naują įrašą',
	'LBL_EXAMPLE_EXPRESSION' => 'Išraiška',
	'LBL_EXAMPLE_RAWTEXT' => 'Grynasis tekstas',
	'LBL_VTIGER' => 'Vtiger',
	'LBL_EXAMPLE_FIELD_NAME' => 'Laukas',
	'LBL_NOTIFY_OWNER' => 'notify_owner',
	'LBL_ANNUAL_REVENUE' => 'annual_revenue',
	'LBL_EXPRESSION_EXAMPLE2' => "if mailingcountry == 'India' then concat(firstname,' ',lastname) else concat(lastname,' ',firstname) end",
	'LBL_FROM' => 'Nuo',
	'LBL_RUN_WORKFLOW' => 'procesą vykdyti',
	'LBL_AT_TIME' => 'šiuo laiku',
	'LBL_HOURLY' => 'kas valandą',
	'Optional' => 'Neprivaloma',
	'ENTER_FROM_EMAIL_ADDRESS'=> 'Įveskite nuo ko el. pašto adresas',
	'LBL_ADD_TASK' => 'Pridėti veiksmą',
    'Portal Pdf Url' =>'Portalo PDF URL',

	'LBL_DAILY' => 'kasdien',
	'LBL_WEEKLY' => 'savaitės dienomis',
	'LBL_ON_THESE_DAYS' => 'šiomis dienomis',
	'LBL_MONTHLY_BY_DATE' => 'mėnesio dienomis',
	'LBL_MONTHLY_BY_WEEKDAY' => 'kas mėnesį savaitės dienomis',
	'LBL_YEARLY' => 'nurodytomis metų dienomis',
	'LBL_SPECIFIC_DATE' => 'vieną kartą',
	'LBL_CHOOSE_DATE' => 'pasirinkite datą',
	'LBL_SELECT_MONTH_AND_DAY' => 'pasirinkite mėnesį ir dieną',
	'LBL_SELECTED_DATES' => 'Pasirinktos dienos',
	'LBL_EXCEEDING_MAXIMUM_LIMIT' => 'Viršytas didžiausias leistinas skaičius',
	'LBL_NEXT_TRIGGER_TIME' => 'artimiausias vykdymas',
    'LBL_ADD_TEMPLATE' => 'Pridėti šabloną',
    'LBL_LINEITEM_BLOCK_GROUP' => 'Elementų blokas grupiniams mokesčiams',
    'LBL_LINEITEM_BLOCK_INDIVIDUAL' => 'Elementų blokas individualiems mokesčiams',
	'LBL_MESSAGE' => 'Pranešimas',
    'LBL_ADD_PDF' => 'Pridėti PDF',
	
	//Translation for module
	'Calendar' => 'Užduotis',
	'Send Mail' => 'Siūsti laišką',
	'Invoke Custom Function' => 'Inicijuoti pasirinktinę funkciją',
	'Create Todo' => 'Sukurti užduotį',
	'Create Event' => 'Sukurti įvykį',
	'Update Fields' => 'Atnaujinti laukus',
	'Create Entity' => 'Sukurti įrašą',
	'SMS Task' => 'SMS užduotis',
	'Mobile Push Notification' => 'Mobilus įspėjimo pranešimas',
    
    // v7 translations
    'LBL_WORKFLOW_NAME' => 'Darbo proceso pavadinimas',
    'LBL_TARGET_MODULE' => 'Tikslinis modulis',
    'LBL_WORKFLOW_TRIGGER' => 'Darbo proceso iniciatorius',
    'LBL_TRIGGER_WORKFLOW_ON' => 'Inicijuoti procesą kai',
    'LBL_RECORD_CREATION' => 'Sukuriamas įrašas',
    'LBL_RECORD_UPDATE' => 'Atnaujinamas įrašas',
    'LBL_TIME_INTERVAL' => 'Laiko intervalas',
    'LBL_RECURRENCE' => 'Pasikartojimas',
    'LBL_FIRST_TIME_CONDITION_MET' => 'Kai pirmą kartą sąlyga bus patenkinta',
    'LBL_EVERY_TIME_CONDITION_MET' => 'Kiek vieną kartą kai sąlyga yra patenkinta',
    'LBL_WORKFLOW_CONDITION' => 'Darbo proceso sąlyga',
    'LBL_WORKFLOW_ACTIONS' => 'Darbo proceso veiksmas',
    'LBL_DELAY_ACTION' => 'Kasdienis veiksmas',
    'LBL_FREQUENCY' => 'Periodiškumas',
    'LBL_SELECT_FIELDS' => 'Pasirinkite laukus',
    'LBL_INCLUDES_CREATION' => 'Itraukiant sukūrimą',
    'LBL_ACTION_FOR_WORKFLOW' => 'Veiksmas darbo procesui',
    'LBL_WORKFLOW_SEARCH' => 'Ieškoti pagal pavadinimą',
	'LBL_ACTION_TYPE' => 'Veiksmo tipas (įskaitant aktyvius)',
	'LBL_VTEmailTask' => 'El. paštas',
    'LBL_VTEntityMethodTask' => 'Pasirinktinė funkcija',
    'LBL_VTCreateTodoTask' => 'Užduotis',
    'LBL_VTCreateEventTask' => 'Įvykis',
    'LBL_VTUpdateFieldsTask' => 'Lauko atnaujinimas',
    'LBL_VTSMSTask' => 'SMS', 
    'LBL_VTPushNotificationTask' => 'Mobilus pranešimas',
    'LBL_VTCreateEntityTask' => 'Sukurti įrašą',
	'LBL_MAX_SCHEDULED_WORKFLOWS_EXCEEDED' => 'Maximum number(%s) of scheduled workflows has been exceeded',
    
    'is' => 'is %s',
    'contains' => 'contains %s',
    'does not contain' => 'does not contain %s',
    'starts with' => 'starts with %s',
    'ends with' => 'ends with %s',
    'has changed' => 'has changed',
    'is empty' => 'is empty',
    'is not empty' => 'is not empty',
    'equal to' => 'equal to %s',
    'less than' => 'less than %s',
    'greater than' => 'greater than %s',
    'does not equal' => 'does not equal %s',
    'less than or equal to' => 'less than or equal to %s',
    'greater than or equal to' => 'greater than or equal to %s',
    'is not' => 'is not %s',
    'has changed to' => 'has changed to %s',
    'has changed from' => 'has changed from %s',
    'before' => 'before %s',
    'after' => 'after %s',
    'is today' => 'is today',
    'is tomorrow' => 'is tomorrow',
    'is yesterday' => 'is yesterday',
	'previous month' => 'previous month',
	'current month' => 'current month',
	'next month' => 'next month',
    'less than days ago' => 'less than %s days ago',
    'less than days later' => 'less than %s days later',
    'more than days ago' => 'more than %s days ago',
    'more than days later' => 'more than %s days later',
    'days ago' => '%s days ago',
    'days later' => '%s days later',
    'between' => 'between %s',
    'in less than' => 'in less than %s',
    'in more than' => 'in more than %s',
    'is added' => 'is added',
	'week days later' => '%s week days later',
    'more than week days later' => 'more than %s week days later',
    'less than week days later' => 'less than %s week days later',
    'week days ago' => '%s week days ago',
    'more than week days ago' => 'more than %s week days ago',
    'less than week days ago' => 'less than %s week days ago',
);

$jsLanguageStrings = array(
	'JS_STATUS_CHANGED_SUCCESSFULLY' => 'Būsena pakeista sėkmingai',
	'JS_TASK_DELETED_SUCCESSFULLY' => 'Veiksmas pašalintas sėkmingai',
	'JS_SAME_FIELDS_SELECTED_MORE_THAN_ONCE' => 'Tie patys laukai pasirinkti kelis kartus',
	'JS_WORKFLOW_SAVED_SUCCESSFULLY' => 'Darbo procesas įrašytas sėkmingai',
    'JS_CHECK_START_AND_END_DATE'=>'Pabaigos data ir laikas turi būti vėlesni arba lygūs pradžios datai ir laikui',
    'JS_TASK_STATUS_CHANGED' => 'Užduoties būsena pakeista sėkmingai.',
    'JS_WORKFLOWS_STATUS_CHANGED' => 'Darbo proceso būsena pakeista sėkmingai.',
    'VTEmailTask' => 'Siūsti laišką',
    'VTEntityMethodTask' => 'Inicijuoti pasirinktinę funkciją',
    'VTCreateTodoTask' => 'Sukurti užduotį',
    'VTCreateEventTask' => 'Sukurti įvykį',
    'VTUpdateFieldsTask' => 'Atnaujinti laukus',
    'VTSMSTask' => 'SMS užduotis', 
    'VTPushNotificationTask' => 'Mobilus įspėjimo pranešimas',
    'VTCreateEntityTask' => 'Sukurti įrašą',
    'LBL_EXPRESSION_INVALID' => 'Neteisinga išraiška'
);

