<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'ADD_CONDITIONS' => 'Pridėti sąlygas',
	'ADD_TASKS' => 'Pridėti užduotis',
	'Calendar' => 'Darbai',
	'LBL_ACTIVE' => 'Aktyvi',
	'LBL_ADD_FIELD' => 'Pridėti lauką', //Duplicated key-value pair
	'LBL_ADD_FIELDS' => 'Pridėti laukus',
	'LBL_ADD_TASKS_FOR_WORKFLOW' => 'Pridėti užduotis į darbo procesą',
	'LBL_ADD_TIME' => 'Pridėti laiką',
	'LBL_ANNUAL_REVENUE' => 'annual_revenue',
	'LBL_ASSIGNED_TO' => 'Priskirta',
	'LBL_CANNOT_DELETE_DEFAULT_WORKFLOW' => 'Numatytojo darbo proceso pašalinti negalima',
	'LBL_CREATED_IN_OLD_LOOK_CANNOT_BE_EDITED' => 'Šis darbo procesas sukurtas naudojantis ankstesne sąsaja. Taip sukurtų sąlygų negalima redaguoti. Galite sąlygas sukurti iš naujo arba palikti esamas, jų nekeisdami.',
	'LBL_CREATING_WORKFLOW' => 'Darbo proceso kūrimas',
	'LBL_DUE_DATE' => 'Įvykdymo terminas',
	'LBL_EDITING_WORKFLOW' => 'Darbo proceso redagavimas',
	'LBL_ENABLE_REPEAT' => 'Įgalinti kartojimą',
	'LBL_ENABLE_TO_CREATE_FILTERS' => 'Įgalinkite, jei norite kurti filtrus',
	'LBL_END_DATE' => 'Pabaigos data',
	'LBL_END_TIME' => 'Pabaigos laikas',
	'LBL_ENTER_BASIC_DETAILS_OF_THE_WORKFLOW' => 'Įveskite pagrindinę darbo proceso informaciją',
	'LBL_EVENT_NAME' => 'Įvykio pavadinimas',
	'LBL_EXAMPLE_EXPRESSION' => 'Išraiška',
	'LBL_EXAMPLE_FIELD_NAME' => 'Laukas',
	'LBL_EXAMPLE_RAWTEXT' => 'Grynasis tekstas',
	'LBL_EXECUTE_TASK' => 'Vykdyti užduotį',
	'LBL_EXPRESSION_EXAMPLE2' => "if mailingcountry == 'India' then concat(firstname,' ',lastname) else concat(lastname,' ',firstname) end",
	'LBL_EXPRESSION' => 'Išraiška',
	'LBL_FIELD_NAME' => 'Laukas',
	'LBL_FINISH' => 'Užbaigti',
	'LBL_IN_ACTIVE' => 'neaktyvi',
	'LBL_METHOD_NAME' => 'Metodo pavadinimas',
	'LBL_MODULES_TO_CREATE_RECORD' => 'Moduliai kurti įrašui',
	'LBL_NEW' => 'Naujas',
	'LBL_NEXT' => 'Toliau',
	'LBL_NO_METHOD_IS_AVAILABLE_FOR_THIS_MODULE' => 'Šis modulis neturi galimų metodų.',
	'LBL_NO_TASKS_ADDED' => 'Užduočių nėra',
	'LBL_NOTIFY_OWNER' => 'notify_owner',
	'LBL_PRIORITY' => 'Prioritetas',
	'LBL_RAW_TEXT' => 'Grynasis tekstas',
	'LBL_RECEPIENTS' => 'Gavėjai',
	'LBL_RECREATE_CONDITIONS' => 'Kurti sąlygas iš naujo',
	'LBL_SAVE_AND_CONTINUE' => 'Įrašyti ir tęsti',
	'LBL_SELECT_OPTIONS' => 'Pažymėti parinktis',
	'LBL_SEND_NOTIFICATION' => 'Siųsti pranešimą',
	'LBL_SET_FIELD_VALUES' => 'Nustatyti laukų reikšmes',
	'LBL_SET_VALUE' => 'Nustatyti reikšmę',
	'LBL_SMS_TEXT' => 'SMS žinutės tekstas',
	'LBL_SPECIFY_WHEN_TO_EXECUTE' => 'Nurodykite, kada vykdyti šį procesą',
	'LBL_START_DATE' => 'Pradžios data',
	'LBL_START_TIME' => 'Pradžios laikas',
	'LBL_STEP_1' => '1 žingsnis',
	'LBL_TASK_TITLE' => 'Užduoties pavadinimas',
	'LBL_TASK_TYPE' => 'Užduoties tipas', //Duplicated key-value pair
	'LBL_THE_SAME_VALUE_IS_USED_FOR_START_DATE' => 'Reikšmė sutampa su pradžios data',
	'LBL_TIME' => 'Laikas',
	'LBL_TITLE' => 'Pavadinimas',
	'LBL_TYPE' => 'Tipas',
	'LBL_USE_EXISTING_CONDITIONS' => 'Palikti esamas sąlygas',
	'LBL_USE_FIELD' => 'Naudoti lauką',
	'LBL_USE_FUNCTION' => 'Naudoti funkciją',
	'LBL_VTIGER' => 'Vtiger',
	'LBL_WORKFLOW' => 'Darbo procesas',
	'MANUAL' => 'Sistema',
	'ONCE' => 'iki pirmą kartą bus patenkinta sąlyga',
	'ON_EVERY_SAVE' => 'kiekvieną kartą įrašant',
	'ON_FIRST_SAVE' => 'tik pirmą kartą įrašant',
	'ON_MODIFY' => 'kaskart atnaujinant įrašą',
	'SCHEDULE_WORKFLOW' => 'Suplanuoti darbo procesą',
        'ON_SCHEDULE'=>'pagal tvarkaraštį',
        'LBL_RUN_WORKFLOW' => 'procesą vykdyti',
	'LBL_AT_TIME' => 'šiuo laiku',
	'LBL_HOURLY' => 'kas valandą',
	'LBL_DAILY' => 'kasdien',
	'LBL_WEEKLY' => 'savaitės dienomis',
	'LBL_ON_THESE_DAYS' => 'šiomis dienomis',
	'LBL_MONTHLY_BY_DATE' => 'mėnesio dienomis',
	'LBL_MONTHLY_BY_WEEKDAY' => 'kas mėnesį savaitės dienomis',
	'LBL_YEARLY' => 'nurodytomis metų dienomis',
	'LBL_SPECIFIC_DATE' => 'vieną kartą',
	'LBL_CHOOSE_DATE' => 'pasirinkite datą',
	'LBL_SELECT_MONTH_AND_DAY' => 'pasirinkite mėnesį ir dieną',
	'LBL_SELECTED_DATES' => 'Pasirinktos dienos',
	'LBL_EXCEEDING_MAXIMUM_LIMIT' => 'Viršytas didžiausias leistinas skaičius',
	'LBL_NEXT_TRIGGER_TIME' => 'artimiausias vykdymas',
	'LBL_MESSAGE' => 'Pranešimas',
    
         //Patch provided by http://trac.vtiger.com/cgi-bin/trac.cgi/ticket/7884
        'Workflows' => 'Darbo procesas', 
        //Field names 
        'Summary' => 'Santrauka', 
        'Module' => 'Modulis', 
        'Execution Condition' => 'Vykdymo sąlyga',
);

$jsLanguageStrings = array(
	'JS_SAME_FIELDS_SELECTED_MORE_THAN_ONCE' => 'Tie patys laukai pasirinkti kelis kartus',
	'JS_STATUS_CHANGED_SUCCESSFULLY' => 'Būsena pakeista sėkmingai',
	'JS_TASK_DELETED_SUCCESSFULLY' => 'Užduotis pašalinta sėkmingai ',
	'JS_WORKFLOW_SAVED_SUCCESSFULLY' => 'Darbo procesas įrašytas sėkmingai',
);
