<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * *********************************************************************************** */
$languageStrings = array(
	'Activity Type' => 'Veiklos tipas',
	'Call' => 'Skambutis',
	'Completed' => 'Užbaigta',
	'Daily' => 'Kasdien',
	'Deferred' => 'Atidėta',
	'End Date & Time' => 'Pabaigos data ir laikas',
	'first' => 'pirmas',
	'ICAL_FORMAT' => '„iCal“ formatas',
	'last' => 'paskutinis',
	'LBL_ACTIVITY_TYPES' => 'Veiklos tipai',
	'LBL_ADD_CALENDAR_VIEW' => 'Pridėti kalendoriaus rodinį',
	'LBL_ADDED_CALENDARS' => 'Pridėti kalendoriai',
	'LBL_ADD_EVENT' => 'Pridėti įvykį',
	'LBL_ADD_TASK' => 'Pridėti darbą',
	'LBL_CALENDAR_SETTINGS' => 'Kalendoriaus nuostatos',
	'LBL_CALENDAR_SHARING' => 'Kalendoriaus bendrinimas',
	'LBL_CALENDAR_VIEW' => 'Mano kalendorius',
	'LBL_CALL' => 'Skambutis',
	'LBL_CHANGE_OWNER' => 'Pakeisti savininką',
	'LBL_CONTACTS_BIRTH_DAY' => 'Gimimo data',
	'LBL_CONTACTS_SUPPORT_END_DATE' => 'Palaikymo pabaigos data',
	'LBL_DAY0' => 'sekmadienis',
	'LBL_DAY1' => 'pirmadienis',
	'LBL_DAY2' => 'antradienis',
	'LBL_DAY3' => 'trečiadienis',
	'LBL_DAY4' => 'ketvirtadienis',
	'LBL_DAY5' => 'penktadienis',
	'LBL_DAY6' => 'šeštadienis',
	'LBL_DAY_OF_THE_MONTH' => 'mėnesio diena',
	'LBL_DEFAULT_EVENT_DURATION' => 'Numatytoji įvykio trukmė',
	'LBL_DEFAULT_STATUS_TYPE' => 'Numatytoji būsena ir tipas',
	'LBL_DELETE_CALENDAR' => 'Šalinti kalendorių',
	'LBL_EDIT_COLOR' => 'Keisti spalvą',
	'LBL_EDITING_CALENDAR_VIEW' => 'Kalendorius',
	'LBL_EVENT' => 'Įvykis',
	'LBL_EVENT_INFORMATION' => 'Įvykio informacija',
	'LBL_EVENT_OR_TASK' => 'Įvykis / darbas',
	'LBL_EVENTS' => 'Įvykiai',
	'LBL_FINISH' => 'Pabaigti',
	'LBL_IMPORT_RECORDS' => 'Importuoti įrašus',
	'LBL_LAST_IMPORT_UNDONE' => 'Jūsų paskutinė importo operacija buvo atšaukta',
	'LBL_MINUTES' => 'min.',
	'LBL_ON' => ' ',
	'LBL_OTHER_EVENTS' => 'kitas įvykis',
	'LBL_RECORDS_LIST' => 'Kalendorių sąrašas', //Duplicated key-value pair
	'LBL_RESULT' => 'Rezultatas',
	'LBL_SELECT_ACTIVITY_TYPE' => 'Pasirinkite veiklos tipą',
	'LBL_SELECT_CALENDAR_COLOR' => 'Kalendoriaus spalva',
	'LBL_SELECT_USER_CALENDAR' => 'Pasirinkite naudotojo kalendorių',
	'LBL_SELECT_USERS' => 'Pažymėkite naudotojus',
	'LBL_SHARED_CALENDAR' => 'Bendras kalendorius',
	'LBL_STATUS' => 'Būsena',
	'LBL_TASK_INFORMATION' => 'Darbo informacija',
	'LBL_TASKS' => 'Darbai',
	'LBL_TASK' => 'Darbas',
	'LBL_TODOS' => 'Darbai',
	'LBL_TOTAL_EVENTS_IMPORTED' => 'Sėkmingai importuotų įvykių skaičius',
	'LBL_TOTAL_EVENTS_SKIPPED' => 'Praleistų įvykių skaičius (dėl neužpildytų reikiamų laukų)',
	'LBL_TOTAL_TASKS_IMPORTED' => 'Sėkmingai importuotų užduočių skaičius',
	'LBL_TOTAL_TASKS_SKIPPED' => 'Praleistų užduočių skaičius (dėl neužpildytų privalomų laukų)',
	'LBL_TYPE' => 'Tipas',
	'LBL_UNDO_LAST_IMPORT' => 'Atšaukti paskutinę importo operaciją',
	'Location' => 'Vieta',
	'Medium' => 'Vidutinis',
	'Meeting' => 'Susirinkimas',
	'Monthly' => 'mėn.',
	'Not Started' => 'Nepradėta',
	'Pending Input' => 'Laukiamas įvedimas',
	'Planned' => 'Planuojama',
	'Send Notification' => 'Siųsti pranešimą',
	'SINGLE_Calendar' => 'Darbai',
	'SINGLE_Events' => 'Įvykis',
	'Start Date & Time' => 'Pradžios data ir laikas',
	'Subject' => 'Tema ',
	'Tasks' => 'Darbai',
	'Task' => 'Darbas',
	'Weekly' => 'Kiekvieną savaitę',
	'Yearly' => 'Metai',
    
         //Patch provided by http://trac.vtiger.com/cgi-bin/trac.cgi/ticket/7884
        'Start Date &amp; Time' => 'Pradžios data ir laikas', 
        'End Date &amp; Time' => 'Pabaigos data ir laikas', 
        'End Date' => 'Pabaigos data', 
    
        //Event Status picklist values 
        'Held' => 'Įvykęs', 
        'Not Held' => 'Neįvykęs', 
);

$jsLanguageStrings = array(
	'JS_CALENDAR_VIEW_ADDED_SUCCESSFULLY' => 'Kalendoriaus rodinys sėkmingai pridėtas',
	'JS_CALENDAR_VIEW_COLOR_UPDATED_SUCCESSFULLY' => 'Kalendoriaus rodinio spalva sėkmingai pakeista', 
	'JS_CALENDAR_VIEW_DELETE_CONFIRMATION' => 'Ar tikrai norite pašalinti šį kalendoriaus rodinį?', 
	'JS_CALENDAR_VIEW_DELETED_SUCCESSFULLY' => 'Kalendoriaus rodinys sėkmingai pašalintas',
	'JS_EDIT_CALENDAR' => 'Redaguoti kalendorių',
        'JS_FUTURE_EVENT_CANNOT_BE_HELD' => 'Negali būti išlaikytas ateityje', 
	'JS_NO_CALENDAR_VIEWS_TO_ADD' => 'Nėra kalendoriaus rodinių, kuriuos būtų galima pridėti',
        'JS_NO_DELETE_PERMISSION' => 'Jūs neturite teisių šalinti kalendoriaus įrašus.', 
        'JS_NO_EDIT_PERMISSION' => 'Jūs neturite teisių keisti kalendoriaus įrašus.', 
        'JS_TASK_IS_SUCCESSFULLY_ADDED_TO_YOUR_CALENDAR' => 'Darbas sėkmingai pridėtas kalendoriuje', 
        'JS_RECORD_DELETED' => 'Kalendoriaus įrašas sėkmingai pašalintas', 
	'LBL_ADD_EVENT_TASK' => 'Pridėti įvykį/darbą',
	'LBL_ALL_DAY' => 'Visa diena',
	'LBL_APR' => 'Bal',
	'LBL_APRIL' => 'Balandis',
	'LBL_AUG' => 'Rugp',
	'LBL_AUGUST' => 'Rugpjūtis',
	'LBL_CANT_SELECT_CONTACT_FROM_LEADS' => 'Negalima pasirinkti adresatų iš užklausų',
	'LBL_DAY' => 'Diena  ',
	'LBL_DEC' => 'Gruo',
	'LBL_DECEMBER' => 'Gruodis',
	'LBL_FEB' => 'Vas',
	'LBL_FEBRUARY' => 'Vasaris',
	'LBL_FRIDAY' => 'Penktadienis',
	'LBL_FRI' => 'Penkt',
	'LBL_JAN' => 'Sau',
	'LBL_JANUARY' => 'Sausis',
	'LBL_JUL' => 'Lie',
	'LBL_JULY' => 'Liepa',
	'LBL_JUNE' => 'Birželis',
	'LBL_JUN' => 'Bir',
	'LBL_MARCH' => 'Kovas',
	'LBL_MAR' => 'Kov',
	'LBL_MAY' => 'Geg',
	'LBL_MAY' => 'Geg',
	'LBL_MONDAY' => 'Pirmadienis',
	'LBL_MON' => 'Pirm',
	'LBL_MONTH' => 'Mėnuo',
	'LBL_NOVEMBER' => 'Lapkritis',
	'LBL_NOV' => 'Lap',
	'LBL_OCTOBER' => 'Spalis',
	'LBL_OCT' => 'Spa',
	'LBL_SAT' => 'Šešt',
	'LBL_SATURDAY' => 'Šeštadienis',
	'LBL_SEP' => 'Rugs',
	'LBL_SEPTEMBER' => 'Rugsėjis',
	'LBL_SUNDAY' => 'Sekmadienis',
	'LBL_SUN' => 'Sekm',
	'LBL_THURSDAY' => 'Ketvirtadienis',
	'LBL_THU' => 'Ketv',
	'LBL_TODAY' => 'Šiandien',
	'LBL_TUESDAY' => 'Antradienis',
	'LBL_TUE' => 'Antr',
	'LBL_WEDNESDAY' => 'Trečiadienis',
	'LBL_WED' => 'Treč',
	'LBL_WEEK' => 'Savaitė ',
	'Mobile Call' => 'Mob. skambutis',
);
