<?php

/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
    $languageStrings = array(
        'Map' => 'Susieti',
        'EXTENTIONNAME' => '„Google“',
        'LBL_UPDATES_CRM' => 'Atnaujinimai CRM serveryje',
        'LBL_UPDATES_GOOGLE' => 'Atnaujinimai „Google“ serveryje',
        'LBL_UPDATED' => 'atnaujintas',
        'LBL_ADDED' => 'Pridėta',
        'LBL_DELETED' => 'Pašalinta',
        'LBL_SYNCRONIZED' => 'Sinchronizuota',
        'LBL_NOT_SYNCRONIZED' => 'Dar nesate sinchronizavę',
        'LBL_SYNC_BUTTON' => 'Sinchronizuoti dabar',
        'LBL_REMOVE_SYNC' => 'Panaikinti sinchronizaciją',
        'LBL_MORE_VTIGER' => 'CRM sistemoje yra daugiau nesinchronizuotų įrašų',
        'LBL_MORE_GOOGLE' => '„Google“ yra daugiau nesinchronizuotų įrašų',
        'Contact Name'=>'Adresato vardas',
        'Email'=>'El. paštas',
        'Mobile Phone'=>'Mobilusis telefonas',
        'Address' => 'Adresas',
        'Event Title'=>'Įvykio pavadinimas',
        'Start Date'=>'Pradžios data',
        'Until Date'=>'Pabaigos data',
        'Description'=>'Aprašymas',
        'Office Phone' => 'Biuro telefonas',
        'Work Phone' => 'Darbo telefonas',
        'Home Phone' => 'Namų telefonas',
        'SYNC_SETTINGS' => 'Adresatų sinchronizavimo nuostatos',
        'LBL_SELECT_GOOGLE_GROUP_TO_SYNC' => 'Pasirinkite „Google“ grupę',
        'LBL_ADD_CUSTOM_FIELD_MAPPING' => 'Pridėti tinkintą atitikmenį',
        'LBL_EMAIL' => 'El. paštas',
        'LBL_PHONE' => 'Telefonas',
        'LBL_URL' => 'URL',
        'LBL_CUSTOM' => 'Kitas',
        'LBL_SELECT_SYNC_DIRECTION' => 'Pasirinkite sinchronizavimo kryptį',
        'LBL_BI_DIRECTIONAL_SYNC' => 'Sinchronizuoti abiem kryptimis',
        'LBL_ONLY_SYNC_FROM_GOOGLE_TO_VTIGER' => 'Tik iš „Google“ į CRM sistemą',
        'LBL_ONLY_SYNC_FROM_VTIGER_TO_GOOGLE' => 'Tik iš CRM sistemos į „Google“',
        'Job Title' => 'Pareigos',
        'Company' => 'Įmonė',
        'Birthday' => 'Gimtadienis',
        'Phone' => 'Telefonas',
        'URL' => 'URL',
        'phone' => 'Telefonas',
        'email' => 'El. paštas',
        'url' => 'URL',
        'home' => 'Namų',
        'work' => 'Darbo',
        'custom' => 'Kitas',
        'mobile' => 'Mobilusis',
        'main' => 'Pagrindinis',
        'work_fax' => 'Faksas',
        'home_fax' => 'Namų faksas',
        'pager' => 'Pranešimų gaviklis',
        'profile' => 'Profilis',
        'blog' => 'Tinklaraštis',
        'home-page' => 'Asmeninė svetainė',
        'CALENDAR_SYNC_SETTINGS' => 'Kalendoriaus sinchronizavimo nuostatos',
        'LBL_SELECT_GOOGLE_CALENDAR_TO_SYNC' => 'Pasirinkite „Google“ kalendorių',
        'LBL_SAVE_AND_START_SYNC' => 'Įrašyti ir pradėti sinchronizaciją',
        'LBL_PRIMARY' => 'Pagrindinis',
        'LBL_SYNC_FROM_GOOGLE_TO_VTIGER' => 'Sinchronizuoti iš „Google“ į „Vtiger“',
        'LBL_SYNC_FROM_VTIGER_TO_GOOGLE' => 'Sinchronizuoti iš „Vtiger“ į „Google“',
        'LBL_GOOGLE_CONNECT_MSG' => 'Prisijunkite prie „Google“ paskyros, kad gautumėte',
        'LBL_SIGN_IN_WITH_GOOGLE' => 'Prisijunkite prie „Google“',
        'LBL_GOOGLE_ACCOUNT_DETAILS' => '„Google“ paskyros duomenys',
        'LBL_GOOGLE_ACCOUNT_SYNCED_WITH' => '„Google“ paskyra sinchronizuota su',
        'LBL_CHANGE_USER' => 'Keisti naudotoją',
        'LBL_SAVE_AND_IMPORT' => 'Įrašyti ir importuoti',
        'LBL_IMPORT_RESULTS_GOOGLE' => '„Google“ importo rezultatai',
		'LBL_REDIRECT_URL' => 'Redirect url',
		'LBL_REDIRECT_URL_MESSAGE' => 'Copy the following redirect url and paste in your google auth project as image shows',
    );
    $jsLanguageStrings = array(
        'LBL_SYNC_BUTTON' => 'Sinchronizuoti dabar',
        'LBL_SYNCRONIZING' => 'Sinchronizuojama…',
        'LBL_NOT_SYNCRONIZE' => 'Dar nesate sinchronizavę'
    );
