<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'Big Problem'=>'Didelė problema',
	'Closed'=>'Uždaryta',
	'Contact Name' => 'Adresato vardas',
	'created' => 'sukurtas',
	'Critical'=>'Kritinė',
	'customer_portal' => 'programos „Vtiger“ klientų portale.',
	'Days' => 'Dienos',
	'Dear'=> 'Gerb.',
	'Feature'=>'Funkcija',
	'From Portal' => 'Iš portalo',
	'HelpDesk ID' => 'Kortelės ID',
	'HelpDesk' => 'Užduočių kortelės',
	'High'=>'Aukštas',
	'Hi' => 'Sveiki',
	'Hours' => 'Valandos',
	'LBL_ADD_RECORD' => 'Pridėti užduoties kortelę',
	'LBL_ALTBODY' => 'Tai yra pagrindinė laiško dalis, skirta programoms, nerodančioms HTML laiškų.',
	'LBL_CHECK_MAILID' => 'Patikrinkite savo klientų portalo el. pašto ID',
	'LBL_CONVERT_FAQ' => 'Konvertuoti į DUK',
	'LBL_COULDNOT_CLOSED' => 'Kortelės nepavyko',
	'LBL_CUSTOMER_COMMENTS' => 'Klientas jums atsakė ir pateikė šią papildomą informaciją:',
	'LBL_CUSTOMER_PORTAL' => 'klientų portale – SKUBU',
	'LBL_DETAIL' => 'išsami informacija:',
	'LBL_GIVE_MAILID' => 'Nurodykite savo el. pašto ID',
	'LBL_LOGIN_DETAILS' => 'Toliau yra jūsų prisijungimo prie klientų portalo informacija:',
	'LBL_LOGIN_REVOKED' => 'Jūsų paskyra atšaukta. Susisiekite su administratoriumi.',
	'LBL_MAIL_COULDNOT_SENT' =>'Laiško išsiųsti nepavyko',
	'LBL_MAIL_SENT' => 'Jums buvo išsiųstas laiškas su prisijungimo prie klientų portalo duomenimis',
	'LBL_PASSWORD' => 'Slaptažodis:',
	'LBL_PORTAL_BODY_MAILINFO'=> 'Užduoties kortelė yra',
	'LBL_RECORDS_LIST' => 'Užduočių sąrašas',
	'LBL_REGARDS'=> 'Linkėjimai',
	'LBL_RELATED_TO' => 'Susiję su',
	'LBL_RESPOND'=> 'Prašome atsakyti į viršuje pateiktą užduoties kortelę kaip galima greičiau.',
	'LBL_RESPONDTO_TICKETID' =>'Atsakyti į užduoties kortelę ID',
	'LBL_RESPONSE_TO_TICKET_NUMBER' =>'Atsakyti į užduoties kortelę Nr.',
	'LBL_SEVERITY' => 'Reikšmingumas',
	'LBL_STATUS_CLOSED' =>'Closed',//Do not convert this label. This is used to check the status. If the status 'Closed' is changed in vtigerCRM server side then you have to change in customerportal language file also.
	'LBL_STATUS' => 'Būsena',
	'LBL_STATUS_UPDATE' => 'Kortelės būsena pakeista į ',
	'LBL_SUBJECT_PORTAL_LOGIN_DETAILS' => 'Dėl jūsų klientų portalo prisijungimo informacijos',
	'LBL_SUBJECT' => 'Tema:',
	'LBL_SUPPORT_ADMIN' => 'Palaikymo administratorius',
	'LBL_TEAM'=> 'Pagalbos tarnybos komanda',
	'LBL_TICKET_DETAILS' => 'Kortelės išsami informacija',
	'LBL_TICKET_INFORMATION' => 'Kortelės informacija',
	'LBL_TICKET_NUMBER' => 'Kortelės numeris',
	'LBL_TICKET_RESOLUTION' => 'Sprendimo informacija',
	'LBL_USERNAME' => 'Abonento vardas:',
	'link' => 'Jei norite peržiūrėti atsakymus, galite pasinaudoti šia nuoroda: ',
	'Major'=>'Reikšminga',
	'Minor'=>'Nereikšminga',
	'Normal'=>'Vidutinis',
	'Open'=>'Atvira',
	'Other Problem'=>'Kita problema',
	'Related To' => 'Organizacijos pavadinimas',
	'replied' => 'atsakė',
	'reply'=>'Yra atsakymas į',
	'Re' => 'Ats:',
	'Severity' => 'Reikšmingumas',
	'SINGLE_HelpDesk' => 'Kortelė',
	'Small Problem'=>'Nedidelė problema',
	'Solution' => 'Sprendimas',
	'Support_team' => '„Vtiger“ palaikymo komanda',
	'Thanks' => 'Ačiū',
	'The comments are' => 'Pastabos:',
	'Ticket ID'=>'Kortelės ID',
	'Ticket No' => 'Kortelės Nr.',
	'Ticket Title' => 'Kortelės pavadinimas',
	'Title' => 'Pavadinimas',
	'Update History' => 'Atnaujinimų žurnalas',
	'Urgent'=>'Skubu',
	'Wait For Response'=>'Laukti atsakymo',
);
