<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_IMPORT_STEP_1'=>'1 žingsnis',
	'LBL_IMPORT_STEP_1_DESCRIPTION'=>'Pasirinkite failą',
	'LBL_IMPORT_SUPPORTED_FILE_TYPES'=>'	Supported File Type(s): .CSV, .VCF',
	'LBL_IMPORT_STEP_2'=>'2 žingsnis',
	'LBL_IMPORT_STEP_2_DESCRIPTION'=>'Nurodykite formatą',
	'LBL_FILE_TYPE'=>'Failo tipas',
	'LBL_CHARACTER_ENCODING'=>'Simbolių kodavimas',
	'LBL_DELIMITER'=>'Skirtukas',
	'LBL_HAS_HEADER'=>'Turi antraštę',
	'LBL_IMPORT_STEP_3'=>'3 žingsnis',
	'LBL_IMPORT_STEP_3_DESCRIPTION'=>'Vienodų įrašų tvarkyklė',
	'LBL_IMPORT_STEP_3_DESCRIPTION_DETAILED'=>'Pažymėkite šią parinktį norėdami įjungti ir nustatyti vienodų įrašų suliejimo kriterijų',
	'LBL_SPECIFY_MERGE_TYPE'=>'Pasirinkite, kokius veiksmus atlikti esant dubliuotiems įrašams',
	'LBL_SELECT_MERGE_FIELDS'=>'Pasirinkite lyginamuosius laukus norėdami rasti vienodusus įrašus',
	'LBL_AVAILABLE_FIELDS'=>'Galimi laukai',
	'LBL_SELECTED_FIELDS'=>'Pažymėti laukai',
	'LBL_NEXT_BUTTON_LABEL'=>'Toliau',
	'LBL_IMPORT_STEP_4'=>'4 žingsnis',
	'LBL_IMPORT_STEP_4_DESCRIPTION' => 'Atvaizduoti modulių laukų stulpelius',
	'LBL_FILE_COLUMN_HEADER'=>'Antraštė',
	'LBL_ROW_1'=>'1 eilutė',
	'LBL_CRM_FIELDS'=>'Sistemos laukai',
	'LBL_DEFAULT_VALUE'=>'Numatytojji reikšmė',
	'LBL_SAVE_AS_CUSTOM_MAPPING'=>'Įrašyti kaip individualizuotą atvaizdavimą',
	'LBL_IMPORT_BUTTON_LABEL'=>'Importuoti',
	'LBL_RESULT'=>'Rezultatas',
	'LBL_TOTAL_RECORDS_IMPORTED'=>'Įrašai sėkmingai mportuoti',
	'LBL_NUMBER_OF_RECORDS_CREATED'=>'Įrašai sukurti',
	'LBL_NUMBER_OF_RECORDS_UPDATED'=>'Įrašai pakeisti',
	'LBL_NUMBER_OF_RECORDS_SKIPPED'=>'Įrašai praleisti',
	'LBL_NUMBER_OF_RECORDS_MERGED'=>'Įrašai sulieti', 
	'LBL_TOTAL_RECORDS_FAILED'=>'Įrašų nepavyko importuoti',
	'LBL_IMPORT_MORE'=>'Importuoti daugiau',
	'LBL_VIEW_LAST_IMPORTED_RECORDS'=>'Paskutiniai importuoti įrašai',
	'LBL_UNDO_LAST_IMPORT'=>'Atšaukti paskutinę importaciją',
	'LBL_FINISH_BUTTON_LABEL'=>'Pabaigti',
	'LBL_UNDO_RESULT'=>'Atšaukti importavimo rezultatą',
	'LBL_TOTAL_RECORDS'=>'Įrašų skaičius',
	'LBL_NUMBER_OF_RECORDS_DELETED'=>'Pašalintų įrašų skaičius',
	'LBL_OK_BUTTON_LABEL'=>'Gerai',
	'LBL_IMPORT_SCHEDULED'=>'Importuoti suplanuotus',
	'LBL_RUNNING'=>'Veikia',
	'LBL_CANCEL_IMPORT'=>'Atsisakyti importavimo',
	'LBL_ERROR'=>'Klaida',
	'LBL_CLEAR_DATA'=>'Išvalyti duomenis',
	'ERR_UNIMPORTED_RECORDS_EXIST'=>'Nepavyko importuoti daugiau duomenų į šį paketą. Atlikite naują importavimą.',
	'ERR_IMPORT_INTERRUPTED'=>'Einamasis importavimas nepavyko. Bandykite vėliau.',
	'ERR_FAILED_TO_LOCK_MODULE'=>'Nepavyko užrakinti modulio importavimui. Pabandykite vėliau.',
	'LBL_SELECT_SAVED_MAPPING'=>'Pažymėkite įrašytą atvaizdavimą',
	'LBL_IMPORT_ERROR_LARGE_FILE'=>'Importavimo klaida, per didelis failas',
	'LBL_FILE_UPLOAD_FAILED'=>'Failo nusiuntimas nepavyko',
	'LBL_IMPORT_CHANGE_UPLOAD_SIZE'=>'Import Change Upload Size',
	'LBL_IMPORT_DIRECTORY_NOT_WRITABLE'=>'Importavimo katalogas neįrašomas',
	'LBL_IMPORT_FILE_COPY_FAILED'=>'Importuojamo failo kopijavimas nepavyko',
	'LBL_INVALID_FILE'=>'Netinkamas failas',
	'LBL_NO_ROWS_FOUND'=>'Eilučių nerasta',
	'LBL_SCHEDULED_IMPORT_DETAILS'=>'Your import has been scheduled and will start within 15 minutes. You will receive an email after import is completed.  <br> <br>
										Please make sure that the Outgoing server and your email address is configured to receive email notification',
	'LBL_DETAILS'=>'Išsami informacija',
	'skipped'=>'Praleisti įrašai',
	'failed'=>'Nepavykę įrašai',
	
);
