<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_IMPORT_STEP_1' => '1 žingsnis',
	'LBL_IMPORT_STEP_1_DESCRIPTION' => 'Pasirinkite failą',
	'LBL_IMPORT_SUPPORTED_FILE_TYPES' => '	Palaikomi failų tipai: .CSV, .VCF',
	'LBL_IMPORT_STEP_2' => '2 žingsnis',
	'LBL_IMPORT_STEP_2_DESCRIPTION' => 'Nurodykite formatą',
	'LBL_FILE_TYPE' => 'Failo tipas',
	'LBL_CHARACTER_ENCODING' => 'Simbolių koduotė',
	'LBL_DELIMITER' => 'Skirtukas',
	'LBL_HAS_HEADER' => 'Turi antraštę',
	'LBL_IMPORT_STEP_3' => '3 žingsnis',
	'LBL_IMPORT_STEP_3_DESCRIPTION' => 'Besidubliuojančių įrašų apdorojimas',
	'LBL_IMPORT_STEP_3_DESCRIPTION_DETAILED' => 'Pažymėkite šią parinktį norėdami įjungti ir nustatyti besidubliuojančių įrašų suliejimo kriterijus',
	'LBL_SPECIFY_MERGE_TYPE' => 'Pasirinkite, kokius veiksmus atlikti esant besidubliuojantiems įrašams',
	'LBL_SELECT_MERGE_FIELDS' => 'Pasirinkite lyginamuosius laukus besidubliuojantiems įrašams aptikti',
	'LBL_AVAILABLE_FIELDS' => 'Galimi laukai',
	'LBL_SELECTED_FIELDS' => 'Pasirinkti laukai',
	'LBL_NEXT_BUTTON_LABEL' => 'Toliau',
	'LBL_IMPORT_STEP_4' => '4 žingsnis',
	'LBL_IMPORT_STEP_4_DESCRIPTION' => 'Susiekite stulpelius su modulio laukais',
	'LBL_FILE_COLUMN_HEADER' => 'Antraštė',
	'LBL_ROW_1' => '1 eilutė',
	'LBL_CRM_FIELDS' => 'Sistemos laukai',
	'LBL_DEFAULT_VALUE' => 'Numatytoji reikšmė',
	'LBL_SAVE_AS_CUSTOM_MAPPING' => 'Įrašyti kaip tinkintą susiejimą',
	'LBL_IMPORT_BUTTON_LABEL' => 'Importuoti',
	'LBL_RESULT' => 'Rezultatas',
	'LBL_TOTAL_RECORDS_IMPORTED' => 'Įrašai sėkmingai importuoti',
	'LBL_NUMBER_OF_RECORDS_CREATED' => 'Įrašai sukurti',
	'LBL_NUMBER_OF_RECORDS_UPDATED' => 'Įrašai pakeisti',
	'LBL_NUMBER_OF_RECORDS_SKIPPED' => 'Įrašai praleisti',
	'LBL_NUMBER_OF_RECORDS_MERGED' => 'Įrašai sulieti', 
	'LBL_TOTAL_RECORDS_FAILED' => 'Įrašų nepavyko importuoti',
	'LBL_IMPORT_MORE' => 'Importuoti daugiau',
	'LBL_VIEW_LAST_IMPORTED_RECORDS' => 'Paskiausiai importuoti įrašai',
	'LBL_UNDO_LAST_IMPORT' => 'Atšaukti paskutinę importo operaciją',
	'LBL_FINISH_BUTTON_LABEL' => 'Užbaigti',
	'LBL_UNDO_RESULT' => 'Atšaukti importavimo rezultatą',
	'LBL_TOTAL_RECORDS' => 'Įrašų skaičius',
	'LBL_NUMBER_OF_RECORDS_DELETED' => 'Pašalintų įrašų skaičius',
	'LBL_OK_BUTTON_LABEL' => 'Gerai',
	'LBL_IMPORT_SCHEDULED' => 'Importuoti suplanuotus',
	'LBL_RUNNING' => 'Vyksta',
	'LBL_CANCEL_IMPORT' => 'Atsisakyti importavimo',
	'LBL_ERROR' => 'Klaida',
	'LBL_CLEAR_DATA' => 'Išvalyti duomenis',
	'ERR_LOCAL_INFILE_NOT_ON' => 'local_infile variable is turned off on the database server.',
	'ERR_UNIMPORTED_RECORDS_EXIST' => 'Šį kartą nepavyko importuoti daugiau duomenų. Atlikite naują importavimą.',
	'ERR_IMPORT_INTERRUPTED' => 'Einamoji importo operacija nepavyko. Bandykite vėliau.',
	'ERR_FAILED_TO_LOCK_MODULE' => 'Nepavyko užrakinti modulio importavimui. Pabandykite vėliau.',
	'LBL_SELECT_SAVED_MAPPING' => 'Pasirinkite įsimintą susiejimą',
	'LBL_IMPORT_ERROR_LARGE_FILE' => 'Importavimo klaida, per didelis failas, ',
	'LBL_FILE_UPLOAD_FAILED' => 'Failo įkelti nepavyko',
	'LBL_IMPORT_CHANGE_UPLOAD_SIZE' => 'yra didžiausias leistinas importuojamo failo dydis',
	'LBL_IMPORT_DIRECTORY_NOT_WRITABLE' => 'Nepavyko rašyti į importo aplanką',
	'LBL_IMPORT_FILE_COPY_FAILED' => 'Nepavyko nukopijuoti importuojamojo failo',
	'LBL_INVALID_FILE' => 'Netinkamas failas',
	'LBL_NO_ROWS_FOUND' => 'Nerasta eilučių',
	'LBL_SCHEDULED_IMPORT_DETAILS' => 'Jūsų importavimas suplanuotas pradėti per artimiausias 15 minučių. Importavimui pasibaigus, jūs gausite el. laišką.<br> <br>
										Kad pranešimas nedingtų, įsitikinkite, jog teisingai sukonfigūruotas siunčiamų laiškų serveris ir jūsų el. pašto adresas.',
	'LBL_DETAILS' => 'Išsami informacija',
	'skipped' => 'Praleisti įrašai',
	'failed' => 'Nepavykę įrašai',
	
        'LBL_IMPORT_LINEITEMS_CURRENCY'=> 'Valiuta (eilutės elementų laukams)',
        'LBL_USE_SAVED_MAPS'=>'Naudoti išsaugotas žymes',
        'LBL_IMPORT_MAP_FIELDS'=>'Susiekite stulpelius su KVS laukais',
        'LBL_UPLOAD_CSV'=>'Įkelti CSV failą', 
        'LBL_UPLOAD_VCF'=>'Įkelti VCF failą',
        'LBL_DUPLICATE_HANDLING'=>'Apdoroti dublikatus',
        'LBL_FIELD_MAPPING'=>'Laukų susiejimas',
        'LBL_IMPORT_FROM_CSV_FILE'=>'Įkelti iš CSV failo',
        'LBL_SELECT_IMPORT_FILE_FORMAT'=>'Iš kur norėtumėte importuoti?',
        'LBL_CSV_FILE'=>'CSV failas',
        'LBL_VCF_FILE'=>'VCF failas',
        'LBL_GOOGLE'=>'Google',
        'LBL_IMPORT_COMPLETED'=>'Importas užbaigtas',
        'LBL_IMPORT_SUMMARY'=>'Importo santrauka',
        'LBL_DELETION_COMPLETED'=>'Ištrynimas užbaigtas',
        'LBL_TOTAL_RECORDS_SCANNED'=>'Viso įrašų nuskanuota',
        'LBL_SKIP_BUTTON'=>'Praleisti',
    'LBL_DUPLICATE_RECORD_HANDLING' => 'Pasikartojančių įrašų apdorojimas',
    'LBL_IMPORT_FROM_VCF_FILE' => 'Įkelti iš VCF failo',
    'LBL_SELECT_VCF_FILE' => 'Pažymėkite VCF failą',
    'LBL_DONE_BUTTON' => 'Užbaigta',
    'LBL_DELETION_SUMMARY' => 'Ištrynti santrauką',

	'LBL_SKIP_THIS_STEP' => 'Praleisti šitą žingsnį',
	'LBL_ICS_FILE'=>'ICS failas',
	'LBL_UPLOAD_ICS'=>'Įkelti ICS failą',
	'LBL_IMPORT_FROM_ICS_FILE'=>'Importuoti iš ICS failo',
	'LBL_SELECT_ICS_FILE' => 'Pažymėkite ICS failą',
    
        //Scheduled Import translations
        'LBL_ENABLE_CRON' => '<b>Please do enable Scheduled Import cron job from settings scheduler</b>',
        'LBL_SCHEDULE_IMPORT_SUBJECT' => 'vtiger CRM - Scheduled Import Report for',
        'LBL_IMPORT_COMPLETED' => 'Importas užbaigtas',
        'LBL_CHECK_IMPORT_STATUS' => '<br/><br/> We recommend you to login to the CRM and check few records to confirm that the import has been successful.'
);
