<?php

/* +***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * *********************************************************************************** */

$languageStrings = array(
	'ERR_DATABASE_CONNECTION_FAILED' => 'Nepavyko prisijungti prie duomenų bazės serverio',
	'ERR_DB_NOT_FOUND' => 'Nepavyko rasti šios duomenų bazės. Pabandykite pakeisti duomenų bazės nuostatas',
	'ERR_INVALID_MYSQL_PARAMETERS' => 'Nurodyti netinkami „MySQL“ ryšio parametrai',
	'ERR_INVALID_MYSQL_VERSION' => 'Ši „MySQL“ versija nepalaikoma, atnaujinkite į versiją „MySQL 5.1.x“ ar aukštesnę ',
	'ERR_UNABLE_CREATE_DATABASE' => 'Nepavyko sukurti duomenų bazės',
	'LBL_ADMIN_INFORMATION'=>'Administratoriaus informacija',
	'LBL_ADMIN_USER_INFORMATION' => 'Administratoriaus informacija',
	'LBL_CONFIRM_CONFIGURATION_SETTINGS' => 'Patvirtinti nuostatas',
	'LBL_CREATE_NEW_DB'=>'Sukurti naują duomenų bazę',
	'LBL_CURRENCIES'=>'Valiuta',
	'LBL_CURRENCY' => 'Valiuta',
	'LBL_DATABASE_INFORMATION' => 'Duomenų bazės informacija',
	'LBL_DATABASE_TYPE' => 'Duomenų bazės tipas',
	'LBL_DATE_FORMAT'=>'Datos formatas',
	'LBL_DB_NAME' => 'Duomenų bazės vardas',
	'LBL_DISAGREE' => 'Nesutinku',
	'LBL_EMAIL' => 'El. paštas',
	'LBL_GD_LIBRARY' => 'GD bibliotekos palaikymas',
	'LBL_HOST_NAME' => 'Serverio vardas',
	'LBL_I_AGREE' => 'Sutinku',
	'LBL_IMAP_SUPPORT' => 'IMAP palaikymas',
	'LBL_INSTALLATION_IN_PROGRESS'=>'Vyksta diegimas',
	'LBL_INSTALLATION_WIZARD' => 'Diegimo vedlys',
	'LBL_INSTALL_BUTTON' => 'Diegti',
	'LBL_INSTALL_PREREQUISITES' => 'Diegimui būtinos sąlygos',
	'LBL_MORE_INFORMATION' => 'Daugiau informacijos',
	'LBL_NEXT' => 'Toliau',
	'LBL_ONE_LAST_THING' => 'Paskutinis dalykas…',
	'LBL_PASSWORD_MISMATCH' => 'Įveskite slaptažodžius iš naujo, nes slaptažodis ir pakartotinai įvestas slaptažodis nesutampa.',
	'LBL_PASSWORD' => 'Slaptažodis',
	'LBL_PHP_CONFIGURATION' => 'PHP konfigūracija',
	'LBL_PHP_RECOMMENDED_SETTINGS'=>'Rekomenduojamos PHP nuostatos',
	'LBL_PHP_VERSION' => 'PHP versija',
	'LBL_PLEASE_WAIT'=>'Prašome palaukti',
	'LBL_PRESENT_VALUE' => 'Esama reikšmė',
	'LBL_READ_WRITE_ACCESS' => 'Skaitymo/rašymo prieiga',
	'LBL_RECHECK' => 'Patikrinti dar kartą',
	'LBL_REQUIRED_VALUE' => 'Reikalinga reikšmė',
	'LBL_RETYPE_PASSWORD' => 'Pakartokite slaptažodį',
	'LBL_ROOT_PASSWORD' => 'Administratoriaus slaptažodis',
	'LBL_ROOT_USERNAME' => 'Administratoriaus naudotojo vardas',
	'LBL_SYSTEM_CONFIGURATION' => 'Sistemos konfigūracija',
	'LBL_SYSTEM_INFORMATION' => 'Sistemos informacija',
	'LBL_TIME_ZONE' => 'Laiko juosta',
	'LBL_TRUE' => 'Įgalintas',
	'LBL_URL' => 'URL',
	'LBL_USERNAME' => 'Naudotojo vardas',
	'LBL_VTIGER6_SETUP_WIZARD_DESCRIPTION' => 'Šis diegimo vedlys jums padės įdiegti „Vtiger 6“ programą',
	'LBL_WELCOME_TO_VTIGER6_SETUP_WIZARD' => 'Sveiki, čia „Vtiger 6“ diegimo vedlys',
	'LBL_WELCOME' => 'Sveiki!',
	'LBL_ZLIB_SUPPORT' => '„Zlib“ palaikymas',
	'MSG_DB_PARAMETERS_INVALID' => 'nurodytas duomenų bazės tipas, serverio vardas, prievado numeris, naudotojo vardas arba slaptažodis netiko',
	'MSG_DB_ROOT_USER_NOT_AUTHORIZED' => 'Pranešimas: nurodytas duomenų bazės administratorius neturi teisių kurti duomenų bazes, arba duomenų bazės pavadinimas turi specialiųjų simbolių. Pabandykite pakeisti duomenų bazės nuostatas.',
	'MSG_DB_USER_NOT_AUTHORIZED' => 'nurodytas duomenų bazės naudotojas neturi teisės jungtis prie duomenų bazės serverio iš šio kompiuterio',
	'MSG_LIST_REASONS' => 'Taip galėjo nutikti dėl šių priežasčių',
        'LBL_MYSQLI_CONNECT_SUPPORT'=>'„mysqli“ palaikymas',
        'LBL_OPEN_SSL'=>'„openssl“ palaikymas',
        'LBL_CURL'=>'„cURL“ palaikymas',
);
