<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/

$languageStrings = Array (
	'MailManager'=>'Laiškų tvarkyklė',
	
	// General translations
	'LBL_Folders'=>'Katalogai',
	'LBL_Newer'=>'Naujesnis',
	'LBL_Older'=>'Ankstesni',
	'LBL_No_Mails_Found'=>'Laiškų nerasta.',
	'LBL_Go_Back'=>'Atgal',
	'LBL_Reply_All'=>'Atsakyti visiems',
	'LBL_Reply'=>'Atsakyti',
	'LBL_Mark_As_Unread'=>'Žymėti kaip neskaitytą',
	'LBL_Previous'=>'praeitas',
	'LBL_Next'=>'Toliau',
	'LBL_RELATED_RECORDS'=>'Susiję įrašai',
	'LBL_Mailbox'=>'Pašto dėžutė',
	'LBL_Outbox'=>'Sistemos išsiųsti laiškai',
	'LBL_Like'=>'kaip',
	'LBL_Mail_Server'=>'Laiškų serverio pavadinimas arba IP',
	'LBL_Refresh'=>'Atšviežinti',
	'LBL_Cancel'=>'Atsisakyti',
	'LBL_Send'=>'Siųsti',
	'LBL_Compose'=>'Kurti',
	'LBL_Forward'=>'Persiųsti',
	'LBL_Remove'=>'Pašalinti',
	'LBL_Associate'=>'Susieti',
	'LBL_Create_Contact'=>'Sukurti adresatą',
	'LBL_No_Matching_Record_Found'=>'Jokių atitinkančių įrašų nerasta.',
	'LBL_ACTIONS'=>'Veiksmai',
	'LBL_Search'=>'Paieška',
	'LBL_Delete'=>'Pašalinti',
	
	'LBL_Username'=>'Vartotojo vardas',
	'LBL_Your_Mailbox_Account'=>'jūsų pašto dėžutės paskyrą',
	'LBL_Password'=>'Slaptažodis',
	'LBL_Account_Password'=>'paskyros slaptažodis',
	'LBL_Protocol'=>'Protokolas',
	'LBL_Imap2'=>'IMAP2',
	'LBL_Imap4'=>'IMAP4',
	'LBL_SSL_Options'=>'SSL savybės',
	'LBL_No_TLS'=>'Be TLS',
	'LBL_TLS'=>'TLS',
	'LBL_SSL'=>'SSL',
	'LBL_Certificate_Validations'=>'Sertifikatų tvirtinimas',
	'LBL_Validate_Cert'=>'Patvirtinti sertifikatą',
	'LBL_Do_Not_Validate_Cert'=>'Nepatvirtinti sertifikato',
	'LBL_SELECT_ACCOUNT_TYPE'=>'Pasirinkite organizacijos tipą',
	
	'LBL_FROM'=>'Nuo',
	'LBL_TO' => 'Kam:',
	'LBL_CC'=>'Kopija:',
	'LBL_BCC'=>'Namatomoji kopija:',
	'LBL_Date'=>'Data',
	'LBL_Attachments'=>'Priedai',
	'LBL_EMAIL_TEMPLATES_LIST'=>'Laiškų šablonų sąrašas',
	'LBL_SELECT_EMAIL_TEMPLATE'=>'Pasirinkite el. pašto šabloną',
	'LBL_ATTACHMENTS'=>'Priedas:',
	'LBL_SELECT_DOCUMENTS'=>'Pasirinkite dokumentus',
	'LBL_IN'=>'tarp ',
	'LBL_FIND'=>'Rasti',
	'LBL_SAVE_NOW'=>'Įrašyti dabar',
	'LBL_Drafts'=>'Juodraščiai',
 	'LBL_NO_EMAILS_SELECTED'=>'Nepažymėta jokių laiškų',
	'LBL_SUBJECT'=>'Tema ',
	'LBL_WRITE_ACCESS_FOR'=>'Rašymo teisė',
	'LBL_READ_ACCESS_FOR'=>'Skaitymo prieiga',
	'LBL_MODULE_DENIED'=>'modulis atmestas',
	'LBL_REFRESH_TIME'=>'Atšviežinimo laikas',
	'LBL_NONE'=>'N',
	'LBL_5_MIN'=>'5 min.',
	'LBL_10_MIN'=>'10 minučių',
	'LBL_MOVE_TO'=>'Perkelti į ...',
    'LBL_MAILMANAGER_ADD_Contacts'=>'Pridėti adresatą',
    'LBL_MAILMANAGER_ADD_Accounts'=>'Pridėti organizaciją',
    'LBL_MAILMANAGER_ADD_Leads'=>'Pridėti galimą klientą',
    'LBL_MAILMANAGER_ADD_Calendar'=>'Pridėti darbą',
    'LBL_MAILMANAGER_ADD_HelpDesk'=>'Pridėti kortelę',
    'LBL_MAILMANAGER_ADD_Emails'=>'Pridėti laišką',
    'LBL_MAILMANAGER_ADD_ModComments'=>'Pridėti pastabą',
    'LBL_ADD'=>'Pridėti',
	'JSLBL_Body_Cannot_Be_Empty'=>'Pagrindinė dalis turi būti užpildyta',
	'LBL_ALLMAILS'=>'Visi laiškai',
	'LBL_TO_CONTACTS'=>'Adresatams',
	'LBL_TO_ACCOUNTS'=>'Organizacijoms',
	'LBL_TO_LEADS'=>'Galimiems klientams',
	'LBL_TO_USERS'=>'Vartotojams',
	'LBL_SENT_MAILS'=>'Išsiųsti laiškai',
	'LBL_Print'=>'Spausdinti',
	
	'LBL_SAVE_BUTTON_LABEL'=>'Įrašyti',
	'LBL_CANCEL_BUTTON_LABEL'=>'Atsisakyti',
	'LBL_CREATE_MAILBOX'=>'Sukurti pašto dėžutę',
	'LBL_WRITE_YOUR_COMMENT_HERE'=>'Pridėkite savo komentarą čia…'
);

$jsLanguageStrings = Array (
	'MailManager'=>'Laiškų tvarkyklė',
	
	// Translations for JS (please use the prefix JSLBL in key)
	'JSLBL_Loading_Please_Wait'=>'Keliama, prašome palaukti',
	'JSLBL_Loading'=>'Keliama...',
	'JSLBL_Settings'=>'Nuostatos',
	'JSLBL_Opening'=>'Atidarymas',
	'JSLBL_Deleting'=>'Šalinama',  
	'JSLBL_Updating'=>'Atnaujinama',
	'JSLBL_Associating'=>'Susiejama',
	'JSLBL_Saving_And_Verifying'=>'Įrašoma ir tvirtinama',
	'JSLBL_Failed_To_Open_Mail'=>'Nepavyko atverti laiško',
	'JSLBL_Finding_Relation'=>'Randamas sąryšis',
	'JSLBL_Find_Relation_Now'=>'Rasti sąryšį dabar',
	'JSLBL_Searching'=>'Ieškoma',
	'JSLBL_Searching_Please_Wait'=>'Ieškoma, prašome palaukti',
	'JSLBL_Sending'=>'Siunčiama',
	'JSLBL_Replied'=>'Atsakyta',
	'JSLBL_Failed_To_Send_Mail'=>'Nepavyko įrašyti laiško',
	'JSLBL_Recepient_Cannot_Be_Empty'=>'Gavėjas turi būti įrašytas',
	'JSLBL_Subject_Cannot_Be_Empty'=>'Tema turi būti užpildyta',
	'JSLBL_Removing'=>'Šalinama',
	'JSLBL_Choose_Server_Type'=>'Pasirinkti serverio tipą',
	'JSLBL_Other'=>'Kita',
	'JSLBL_Gmail'=>'Gmail',
	'JSLBL_Fastmail'=>'Greitasis paštas',
	'JSLBL_Search_For_Email'=>'Ieškoti el. pašto ',
	'JSLBL_Nothing_Found'=>'Nieko nerata',
	'JSLBL_Delete_Confirm'=>'Ar tikrai norite visam laikui pašalinti laiškus?',
	'JSLBL_Delete_Mails_Confirm'=>'Ar norite pašalinti laiškus?',
	'JSLBL_Receipents_Warning_Message'=>'Pasirinkite gavėjus',
	'JSLBL_NO_MATCH'=>'Atitikmenų nerasta',
	'JSLBL_Saving'=>'Įrašoma',
	'JSLBL_Failed_To_Save_Mail'=>'Nepavyko įrašyti laiško',
	'JSLBL_ATTACHMENT_NOT_DELETED'=>'Priedo pašalinti nepavyko',
	'JSLBL_UPLOAD_CANCEL'=>'Atsisakyti',
	'JSLBL_UPLOAD_DROPFILES'=>'Nutempkite failus ',
	'JSLBL_UPLOAD_FILE'=>'Išsiųsti',
	'JSLBL_UPLOAD_DELETE'=>'[x]',
	'JSLBL_UPLOAD_FAILED'=>'Nepavyko  ',
	'JSLBL_FILEUPLOAD_LIMIT_EXCEEDED'=>'Siunčiamasis failas viršija talpos limitą',
	'JSLBL_MAIL_SENT'=>'Laiškas išsiųstas',
	'JSLBL_EMAIL_FORMAT_INCORRECT'=>'Nurodykite tinkamą el. pašto adresą',
	'JSLBL_Saving'=>'Įrašoma',
	'JSLBL_SaveWith_EmptySubject'=>'Įrašyti palikus temos lauką tuščią?',
	'JSLBL_Delete'=>'Pašalinti',
	'JSLBL_Drafts'=>'Juodraščiai',
	'JSLBL_PASSWORD_CANNOT_BE_EMPTY'=>'Slaptažodis turi būti įvestas',
	'JSLBL_SERVERNAME_CANNOT_BE_EMPTY'=>'Serverio pavadinimas turi būti įrašytas',
	'JSLBL_USERNAME_CANNOT_BE_EMPTY'=>'Vartotojo vardas turi būti užpildytas',
	'JSLBL_ACCOUNTNAME_CANNOT_EMPTY'=>'Organizacijos pavadinimas turi būti įrašytas',
	'JSLBL_FROM'=>'Nuo:',
	'JSLBL_DATE'=>'Data:',
	'JSLBL_SUBJECT'=>'Tema:',
	'JSLBL_TO'=>'Kam:',
	'JSLBL_CC'=>'Kopija:',
	'JSLBL_FORWARD_MESSAGE_TEXT'=>'_---------- Persiunčiamas pranešimas ----------',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_MAIL'=>'Pasirinkite bent vieną paštą',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_RECORD'=>'Pasirinkie bent vieną įrašą',
	'JSLBL_MAIL_MOVED'=>'Laiškas(-ai) perkelti',
	'JSLBL_MOVING'=>'Perkeliami laiškai',
	'JSLBL_LOADING_FOLDERS'=>'Keliami katalogai',
	'JSLBL_ADD_COMMENT'=>'Pridėti pastabą',
    'JSLBL_Yahoo'=>'Yahoo',
    'JSLBL_CANNOT_ADD_EMPTY_COMMENT'=>'Pastaba turi būti įrašyta',
    'JSLBL_NO_EMAILS_SELECTED'=>'Nepažymėta jokių laiškų',
    'JSLBL_ENTER_SOME_VALUE'=>'Įveskite eilutę paieškai',
    'JSLBL_DRAFT_MAIL_SAVED'=>'Laiškas įrašytas juodraščiuose.',
);

// Special Handling: Mix of language strings are used.
$languageStrings = array_merge($languageStrings, $jsLanguageStrings);
