<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'300-Sales-Software'=>'300-Pardavimai-Programinė-įranga',
	'301-Sales-Hardware'=>'301-Pardavimai-Aparatinė-įranga',
	'302-Rental-Income'=>'302-Nuomos-Pajamos',
	'303-Interest-Income'=>'303-Palūkanų-Pajamos',
	'304-Sales-Software-Support'=>'304-Pardavimai-Programinė-įranga-Palaikymas',
	'305-Sales Other'=>'305-Pardavimai-Kita',
	'306-Internet Sales'=>'306-Pardavimai-internetu',
	'307-Service-Hardware Labor'=>'307-Paslaugos-Aparatinės-įrangos-darbai',
	'308-Sales-Books'=>'308-Pardavimai-Knygos',
	'Box'=>'Dėžutė',
	'Carton'=>'Dėžė',
	'Caton'=>'Dėžė',
	'Commission Rate'=>'Komisinių kursas',
	'CRM Applications'=>'CRM programos',
	'Dozen'=>'Tuzinas',
	'Each'=>'Kiekvienas',
	'GL Account'=>'Didžiosios knygos paskyra',
	'Handler'=>'Tvarkytojas',
	'Hardware'=>'Aparatinė įranga',
	'Hours'=>'Valanda',
	'Impressions'=>'Parodymas',
	'LBL_ADD_RECORD' => 'Pridėti prekę',
	'LBL_ADD_TO_PRICEBOOKS' => 'Įtraukti į kainynus', //Duplicated key-value pairs
	'Lb'=>'kg',
	'LBL_IMAGE_INFORMATION' => 'Prekės paveikslo informacija',
	'LBL_MORE_CURRENCIES' => 'daugiau valiutų', 
	'LBL_PRICE' => 'Kaina',
	'LBL_PRICES' => 'Prekių kainos',
	'LBL_PRODUCT_INFORMATION' => 'Prekės informacija',
    'LBL_PRODUCTSMOD_DISABLED' => 'Prekėms peržiūrėti turi būti įjungtas Prekių modulis',
	'LBL_RECORDS_LIST' => 'Prekių sąrašas',
	'LBL_RESET_PRICE' => 'Atstatyti kainą',
	'LBL_RESET' => 'Atstatyti',
	'LBL_STOCK_INFORMATION' => 'Sandėlio informacija',
	'Manufacturer' => 'Gamintojas',
	'Mfr PartNo' => 'Gamintojo prekės kodas',
	'M'=>'m',
	'--None--'=>'—Nieko—',
	'Pack'=>'Pakuotė',
	'Pages'=>'Puslapis',
	'Part Number' => 'Prekės kodas',
	'Pieces'=>'Vienetas',
	'Product Active' => 'Prekė aktyvi',
	'Product Category' => 'Prekės kategorija',
	'Product Image'=>'Prekės paveikslas',
	'Product No' => 'Prekės Nr.',
	'Product Sheet'=>'Prekės lapas',
	'Products' => 'Prekės',
	'Qty In Demand'=>'Užsakytų prekių kiekis',
	'Qty In Stock'=>'Kiekis sandėlyje',
	'Qty/Unit'=>'Kiekis pakuotėje',
	'Reams'=>'Popieriaus pakas',
	'Reorder Level'=>'Kartoti užsakymą esant kiekiui', //Duplicated key-value pairs
	'Serial No'=>'Serijos Nr.',
	'Sheet'=>'Lapas',
	'SINGLE_Products' => 'Prekė',
	'Software'=>'Programinė įranga',
	'Spiral Binder'=>'Spiralinis rišiklis',
	'Sq Ft'=>'m²',
	'Tax Class'=>'Mokesčių grupė',
	'Unit Price'=>'Vieneto kaina',
	'Usage Unit'=>'Apskaitos vienetas',
	'Vendor PartNo' => 'Tiekėjo prekės kodas', //Duplicated key-value pairs
	'Website' => 'Svetainė',
);
