<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'Reports'=>'Ataskaitos',
	'SINGLE_Reports' => 'Ataskaita',

	// Basic Strings
	'LBL_FOLDER_NOT_EMPTY' => 'Aplankas nėra tuščias',
	'LBL_MOVE_REPORT' => 'Perkelti ataskaitas',
	'LBL_CUSTOMIZE' => 'Tinkinti',
	'LBL_REPORT_EXPORT_EXCEL' => 'Eksportuoti „Excel“ formatu',
	'LBL_REPORT_PRINT' => 'Spausdinti',
	'LBL_CREATING_REPORT' => 'Kuriama ataskaita',
	'LBL_EDITING_REPORT' => 'Ataskaitos redagavimas',
	'LBL_REPORT_DETAILS' => 'Ataskaitos informacija',
	'LBL_SELECT_COLUMNS' => 'Pasirinkite stulpelius',
	'LBL_FILTERS' => 'Filtrai',
	'LBL_FOLDERS' => 'Aplankai',
	'LBL_ADD_NEW_FOLDER' => 'Pridėti aplanką',
	'LBL_FOLDER_NAME' => 'Aplanko pavadinimas',
	'LBL_FOLDER_DESCRIPTION' => 'Aplanko aprašymas',
	'LBL_WRITE_YOUR_DESCRIPTION_HERE' => 'Įveskite aprašymą',
	'LBL_DUPLICATES_EXIST' => 'Ataskaita tokiu pavadinimu jau egzistuoja',
	'LBL_FOLDERS_LIST' => 'Aplankų sąrašas',
	'LBL_DENIED_REPORTS' => 'Atmestos ataskaitos',
	'LBL_NO_OF_RECORDS' => 'Įrašų skaičius:',
    'LBL_MORE_RECORDS_TXT'=>'Žemiau rodoma tik 500 įrašų. Jei norite pamatyti visus, atlikite eksportavimą',
	'LBL_SCHEDULE_REPORTS' => 'Suplanuoti ataskaitos vykdymą',
	'LBL_AT_TIME' => 'Šiuo laiku',

	'LBL_DAILY' => 'Kasdien',
	'LBL_WEEKLY' => 'Nurodytomis savaitės dienomis',
	'LBL_MONTHLY_BY_DATE' => 'Nurodytomis mėnesio dienomis',
	'LBL_YEARLY' => 'Nurodytomis metų dienomis',
	'LBL_SPECIFIC_DATE' => 'Vieną kartą',
	'LBL_CHOOSE_DATE' => 'Pasirinkite datą',
	'LBL_ON_THESE_DAYS' => 'Šiomis dienomis',
	'LBL_SELECT_MONTH_AND_DAY' => 'Pasirinkite mėnesių dienas',
	'LBL_SELECTED_DATES' => 'Pasirinktos dienos',
	'LBL_EXCEEDING_MAXIMUM_LIMIT' => 'Viršytas didžiausias leistinas kiekis',
	'LBL_NEXT_TRIGGER_TIME' => 'Artimiausias vykdymo laikas',
	'LBL_RUN_REPORT' =>'Vykdyti ataskaitą',
	'LBL_SELECT_RECIEPIENTS' => 'Pasirinkite gavėjus',
	'LBL_SPECIFIC_EMAIL_ADDRESS' => 'Siųsti šiuo el. pašto adresu',
	'LBL_SAME_LEVEL_ROLES' => 'To paties lygio vaidmenys',
	'LBL_SUBORDINATE_ROLES' => 'Žemesnio lygio vaidmenys',
	//ListView Actions
	'LBL_ADD_RECORD' => 'Pridėti ataskaitą',
	'LBL_ADD_FOLDER' => 'Pridėti aplanką',
	'LBL_REPORT_DELETE_DENIED' => 'Šiai ataskaitai pašalinti neturite teisių',

	//Folder Actions
	'LBL_FOLDER_NOT_EMPTY' => 'Aplankas nėra tuščias',
	'LBL_FOLDER_CAN_NOT_BE_DELETED' => 'Šio aplanko pašalinti negalima',

	//Mass Actions
	'LBL_REPORTS_LIST' => 'Ataskaitų sąrašas',

	//Step1 Strings
	'LBL_REPORT_NAME' => 'Ataskaitos pavadinimas',
	'LBL_REPORT_FOLDER' => 'Ataskaitų aplankas',
	'LBL_DESCRIPTION' => 'Aprašymas',
	'PRIMARY_MODULE' => 'Pagrindinis modulis',
	'LBL_SELECT_RELATED_MODULES' => 'Pasirinkite susijusius modulius',
	'LBL_MAX' => 'Daugiausiai',
	'LBL_NEXT' => 'Toliau',
	'LBL_REPORTS' => 'Ataskaitų sąrašas',
	'LBL_SELECT_RELATED_MODULES' => 'Pasirinkite susijusius modulius',

	//Step2 Strings
	'LBL_GROUP_BY' => 'Grupuoti pagal',
	'LBL_SORT_ORDER' => 'Rikiavimo tvarka',
	'LBL_ASCENDING' => 'Didėjimo tvarka',
	'LBL_DESCENDING' => 'Mažėjimo tvarka',
	'LBL_CALCULATIONS' =>'Skaičiavimai',
	'LBL_COLUMNS' => 'Stulpeliai',
	'LBL_SUM_VALUE' => 'Suma',
	'LBL_AVERAGE' => 'Vidurkis',
	'LBL_LOWEST_VALUE' => 'Žemiausia reikšmė',
	'LBL_HIGHEST_VALUE' => 'Aukščiausia reikšmė',

	//Step3 Strings
	'LBL_GENERATE_REPORT' => 'Išsaugoti ir sugeneruoti ataskaitą',

	//DetailView
	'LBL_SUM' => 'Suma',
	'LBL_AVG' => 'Vid.',
	'LBL_MAX' => 'Daugiausiai',
	'LBL_MIN' => 'Min.',
	'LBL_FIELD_NAMES' => 'Laukų pavadinimai',
	'LBL_REPORT_CSV' => 'Eksportuoti CSV formatu',
	'LBL_VIEW_DETAILS' => 'Rodyti išsamią informaciją',
	'LBL_GENERATE_NOW' => 'Generuoti dabar',

	//List View Headers
	'Report Name' => 'Ataskaitos pavadinimas',

	//Default Folders Names, Report Names and Description
	'Account and Contact Reports'=>'Organizacijų ir adresatų ataskaitos',
	'Lead Reports'=>'Užklausų ataskaita',
	'Potential Reports'=>'Galimybių ataskaitos',
	'Activity Reports'=>'Veiklos ataskaitos',
	'HelpDesk Reports'=>'Užduočių kortelių ataskaitos',
	'Product Reports'=>'Prekių ataskaitos',
	'Quote Reports'=>'Pasiūlymų ataskaitos',
	'PurchaseOrder Reports'=>'Pirkimo užsakymų ataskaitos',
	'SalesOrder Reports'=>'Pardavimo užsakymų ataskaitos', //Added for SO
	'Invoice Reports'=>'Sąskaitų faktūrų ataskaitos',
	'Campaign Reports'=>'Kampanijų ataskaitos', //Added for Campaigns
	'Contacts by Accounts'=>'Adresatai pagal organizacijas',
	'Contacts without Accounts'=>'Adresatai be organizacijų',
	'Contacts by Potentials'=>'Adresatai pagal galimybes',
	'Contacts related to Accounts'=>'Adresatai susiję su organizacijomis',
	'Contacts not related to Accounts'=>'Adresatai nesusiję su organizacijomis',
	'Contacts related to Potentials'=>'Adresatai susiję su galimybėmis',
	'Lead by Source'=>'Užklausos pagal šaltinį',
	'Lead Status Report'=>'Užklausų būsenų ataskaita',
	'Potential Pipeline'=>'Galimybių grandinė',
	'Closed Potentials'=>'Užbaigtos galimybės',
	'Potential that have Won'=>'Laimėtos galimybės',
	'Tickets by Products'=>'Užduočių kortelės pagal prekes',
	'Tickets by Priority'=>'Užduočių kortelės pagal prioritetą',
	'Open Tickets'=>'Atviros užduočių kortelės',
	'Tickets related to Products'=>'Užduočių kortelės susijusios su prekėmis',
	'Tickets that are Open'=>'Atviros užduočių kortelės',
	'Product Details'=>'Prekės informacija',
	'Products by Contacts'=>'Prekės pagal adresatus',
	'Product Detailed Report'=>'Prekių išsami ataskaita',
	'Products related to Contacts'=>'Prekės susijusios su adresatais',
	'Open Quotes'=>'Atviri pasiūlymai',
	'Quotes Detailed Report'=>'Pasiūlymų išsami ataskaita',
	'Quotes that are Open'=>'Atviri pasiūlymai',
	'PurchaseOrder by Contacts'=>'Pirkimo užsakymai pagal adresatus',
	'PurchaseOrder Detailed Report'=>'Pirkimo užsakymų išsami ataskaita',
	'PurchaseOrder related to Contacts'=>'Pirkimo užsakymai susiję su adresatais',
	'Invoice Detailed Report'=>'Sąskaitų faktūrų išsami ataskaita',
	'Last Month Activities'=>'Praėjusio mėnesio veiklos',
	'This Month Activities'=>'Šio mėnesio veiklos',
	'Campaign Expectations and Actuals'=>'Kampanijų laukiami ir faktiniai rezultatai', //Added for Campaigns
	'SalesOrder Detailed Report'=>'Pardavimo užsakymų išsami ataskaita', //Added for SO

	'Email Reports'=>'Laiškų ataskaitos',
	'Contacts Email Report'=>'Adresatų laiškų ataskaita',
	'Accounts Email Report'=>'Organizacijos laiškų ataskaita',
	'Leads Email Report'=>'Užklausų laiškų ataskaita',
	'Vendors Email Report'=>'Tiekėjų laiškų ataskaita',

	'Emails sent to Contacts' => 'Laiškai išsiųsti adresatams',
	'Emails sent to Organizations' => 'Laiškai išsiųsti organizacijoms',
	'Emails sent to Leads' => 'Laiškai išsiųsti užklausėjams',
	'Emails sent to Vendors' => 'Laiškai išsiųsti tiekėjams',

	'LBL_PRINT_REPORT' => 'Spausdinti ataskaitą',
	'LBL_RECORDS' => 'Įrašai',
	'LBL_LIMIT_EXCEEDED' => 'Rodoma tik 1000 įrašų. Eksportuokite duomenis CSV arba „Excel“ formatu, jei norite pamatyti visus',
	'LBL_TOP' => 'Aukščiausi',
	'LBL_ALL_REPORTS' => 'Visos ataskaitos',
	'LBL_CALCULATION_CONVERSION_MESSAGE' => 'Škaičiavimai aliekami naudojant jūsų nustatymuose pasirinkta valiuta',

    //Summary/Pivot Reports
    'LBL_CREATING_PIVOT_REPORT' => 'Sukurti suvestinę ataskaitą',
    'LBL_EDITING_PIVOT_REPORT' => 'Redaguoti suvestinę ataskaitą',
    'LBL_SELECT_PIVOT_FIELDS' => 'Pasirinkite suvestinės laukus',
    'LBL_SELECT_ROWS' => 'Pasirinkite eilutę',
    'LBL_SELECT_DATA_FIELDS' => 'Pasirinkite duomenų laukus',
    'LBL_ADD_ROWS' => 'Pridėti eilutę',
    'LBL_ADD_COLUMNS' => 'Pridėti stulpelį',
    'LBL_ADD_DATA_FIELDS' => 'Pridėti duomenų laukus',
    'LBL_PIVOT_FIELDS' => 'Pasirinkti suvestinės laukai',
    'LBL_RECORD_COUNT' => 'Įrašų skaičius',
    'LBL_SELECT_PIVOT_FIELDS_WARNING' => 'Dėmesio: pasirinkite bent vieną eilutės, stulpelio ir duomenų laukus',
    'LBL_PIVOT_DATA_FIELDS_WARNING' => 'Įspėjimas: duomenų stulpelyje - agregavimo funkcijos (suma, vidurkis, mažiausiai ir daugiausiai) neturėtų būti kartojamos.',
    'LBL_MODIFY_CONDITIONS' => 'Pakeiskite sąlygas',
    'LBL_PIVOT_PREVIEW_EX' => 'Suvestinė ataskaitos peržiūra (pavyzdys)',

	//charts labels
	'LBL_SELECT_CHART_TYPE' => 'Pasirinkite diagramos tipą',
	'LBL_CLICK_THROUGH_NOT_AVAILABLE' => 'Click through not available as you have selected more than one module',
	'LBL_TOTAL_SUM_OF' => '%s – galutinė suma',
	'LBL_AVG_OF' => '%s – vidurkis',
	'LBL_MIN_OF' => '%s – žemiausia reikšmė',
	'LBL_MAX_OF' => '%s – aukščiausia reikšmė',
	'LBL_RECORD_COUNT' => 'Įrašų skaičius',
	'LBL_PIE_CHART' => 'Skritulinė diagrama',
	'LBL_VERTICAL_BAR_CHART' => 'Stulpelinė diagrama',
	'LBL_HORIZONTAL_BAR_CHART' => 'Juostinė diagrama',
	'LBL_LINE_CHART' => 'Linijinė diagrama',
	'LBL_SELECT_CHART' => 'Diagramos tipas',
	'LBL_CREATING_CHART_REPORT' => 'Ataskaitos – diagramos kūrimas',
	'LBL_EDITING_CHART_REPORT' => 'Ataskaitos – diagramos redagavimas',
	'LBL_GENERATE_CHART' => 'Generuoti diagramą',
	'LBL_SELECT_GROUP_BY_FIELD' => 'Pasirinkite grupavimo kriterijų',
	'LBL_SELECT_DATA_FIELD' => 'Pasirinkite duomenų laukus',
	'LBL_MODIFY_CONDITION' => 'Pakeiskite sąlygas',
	'LBL_PLEASE_SELECT_ATLEAST_ONE_GROUP_FIELD_AND_DATA_FIELD' => 'Pasirinkite bent vieną grupavimo kriterijų ir bent vieną duomenų lauką.',
	'LBL_FOR_BAR_GRAPH_AND_LINE_GRAPH_SELECT_3_MAX_DATA_FIELDS' => 'Stulpelinių ir juostinių diagramų atveju leidžiama pasirinkti ne daugiau kaip 3 duomenų laukus.',
	'LBL_DETAIL_REPORT' => 'Išsami ataskaita',
	'LBL_PIVOT_REPORT' => 'Suvestinė ataskaita',
	'LBL_CHARTS' => 'Diagrama',
    //Schedule Reports - Mail Content
    'LBL_AUTO_GENERATED_REPORT_EMAIL' => 'Tai – planinės ataskaitos automatiškai sugeneruotas laiškas .',
    'LBL_PIN_CHART_TO_DASHBOARD' => 'Prisegti diagramą prie skydelio',
    'LBL_FILE_FORMAT' => 'Failo formatas',
    
    'Report Type' => 'Ataskaitos tipas',
    'tabular' => 'Išsami informacija',
    'summary' => 'Lentelė',
    'pivot' => 'Suvestinė',
    'chart' => 'Diagrama',

    'LBL_REPORTS_MOVED_SUCCESSFULLY'=>'Ataskaitos perkeltos sėkmingai',
    'LBL_SAME_SOURCE_AND_TARGET_FOLDER'=>'Tikslinis aplankas yra tas pats kaip šaltinio aplankas.',
	'LBL_SHARE_REPORT' => 'Bendrinti ataskaitą',
	'LBL_SHARED_REPORTS' => 'Pasidalino su manim',
	'LBL_PINNED' => 'Prisegtas',
	'LBL_UNPINNED' => 'Atsegtas',
	'LBL_SEARCH_FOR_FOLDERS' => 'Iškoti aplankalų',
	'LBL_CHART_REPORT' => 'Diagramos ataskaita',
	'LBL_UNPIN_CHART_FROM_DASHBOARD' => 'Atsegti diagramą nuo skydelio',
	'LBL_REPORTS_DELETED_SUCCESSFULLY' => 'Ataskaitos sėkmingai ištrintos',
);
$jsLanguageStrings = array(
	'JS_DUPLICATE_RECORD' => 'Dubliuoti ataskaitą',
	'JS_CALCULATION_LINE_ITEM_FIELDS_SELECTION_LIMITATION' => 'Apribojimas: sąskaitos elemento laukai (kaina kainyne, nuolaida ir kiekis) gali būti naudojami tik tada, kai nepasirinkti jokie kiti skaičiuojami laukai.',
	'JS_NO_CHART_DATA_AVAILABLE' => 'Duomenys neprieinami. Patikrinkite pasirinktus laukus.',
    'JS_CHART_PINNED_TO_DASHBOARD' => 'Diagrama prisegta prie skydelio',
    'JS_CHART_ALREADY_PINNED_TO_DASHBOARD' => 'Diagrama jau yra prisegta prie skydelio',
	'JS_MOVE_REPORTS'=>'Perkelti ataskaitas',
    'JS_SCHEDULED_DATE_TIME_ERROR' => 'Numatyta data ir laikas turi būti vėlesni už dabartinę datą ir laiką',
	'JSLBL_PIN_CHART_TO_DASHBOARD' => 'Prisegti diagramą prie skydelio',
	'JSLBL_UNPIN_CHART_FROM_DASHBOARD' => 'Atsegti diagramą nuo skydelio',
	'JS_CHART_REMOVED_FROM_DASHBOARD' => 'Diagrama pašalinta iš skydelio',
);
