<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_ADD_RECORD' => 'Pridėti naudotoją',

	//MyPreference Blocks
	'LBL_MY_PREFERENCES'  =>  'Mano nuostatos',
	'LBL_MORE_INFORMATION'  =>  'Išsamesnė informacija',
	'LBL_USERLOGIN_ROLE'  =>  'Naudotojo prisijungimas ir vaidmuo',
	'LBL_USER_IMAGE_INFORMATION' => 'Naudotojo nuotrauka',
	'LBL_CURRENCY_CONFIGURATION' =>  'Piniginių sumų ir skaičių laukų nuostatos',
	'LBL_ADDRESS_INFORMATION' => 'Naudotojo adresas',
	'LBL_USER_ADV_OPTIONS' => 'Naudotojo papildomos parinktys',
	'Asterisk Configuration'  =>  '„Asterisk“ konfigūravimas',
	'LBL_HOME_PAGE_COMPONENTS' => 'Pradžios tinklalapio komponentai',
	'LBL_TAG_CLOUD_DISPLAY' => 'Žymių debesies rodymas',

	//MyPreference Fields
	'Role' => 'Vaidmuo ',
	'Admin' => 'Administratorius',
	'User Name' => 'Naudotojo vardas',
	'Default Activity View' => 'Numatytasis asmeninio kalendoriaus rodinys',
	'Default Calendar View' => 'Numatytasis kalendoriaus rodinys',
	'Default Lead View' => 'Numatytasis užklausų rodinys',
	'Title' => 'Pareigos',
	'Office Phone' => 'Darbo telefonas',
	'Department' => 'Padalinys',
	'Reports To' => 'Kam pavaldus',
	'Yahoo id' => 'Yahoo ID',
	'Home Phone' => 'Namų telefonas',
	'User Image' => 'User Image',
	'Date Format' => 'Datų formatas',
	'Tag Cloud' => 'Žymių debesis',
	'Signature' => 'Parašas',
	'Street Address' => 'Adresas',
	'Password' => 'Slaptažodis',
	'Confirm Password' => 'Patvirtinkite slaptažodį',
	'LBL_SHOWN' => 'rodomas',
	'LBL_HIDDEN' => 'nerodomas',
	'LBL_SHOW' => 'Rodyti',
	'LBL_HIDE' => 'Nerodyti',
	'LBL_HOME_PAGE_COMPO' => 'Pradžios tinklalapio komponentai',
	'LBL_LOGIN_HISTORY' => 'Prisijungimų žurnalas',
	'LBL_USERDETAIL_INFO' => 'Išsami informacija apie naudotoją',
	'LBL_DELETE_GROUP' => 'Šalinti grupę',
	'LBL_DELETE_GROUPNAME' => 'Šalinamos grupės',
	'LBL_TRANSFER_GROUP' => 'Perkelti savininkystę:',
	'LBL_DELETE_USER' => 'Šalinamas naudotojas',
	'LBL_REMOVE_USER' => 'Šalinti',
	'LBL_MORE_OPTIONS' => 'Daugiau parinkčių',
	'LBL_TRANSFER_USER' => 'Perkelti savininkystę naudotojui',
	'LBL_RESTORE_USER' => 'Atkurti naudotoją',
	'LBL_DELETE_PROFILE' => 'Šalinti profilį',
	'LBL_TRANSFER_ROLES_TO_PROFILE' => 'Perkelti vaidmenis profiliui',
	'LBL_PROFILE_TO_BE_DELETED' => 'Šalinamas profilis',
	'INTERNAL_MAIL_COMPOSER' => 'Vidinė laiškų rašyklė',
	'Asterisk Extension'  =>  '„Asterisk“ plėtinys',
	' Receive Incoming Calls'  =>  'Priimti gaunamus skambučius',
	'Webservice Access Key' => 'Prieigos raktas',
	'Language' => 'Kalba',
	'Theme' =>  'Tema',
	'Time Zone'  =>  'Laiko juosta',
	'Decimal Separator'  =>  'Trupmenos skirtukas',
	'Digit Grouping Pattern'  =>  'Skaitmenų grupavimo šablonas',
	'Digit Grouping Separator'  =>  'Skaitmenų grupių skirtukas',
	'Symbol Placement'  =>  'Ženklo pozicija',
	'Number Of Currency Decimals'  =>  'Valiutos skaitmenų po kablelio skaičius',
	'Truncate Trailing Zeros'  =>   'Nerodyti nereikšminių nulių',
	'Default Call Duration' => 'Numatytoji skambučio trukmė (min.)',
	'Other Event Duration' => 'Kito įvykio trukmė (min.)',
	'Calendar Hour Format' => 'Laiko formatas kalendoriuje',
	'Tag Cloud' => 'Žymių debesis',

	//Time zones-Dont change any value
	'Kwajalein'  =>  '(UTC-12:00) Datos keitimosi linija, Vakarinė pusė',
	'Pacific/Midway'  =>  '(UTC-11:00) Pasaulinis koordinuotasis laikas -11',
	'Pacific/Samoa'  =>  '(UTC-11:00) Samoa',
	'Pacific/Honolulu'  =>  '(UTC-10:00) Havajai',
	'America/Anchorage'  =>  '(UTC-09:00) Aliaska',
	'America/Los_Angeles'  =>  '(UTC-08:00) Ramiojo vandenyno laikas (JAV ir Kanada)',
	'America/Tijuana'  =>  '(UTC-08:00) Tichuana, Žemutinė Kalifornija',
	'America/Denver'  =>  '(UTC-07:00) Kalnų laikas (JAV ir Kanada)',
	'America/Chihuahua'  =>  '(UTC-07:00) Čihuahua, La Pasas, Masatlanas',
	'America/Mazatlan'  =>  '(UTC-07:00) Masatlanas',
	'America/Phoenix'  =>  '(UTC-07:00) Arizona',
	'America/Regina'  =>  '(UTC-06:00) Saskačevanas',
	'America/Tegucigalpa'  =>  '(UTC-06:00) Centrinė Amerika',
	'America/Chicago'  =>  '(UTC-06:00) Centrinis laikas (JAV ir Kanada)',
	'America/Mexico_City'  =>  '(UTC-06:00) Mieksikas',
	'America/Monterrey'  =>  '(UTC-06:00) Monterėjus',
	'America/New_York'  =>  '(UTC-05:00) Rytinis laikas (JAV ir Kanada)',
	'America/Bogota'  =>  '(UTC-05:00) Bogota, Lima, Kitas',
	'America/Lima'  =>  '(UTC-05:00) Lima',
	'America/Rio_Branco'  =>  '(UTC-05:00) Rio Branko',
	'America/Indiana/Indianapolis'  =>  '(UTC-05:00) Indiana (Rytinė)',
	'America/Caracas'  =>  '(UTC-04:30) Karakasas',
	'America/Halifax'  =>  '(UTC-04:00) Atlanto laikas (Kanada)',
	'America/Manaus'  =>  '(UTC-04:00) Manausas',
	'America/Santiago'  =>  '(UTC-04:00) Santjagas',
	'America/La_Paz'  =>  '(UTC-04:00) La Pasas',
	'America/Cuiaba'  =>  '(UTC-04:00) Kujaba',
	'America/Asuncion'  =>  '(UTC-04:00) Asunsjonas',
	'America/St_Johns'  =>  '(UTC-03:30) Niufaundlendas',
	'America/Argentina/Buenos_Aires'  =>  '(UTC-03:00) Buenos Airės',
	'America/Sao_Paulo'  =>  '(UTC-03:00) Brazilija',
	'America/Godthab'  =>  '(UTC-03:00) Grenlandija',
	'America/Montevideo'  =>  '(UTC-03:00) Montevidėjas',
	'Atlantic/South_Georgia'  =>  '(UTC-02:00) Vidurio atlantas',
	'Atlantic/Azores'  =>  '(UTC-01:00) Azorai',
	'Atlantic/Cape_Verde'  =>  '(UTC-01:00) Žaliojo kyšulio sala',
	'Europe/London'  =>  '(UTC) Londonas, Edinburgas, Dublinas, Lisabona',
	'UTC'  =>  '(UTC) Pasaulinis koordinuotasis laikas (Grinvičo laikas)',
	'Africa/Monrovia'  =>  '(UTC) Monrovija, Reikjavikas',
	'Africa/Casablanca'  =>  ' (UTC) Kasablanka',
	'Europe/Belgrade'  =>  '(UTC+01:00) Belgradas, Bratislava, Budapeštas, Liublijana, Praha',
	'Europe/Sarajevo'  =>  '(UTC+01:00) Sarajevas, Skopjė, Varšuva, Zagrebas',
	'Europe/Brussels'  =>  '(UTC+01:00) Briuselis, Kopenhaga, Madridas, Paryžius',
	'Africa/Algiers'  =>  '(UTC+01:00) Centrinė Afrika (Vakarinė)',
	'Europe/Amsterdam'  =>  '(UTC+01:00) Amsterdamas, Berlynas, Bernas, Roma, Stokholmas, Viena',
	'Europe/Minsk'  =>  '(UTC+02:00) Minskas',
	'Africa/Cairo'  =>  '(UTC+02:00) Kairas',
	'Europe/Helsinki'  =>  '(UTC+02:00) Helsinkis, Ryga, Sofija, Talinas, Vilnius',
	'Europe/Athens'  =>  '(UTC+02:00) Atėnai, Bukareštas',
	'Europe/Istanbul'  =>  '(UTC+02:00) Stambulas',
	'Asia/Jerusalem'  =>  '(UTC+02:00) Jeruzalė',
	'Asia/Amman'  =>  '(UTC+02:00) Amanas',
	'Asia/Beirut'  =>  '(UTC+02:00) Beirutas',
	'Africa/Windhoek'  =>  '(UTC+02:00) Vindhokas',
	'Africa/Harare'  =>  '(UTC+02:00) Hararė',
	'Asia/Kuwait'  =>  '(UTC+03:00) Kuveitas, Riadas',
	'Asia/Baghdad'  =>  '(UTC+03:00) Bagdadas',
	'Africa/Nairobi'  =>  '(UTC+03:00) Nairobis',
	'Europe/Moscow'  =>  '(UTC+03:00) Moscow, Volgograd',
	'Asia/Tehran'  =>  '(UTC+03:30) Teheranas',
	'Asia/Tbilisi'  =>  '(UTC+04:00) Tbilisis',
	'Asia/Muscat'  =>  '(UTC+04:00) Abu Dabis, Muskatas',
	'Asia/Baku'  =>  '(UTC+04:00) Baku',
	'Asia/Yerevan'  =>  '(UTC+04:00) Jerevanas',
	'Asia/Karachi'  =>  '(UTC+05:00) Islamabadas, Karačis',
	'Asia/Tashkent'  =>  '(UTC+05:00) Taškentas',
	'Asia/Kolkata'  =>  '(UTC+05:30) Čenajus, Kolkata, Mumbajus, Niu Delis',
	'Asia/Colombo'  =>  '(UTC+05:30) Šri Džajavardenepura',
	'Asia/Katmandu'  =>  '(UTC+05:45) Katmandu',
	'Asia/Dhaka'  =>  '(UTC+06:00) Daka',
	'Asia/Almaty'  =>  '(UTC+06:00) Almata',
	'Asia/Yekaterinburg'  =>  '(UTC+06:00) Jekaterinburgas',
	'Asia/Rangoon'  =>  '(UTC+06:30) Rangūnas',
	'Asia/Novosibirsk'  =>  '(UTC+07:00) Novosibirskas',
	'Asia/Bangkok'  =>  '(UTC+07:00) Bankokas, Džakarta',
	'Asia/Brunei'  =>  '(UTC+08:00) Pekinas, Honkongas',
	'Asia/Krasnoyarsk'  =>  '(UTC+08:00) Krasnojarskas',
	'Asia/Ulaanbaatar'  =>  '(UTC+08:00) Ulan Batoras',
	'Asia/Kuala_Lumpur'  =>  '(UTC+08:00) Kvala Lumpūras, Singapūras',
	'Asia/Taipei'  =>  '(UTC+08:00) Taipėjus',
	'Australia/Perth'  =>  '(UTC+08:00) Pertas',
	'Asia/Irkutsk'  =>  '(UTC+09:00) Irkutskas',
	'Asia/Seoul'  =>  '(UTC+09:00) Seulas',
	'Asia/Tokyo'  =>  '(UTC+09:00) Tokijas',
	'Australia/Darwin'  =>  '(UTC+09:30) Darvinas',
	'Australia/Adelaide'  =>  '(UTC+09:30) Adelaidė',
	'Australia/Canberra'  =>  '(UTC+10:00) Kanbera, Melburnas, Sidnėjus',
	'Australia/Brisbane'  =>  '(UTC+10:00) Brisbenas',
	'Australia/Hobart'  =>  '(UTC+10:00) Hobartas',
	'Asia/Vladivostok'  =>  '(UTC+10:00) Vladivostokas',
	'Pacific/Guam'  =>  '(UTC+10:00) Guamas, Port Morzbis',
	'Asia/Yakutsk'  =>  '(UTC+10:00) Jakutskas',
	'Etc/GMT-11' => '(UTC+11:00) Saliamono Salos, Naujoji Kaledonija',
	'Pacific/Fiji'  =>  '(UTC+12:00) Fidžis',
	'Asia/Kamchatka'  =>  '(UTC+12:00) Kamčiatka',
	'Pacific/Auckland'  =>  '(UTC+12:00) Oklandas',
	'Asia/Magadan'  =>  '(UTC+12:00) Magadanas',
	'Pacific/Tongatapu'  =>  '(UTC+13:00) Nukualofa',

	'Summary' => 'Santrauka',
	'Detail' => 'Išsami informacija',
	'LBL_USER_LIST_DETAILS' => 'Išsami informacija',

	'LBL_OLD_PASSWORD' => 'Senasis slaptažodis',
	'LBL_CHANGE_PASSWORD' => 'Keisti slaptažodį',
	'LBL_NEW_PASSWORD' => 'Naujas slaptažodis:',
	'LBL_CONFIRM_PASSWORD' => 'Patvirtinkite slaptažodį',
	'LBL_CHANGE_ACCESS_KEY' => 'Keisti prieigos raktą',
	'LBL_ACCESS_KEY_UPDATED_SUCCESSFULLY' => 'Prieigos raktas sėkmingai pakeistas',
	'LBL_FAILED_TO_UPDATE_ACCESS_KEY' => 'Prieigos rakto pakeisti nepavyko',
	'LBL_TRANSFER_OWNERSHIP' => 'Perkelti savininkystę',
	'LBL_LOGIN_AS' => 'Jungtis kaip',
	'LBL_USER_DELETED_SUCCESSFULLY' => 'Naudotojas sėkmingai pašalintas',
	'LBL_ACTIVE_USERS' => 'Aktyvūs naudotojai',
	'LBL_INACTIVE_USERS' => 'Neaktyvūs naudotojai',
	'LBL_CREATE_USER' => 'Kurti naudotoją',
	'LBL_DELETE_USER_PERMANENTLY' => 'Šalinti naudotoją negrįžtamai',
	'LBL_DELETE_USER_PERMANENTLY_INFO' => 'Šalinant naudotoją negrįžtamai, visi jo priklausiniai, įskaitant komentarus ir žurnalo įrašus, bus priskirti nurodytam naudotojui.',
	'LBL_RESTORE' => 'Atkurti',
	'LBL_USER_RESTORED_SUCCESSFULLY' => 'Naudotojas sėkmingai atkurtas',
	//Login strings
	'LBL_TO_CRM' => 'Prisijungimas prie CRM',
	'LBL_INVALID_USER_OR_PASSWORD' => 'Netinkamas naudotojo vardas arba slaptažodis.',
	'LBL_INVALID_USER_OR_EMAIL' => 'Neteisingas naudotojo vardas arba el. pašto adresas.',
	'LBL_EMAIL_SEND' => 'Jums išsiųstas slaptažodžio keitimo laiškas.',
	'ForgotPassword' => 'Pamiršau slaptažodį',
	'LBL_CONNECT_WITH_US' => 'Susisiekite su mumis',
	'LBL_GET_MORE' => 'Išnaudokite programą „Vtiger“ dar geriau',

	'LBL_TRANSFER_RECORDS_TO_USER' => 'Perkelti priklausinius naudotojui',
	'LBL_USER_TO_BE_DELETED' => 'Šalinamas naudotojas',
	'LBL_ALMOST_THERE'	=>	'Beveik baigta!',
	'LBL_ABOUT_ME'		=>	'Apie mane',
	'LBL_WE_PROMISE_TO_KEEP_THIS_PRIVATE'	=>	'(pažadame, tai nebus viešinama)',
	'LBL_ALL_FIELDS_BELOW_ARE_REQUIRED'		=>	'(visi tolesni laukai yra privalomi)',
	'LBL_GET_STARTED'	=> 'Pradėti',
	'LBL_YOUR_CONTACT_NUMBER' => 'Jūsų telefono numeris',
	'LBL_WHERE_ARE_YOU_FROM' =>	'Iš kur esate?',
	'LBL_SELECT_COUNTRY'	=> 'Pasirinkite šalį',
	'LBL_COMPANY_SIZE'		=> 'Įmonės dydis',
	'LBL_JOB_TITLE'			=> 'Pareigos',
	'LBL_DEPARTMENT'		=> 'Padalinys',
	'LBL_BASE_CURRENCY'		=> 'Pagrindinė valiuta',
	'LBL_CHOOSE_BASE_CURRENCY'	=> 'Pasirinkite pagrindinę valiutą',
	'LBL_OPERATING_CURRENCY'	=> 'Pagrindinė valiuta vėliau negali būti keičiama. Pasirinkite valiutą, kuria operuojate',
	'LBL_LANGUAGE' => 'Kalba',
	'LBL_CHOOSE_LANGUAGE'	=> 'Pasirinkite kalbą',
	'LBL_CHOOSE_TIMEZONE'	=> 'Pasirinkite laiko juostą',
	'LBL_DATE_FORMAT'		=> 'Datų formatas',
	'LBL_CHOOSE_DATE_FORMAT'=> 'Pasirinkite datos formatą',
	'LBL_PHONE'	=> 'Telefonas',
	'Space' => 'tarpas',
	//picklist values for Default Calendar View field in MyPreference Page
	'ListView' => 'Sąrašo rodinys',
	'MyCalendar' => 'Mano kalendorius',
	'SharedCalendar' => 'Bendras kalendorius',

	'LBL_CHANGE_OWNER' => 'Keisti savininką',
	'LBL_TRANSFER_OWNERSHIP' => 'Perkelti savininkystę',
	'LBL_TRANSFER_OWNERSHIP_TO_USER' => 'Perleisti CRM savininkystę naudotojui',
	'LBL_OWNERSHIP_TRANSFERRED_SUCCESSFULLY' => 'CRM savininkas sėkmingai pakeistas',
	'LBL_OWNERSHIP_TRANSFERRED_FAILED' => 'CRM savininko pakeisti nepavyko',
	'Account Owner' => 'Paskyros savininkas',
	'Starting Day of the week' => 'Pirmoji savaitės diena',
	'Day starts at' => 'Dienos pradžios laikas',
	'Default Event Status' => 'Numatytoji įvykio būsena',
	'Default Activity Type' => 'Numatytasis veiklos tipas',
	'Default Record View' => 'Numatytasis įrašo rodinys',
	'Left Panel Hide' => 'Kairysis polangis nerodomas',
	'Row Height' => 'Eilutės aukštis',

	//Change Username labels
	'LBL_CHANGE_USERNAME' => 'Keisti naudotojo vardą',
	'LBL_USERNAME_CHANGED' => 'Naudotojo vardas pakeistas sėkmingai',
	'ERROR_CHANGE_USERNAME' => 'Naudotojo vardo pakeisti nepavyko. Bandykite dar kartą',

	'LBL_RESTORE_USER_FAILED' => 'Naudotojo atkurti nepavyko. Aptiktas kitas CRM naudotojas tuo pačiu naudotojo vardu',

	'LBL_DUPLICATE_USER_EXISTS' => 'Toks naudotojas jau yra',

	/* For Vtiger7*/
	'LBL_USERS_SETTINGS' => 'NAUDOTOJO NUOSTATOS',
	'LBL_TEMPLATES' => 'Šablonai',
);

$jsLanguageStrings = array(

	//Curency seperator validation messages
	'JS_ENTER_OLD_PASSWORD'=>'Įveskite senąjį slaptažodį.',
	'JS_ENTER_NEW_PASSWORD'=>'Įveskite naująjį slaptažodį.',
	'JS_ENTER_CONFIRMATION_PASSWORD'=>'Pakartotinai įveskite slaptažodį.',
	'JS_REENTER_PASSWORDS'=>'Pakartotinai įveskite slaptažodžius, nes naujasis slaptažodis ir jo pakartojimas nesutampa.. ',
	'JS_INVALID_PASSWORD'=>'Turite pasirinkti galiojantį naudotojo vardą ir slaptažodį.',
	'JS_PASSWORD_CHANGE_FAILED_1'=>'Slaptažodžio pakeisti nepavyko naudotojui ',
	'JS_PASSWORD_CHANGE_FAILED_2'=>'nepavyko. Įveskite naują slaptažodį.',
	'JS_PASSWORD_INCORRECT_OLD'=>'Neteisingai nurodytas senasis slaptažodis. Įveskite jį iš naujo.',
	'JS_ENTERED_CURRENT_USERNAME_MSG' => 'Įvedėte esamą naudotojo vardą. Įveskite kitokį naudotojo vardą.',
	'JS_NEW_ACCESS_KEY_REQUESTED' => 'Prieigos rakto keitimas',
	'JS_CHANGE_ACCESS_KEY_CONFIRMATION' => 'Ketinate pakeisti prieigos raktą.&lt;br&gt;&lt;br&gt;Pakeitę prieigos raktą čia, turėsite jį atnaujinti ir visuose įdiegtuose prieduose.&lt;br&gt;&lt;br&gt;Ar norite tęsti?',
);