<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_ADD_RECORD'=>'Pridėti vartotoją',

	//MyPreference Blocks
	'LBL_MY_PREFERENCES'=>'Mano pirmenybės',
	'LBL_MORE_INFORMATION'=>'Daugiau informacijos',
	'LBL_USERLOGIN_ROLE'=>'Vartotojo prisijungimas ir vaidmuo',
	'LBL_USER_IMAGE_INFORMATION'=>'Vartotojo nuotrauka',
	'LBL_CURRENCY_CONFIGURATION'=>'Valiutos ir numerių lauko konfigūracija',
	'LBL_ADDRESS_INFORMATION'=>'Vartotojo adresas',
	'LBL_USER_ADV_OPTIONS'=>'Vartotojo išsamios parinktys',
	'Asterisk Configuration'=>'Žvaigždutės konfigūracija',
	'LBL_HOME_PAGE_COMPONENTS'=>'Pradinio puslapio komponentai',
	'LBL_TAG_CLOUD_DISPLAY'=>'Debesies žymės rodymas',

	//MyPreference Fields
	'Role'=>'Vaidmuo ',
	'Admin'=>'administratorius',
	'User Name'=>'Vartotojo vardas',
	'Default Activity View'=>'Numatytoji veiklų peržiūra',
	'Default Lead View'=>'Numatytoji galimo kliento peržiūra',
	'Title'=>'Pavadinimas',
	'Office Phone'=>'Ofiso telefonas',
	'Department'=>'Skyrius',
	'Reports To'=>'Ataskaita pagal',
	'Yahoo id'=>'Yahoo ID',
	'Home Phone'=>'Namų telefonas',
	'User Image'=>'Įkelti nuotrauką',
	'Date Format'=>'Datos formatas',
	'Tag Cloud'=>'Žymių debesis',
	'Signature'=>'Parašas',
	'Street Address'=>'Gatvė',
	'Password'=>'Slaptažodis',
	'Confirm Password'=>'Patvirtinti slaptažodį',
	'LBL_SHOWN'=>'Rodyta',
	'LBL_HIDDEN'=>'Paslėpta',
	'LBL_SHOW'=>'Rodyti',
	'LBL_HIDE'=>'Slėpti  ',
	'LBL_HOME_PAGE_COMPO'=>'Pradinio puslapio komponentai',
	'LBL_LOGIN_HISTORY'=>'Prisijungimų registras',
	'LBL_USERDETAIL_INFO'=>'Peržiūrima vartotojo išsami informacija',
	'LBL_DELETE_GROUP'=>'Pašalinti grupę',
	'LBL_DELETE_GROUPNAME'=>'Šalinamos grupės',
	'LBL_TRANSFER_GROUP'=>'Perkelti savininkystę:',
	'LBL_DELETE_USER'=>'Vartotojai, kurie bus pašalinti',
	'LBL_TRANSFER_USER'=>'Perkelti savininkystę vartotojui',
	'LBL_DELETE_PROFILE'=>'Pašalinti profilį',
	'LBL_TRANSFER_ROLES_TO_PROFILE'=>'Perkelti vaidmenis profiliui',
	'LBL_PROFILE_TO_BE_DELETED'=>'Šalinamas profilis',
	'INTERNAL_MAIL_COMPOSER'=>'Vidinė laiškų rašyklė',
	'Asterisk Extension'=>'Žvaigždutės plėtinys',
	' Receive Incoming Calls'=>'Priimti įeinančiuosius skambučius',
	'Webservice Access Key'=>'Prieigos raktas',
	'Language'=>'Kalba',
	'Theme'=>'Tema',
	'Time Zone'=>'Laiko juosta',
	'Decimal Separator'=>'Dešimtainis skirtukas',
	'Digit Grouping Pattern'=>'Skaitmenų grupavimo šablonas',
	'Digit Grouping Separator'=>'Skaitmenų grupavimo skirtukas',
	'Symbol Placement'=>'Simbolio vieta',
	'Number Of Currency Decimals'=>'Valiutos skaitmenų po kablelio skaičius',
	'Truncate Trailing Zeros'=>'Trumpinti gale esančius nulius',
	'Default Call Duration'=>'Numatytoji skambučio trukmė (minutėmis)',
	'Other Event Duration'=>'Kito įvykio trukmė (minutėmis)',
	'Calendar Hour Format'=>'Kalendoriaus valandų formatas',
	'Tag Cloud'=>'Žymių debesis',

	//Time zones-Dont change any value
    'Kwajalein'=>'(UTC)-12:00) Tarptautinė datos linija',
    'Pacific/Midway'=>'(UTC)-11:00) Koordinuotas universalus laikas',
    'Pacific/Samoa'=>'(UTC)-11:00) Samoa',
    'Pacific/Honolulu'=>'(UTC)-10:00) Havajai',
    'America/Anchorage'=>'(UTC)-09:00) Aliaska',
    'America/Los_Angeles'=>'(UTC)-08:00) Ramiojo vandenyno laikas (JAV, Kanada)',
    'America/Tijuana'=>'(UTC)-08:00) Tichuana, Žemutinė Kalifornija',
    'America/Denver'=>'(UTC)-07:00) Kalnų laikas (JAV, Kanada)',
    'America/Chihuahua'=>'(UTC)-07:00) Čihuahua, La Paz',
    'America/Mazatlan'=>'(UTC)-07:00) Mazatlanas',
    'America/Phoenix'=>'(UTC)-07:00) Arizona',
    'America/Regina'=>'(UTC)-06:00) Saskačevanas',
    'America/Tegucigalpa'=>'(UTC)-06:00) Centrinė Amerika',
    'America/Chicago'=>'(UTC)-06:00) Centrinis laikas (JAV, Kanada)',
    'America/Mexico_City'=>'(UTC)-06:00) Mieksikas',
    'America/Monterrey'=>'(UTC)-06:00) Monterėjus',
    'America/New_York'=>'(UTC)-05:00) Rytinis laikas (JAV, Kanada)',
    'America/Bogota'=>'(UTC)-05:00) Bogota, Lima, Kitas',
    'America/Lima'=>'(UTC)-05:00) Lima',
    'America/Rio_Branco'=>'(UTC)-05:00) Rio Branko',
    'America/Indiana/Indianapolis'=>'(UTC)-05:00) Indiana (Rytinė)',
    'America/Caracas'=>'(UTC)-04:30) Karakas',
    'America/Halifax'=>'(UTC)-04:00) Atlantas (Kanada)',
    'America/Manaus'=>'(UTC)-04:00) Manausas',
    'America/Santiago'=>'(UTC)-04:00) Santjagas',
    'America/La_Paz'=>'(UTC)-04:00) La Paz',
    'America/Cuiaba'=>'(UTC)-04:00) Kujaba',
    'America/Asuncion'=>'(UTC)-04:00) Asunsjonas',
    'America/St_Johns'=>'(UTC)-03:30) Niufaundlendas',
    'America/Argentina/Buenos_Aires'=>'(UTC)-03:00) Buenos Aires',
    'America/Sao_Paulo'=>'(UTC)-03:00) Brazilija',
    'America/Godthab'=>'(UTC)-03:00) Grenlandija',
    'America/Montevideo'=>'(UTC)-03:00) Montevidėjas',
    'Atlantic/South_Georgia'=>'(UTC)-02:00) Vidurio atlantas',
    'Atlantic/Azores'=>'(UTC)-01:00) Azorai',
    'Atlantic/Cape_Verde'=>'(UTC)-01:00) Žaliojo kyšulio sala',
    'Europe/London'=>'(UTC) Londonas, Edinburgas, Dublinas, Lisabona',
    'UTC'=>'(UTC) Grinvičas (koordinuotas universalus laikas)',
    'Africa/Monrovia'=>'(UTC) Monrovija, Reikjavikas',
    'Africa/Casablanca'=>' (UTC) Kasablanka',
    'Europe/Belgrade'=>'(UTC)+01:00) Belgradas, Bratislava, Budapeštas, Liublijana, Praha',
    'Europe/Sarajevo'=>'(UTC)+01:00) Sarajevas, Skopjė, Varšuva, Zagrebas',
    'Europe/Brussels'=>'(UTC)+01:00) Briuselis, Kopenhaga, Madridas, Paryžius',
    'Africa/Algiers'=>'(UTC)+01:00) ',
    'Europe/Amsterdam'=>'(UTC)+01:00) Amsterdamas, Berlynas, Bernas, Roma, Stokholmas, Viena',
    'Europe/Minsk'=>'(UTC)+02:00) Minskas',
    'Africa/Cairo'=>'(UTC)+02:00) Kairas',
    'Europe/Helsinki'=>'(UTC)+02:00) Helsinkis, Ryga, Sofija, Talinas, Vilnius',
    'Europe/Athens'=>'(UTC)+02:00) Atėnai, Bukareštas',
    'Europe/Istanbul'=>'(UTC)+02:00) Istanbulas',
    'Asia/Jerusalem'=>'(UTC)+02:00) Jeruzalė',
    'Asia/Amman'=>'(UTC)+02:00) Amanas',
    'Asia/Beirut'=>'(UTC)+02:00) Beirutas',
    'Africa/Windhoek'=>'(UTC)+02:00) Vindhokas',
    'Africa/Harare'=>'(UTC)+02:00) Hararė',
    'Asia/Kuwait'=>'(UTC)+03:00) Kuveitas, Riadas',
    'Asia/Baghdad'=>'(UTC)+03:00) Bagdadas',
    'Africa/Nairobi'=>'(UTC)+03:00) Nairobis',
    'Asia/Tehran'=>'(UTC)+03:30) Teheranas',
    'Asia/Tbilisi'=>'(UTC)+04:00) Tbilisis',
    'Europe/Moscow'=>'(UTC)+04:00) Maskva, Volgogradas',
    'Asia/Muscat'=>'(UTC)+04:00) Abu Dabis, Muskatas',
    'Asia/Baku'=>'(UTC)+04:00) Baku',
    'Asia/Yerevan'=>'(UTC)+04:00) Jerevanas',
    'Asia/Karachi'=>'(UTC)+05:00) Islamabadas, Karachis',
    'Asia/Tashkent'=>'(UTC)+05:00) Taškentas',
    'Asia/Kolkata'=>'(UTC)+05:30) Čenajus, Kolkata, Mumbajus, Naujasis Delis',
    'Asia/Colombo'=>'(UTC)+05:30) Sri Jayawardenepura',
    'Asia/Katmandu'=>'(UTC)+05:45) Katmandu',
    'Asia/Dhaka'=>'(UTC)+06:00) Daka',
    'Asia/Almaty'=>'(UTC)+06:00) Almata',
    'Asia/Yekaterinburg'=>'(UTC)+06:00) Jekaterinburgas',
    'Asia/Rangoon'=>'(UTC)+06:30) Rangūnas',
    'Asia/Novosibirsk'=>'(UTC)+07:00) Novosibirskas',
    'Asia/Bangkok'=>'(UTC)+07:00) Bankokas, Džakarta',
    'Asia/Brunei'=>'(UTC)+08:00) Beijingas, Honkongas',
    'Asia/Krasnoyarsk'=>'(UTC)+08:00) Krasnojarskas',
    'Asia/Ulaanbaatar'=>'(UTC)+08:00) Ulan Batoras',
    'Asia/Kuala_Lumpur'=>'(UTC)+08:00) Kvala Lumpūras, Singapūras',
    'Asia/Taipei'=>'(UTC)+08:00) Taipėjus',
    'Australia/Perth'=>'(UTC)+08:00) Pertas',
    'Asia/Irkutsk'=>'(UTC)+09:00) Irkutskas',
    'Asia/Seoul'=>'(UTC)+09:00) Seulas',
    'Asia/Tokyo'=>'(UTC)+09:00) Tokijus',
    'Australia/Darwin'=>'(UTC)+09:30) Darvinas',
    'Australia/Adelaide'=>'(UTC)+09:30) Adelaida',
    'Australia/Canberra'=>'(UTC)+10:00) Kanbera, Melburnas, Sidnėjus',
    'Australia/Brisbane'=>'(UTC)+10:00) Brisbanė',
    'Australia/Hobart'=>'(UTC)+10:00) Hobartas',
    'Asia/Vladivostok'=>'(UTC)+10:00) Vladivostokas',
    'Pacific/Guam'=>'(UTC)+10:00) Guamas, Port Morzbis',
    'Asia/Yakutsk'=>'(UTC)+10:00) Jakutskas',
    'Pacific/Fiji'=>'(UTC)+12:00) Fidžis',
    'Asia/Kamchatka'=>'(UTC)+12:00) Kamčiatka',
    'Pacific/Auckland'=>'(UTC)+12:00) Auklandas',
    'Asia/Magadan'=>'(UTC)+12:00) Magadanas',
    'Pacific/Tongatapu'=>'(UTC)+13:00) Nukualofa',

	'Summary'=>'Santrauka',
	'Detail'=>'Išsami informacija',
	'LBL_USER_LIST_DETAILS'=>'Išsami informacija',
	
	'LBL_OLD_PASSWORD'=>'Senasis slaptažodis:',
	'LBL_CHANGE_PASSWORD'=>'Pakeisti slaptažodį',
	'LBL_NEW_PASSWORD'=>'Naujas slaptažodis:',
	'LBL_CONFIRM_PASSWORD'=>'Patvirtinti slaptažodį:',
	
	//Login strings
	'LBL_TO_CRM'=>'Prisijungti prie Vtiger sistemos',
	'LBL_INVALID_USER_OR_PASSWORD'=>'Netinkamas vartotojas arba slaptažodis',
	'LBL_INVALID_USER_OR_EMAIL'=>'Netinkamas vartotojas arba el. pašto adresas.',
	'LBL_EMAIL_SEND'=>'Jums buvo išsiųstas slaptažodžio keitimo laiškas',
	'ForgotPassword'=>'Pamiršau slaptažodį',
	'LBL_CONNECT_WITH_US'=>'Susisiekite su mumis',
	'LBL_GET_MORE'=>'Gauti daugiau iš programos Vtiger',
	
	'LBL_TRANSFER_RECORDS_TO_USER'=>'Perkelti įrašus vartotojui',
	'LBL_USER_TO_BE_DELETED'=>'Vartotojai, kurie bus pašalinti',
);

$jsLanguageStrings = array(
	'JS_ENTER_OLD_PASSWORD'=>'Įveskite senąjį slaptažodį.',
	'JS_ENTER_NEW_PASSWORD'=>'Įveskite naują slaptažodį.',
	'JS_ENTER_CONFIRMATION_PASSWORD'=>'Pakartotinai įveskite slaptažodį.',
	'JS_REENTER_PASSWORDS'=>'Pakartotinai įveskite slaptažodžius, nes naujas ir senasis slaptažodžiai nesutampa.. ',
	'JS_INVALID_PASSWORD'=>'urite pasirinkti galiojantį vartotojo vardą ir slaptažodį.',
	'JS_PASSWORD_CHANGE_FAILED_1'=>'Varotojo slaptažodžio keitimas nepavyko',
	'JS_PASSWORD_CHANGE_FAILED_2'=>'nepavyko. Įveskite kitą slaptažodį.',
	'JS_PASSWORD_INCORRECT_OLD'=>'Neteisingai nurodytas senas slaptažodis. Įrašykite dar kartą.',
);
