<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is: vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(

	// Footer
	'APPTITLE' => 'Vtiger KVS',
	'POWEREDBY'=> 'Veikia „Vtiger CRM“ pagrindu',
	'LBL_READ_LICENSE' => 'Skaityti licenciją',
	'LBL_PRIVACY_POLICY' => 'Privatumo politika',

	// Common Actions
	'LBL_NEW' => 'Naujas',
	'LBL_LINKED' => 'Susietas',
	'LBL_SELECT_ALL' => 'Pasirinkti viską –',
	'LBL_SELECT_TO_LOAD_LIST' => 'Jei norite įkelti sąrašą, pasirinkite',
	'LBL_CREATING_NEW' => 'Kuriamas naujas įrašas –',
	'LBL_ADDING_NEW' => 'Pridedamas naujas įrašas –',
	'LBL_EDITING' => 'Redagavimas:',
	'LBL_SAVE' => 'Įrašyti',
	'LBL_CANCEL' => 'Atsisakyti',
	'LBL_BACK' => 'Atgal',
	'LBL_IMPORT' => 'Importuoti',
	'LBL_EXPORT' => 'Eksportuoti',
	'LBL_FIND_DUPLICATES' => 'Rasti dublikatus',
	'LBL_MORE' => 'Daugiau',
	'LBL_LESS' => 'Mažiau',
	'LBL_ACTIONS' => 'Veiksmai',
	'LBL_ADD' => 'Pridėti',
	'LBL_EDIT' => 'Redaguoti',
	'LBL_DELETE' => 'Šalinti',
	'LBL_COMMENT' => 'Komentaras',
	'LBL_STARRED' => 'Nebesekti',
	'LBL_NOT_STARRED' => 'Spauskite čia norėdami sekti',
	'LBL_QUICK_VIEW' => 'Greita peržiūra',
	'LBL_NOTIFICATION_CENTER' => 'Pranešimų centras',
	'LBL_NOTIFICATION' => 'Notification',
	'LBL_STARRED_RECORD_TO' => '%s to %s',
	'LBL_STARRED_RECORD_UPDATED' => '%s updated %s',
	'LBL_SETTINGS'=> 'Nuostatos',
	'LBL_ADD_COMMENT' => 'Pridėti pastabą',
	'LBL_EDIT_FIELDS' => '%s laukai ir išdėstymas',
	'LBL_EDIT_WORKFLOWS' => '%s darbo procesai',
	'LBL_EDIT_PICKLIST_VALUES' => 'Parinkčių sąrašo reikšmės',
	'LBL_EDIT_MAILSCANNER' => 'Laiškų keitiklis',
	'LBL_RECORD_DELETE' => 'Įrašas, kurį norite peržiūrėti, pašalintas.',
	'LBL_RECORD_NOT_FOUND' => 'Įrašas, kurį norite pasiekti, nerastas',
	'LBL_EDIT_REASON' => 'Redagavimo priežastis',
	//'LBL_EDIT_CURRENT_FILTER' => 'Redaguoti dabartinį filtrą',
	//'LBL_DELETE_CURRENT_FILTER' => 'Ištrinti dabartinį filtrą',
	'LBL_SELECT' => 'Pasirinkite',
	'LBL_CLEAR' => 'Išvalyti',
	'LBL_YES' => 'Taip',
	'LBL_NO' => 'Ne',
	'LBL_SHOW_COMPLETE_DETAILS' => 'Išsami informacija',
	'LBL_MINILIST_FIELDS_ARE_NOT_AVAILABLE_FOR_YOU' => 'Apgailestaujame! Mažojo sąrašo laukai jums nepasiekiami.',
	'LBL_MASS_EDITING' => 'Dauginis redagavimas',
	'LBL_DESELECT_ALL_RECORDS' => 'Nužymėti įrašus visuose puslapiuose',
	'LBL_QUICK_CREATE' => 'Greitasis kūrimas',
	'LBL_QUICK_EDIT' => 'Greitasis redagavimas',
	'LBL_SEND_EMAIL' => 'Siųsti laišką  ',
	//SEND EMAIL translations
	'LBL_ALL_EMAILS' => 'Visos el. pašto paskyros',
	'LBL_MUTIPLE_EMAIL_SELECT_ONE' => 'Pasirinkite vieną iš toliau pateiktų parinkčių',
	//SEND EMAIL translations
	'LBL_GO_TO_FULL_FORM' => 'Eiti į išsamią formą',
	'LBL_SEND_SMS' => 'Siųsti žinutę',
	'LBL_FOUND' => 'nerasti',
	'LBL_CLICK_ADD' => 'Spauskite čia norėdami pridėti',
	'LBL_ADD_MORE_FIELDS' => 'Pridėti daugiau laukų',
	'LBL_ADD_NOTE' => 'Pridėti dokumentą',
	'LBL_CREATE_NEW' => 'Kurti naują',
	'LBL_ADD_EVENT' => 'Pridėti įvykį',
	'LBL_ADD_TASK' => 'Pridėti užduotį',
	'LBL_MARKETING_AND_SALES' => 'RINKODARA IR PARDAVIMAI',
	'LBL_TOOLS_HEADER' => 'ĮRANKIAI',
	'LBL_SUPPORT' => 'APTARNAVIMAS',
	'LBL_INVENTORY' => 'INVENTORIUS',
	'LBL_ANALYTICS' => 'ANALIZĖ',
	'LBL_CONTACT' => 'ADRESATŲ VALDYMAS',
	'LBL_HOME' => 'Pradžia',
	'LBL_NO_ATTACHMENTS' => 'Nėra priedų',
	'LBL_COMPOSE_EMAIL_WARNING' => 'Įspėjimas: jūsų el. laiškas gali būti nukreipti į šlamštą. Pridėkite  „Vtiger“ kaip savo domeno įgaliotą siuntėją. Sužinokite daugiau',
	// Common Link Labels
	'LBL_REARRANGE_DASHBOARD_TABS' => 'Pertvarkyti stulpelius',
	'LBL_DONE' => 'Užbaigta',
	'LBL_DELETE_DASHBOARD_TAB' =>'Pašalinti stulpelį',
	'LBL_DASHBOARD_TAB_ALREADY_EXIST' => 'Toks stulpelis jau egzistuoja',
	'LBL_TABS_LIMIT_EXCEEDED' => 'Apgailestaujame!  Negalite pridėti daugiau nei 10 stulpelių',
	'LBL_TODOS' => 'Užduotys',
	'LBL_LAST_VIEWED_RECORDS' => 'Paskiausiai peržiūrėti įrašai',
	'LBL_DASHBOARD' => 'Skydelis',
	'LBL_USER_SETTINGS' => 'Naudotojo nuostatos',
	'LBL_MY_PREFERENCES' => 'Mano nuostatos',
	'LBL_SIGN_OUT' => 'Atsijungti',
	'LBL_HELP' => 'Pagalba',
	'LBL_DOCUMENTATION' => 'Dokumentacija',
	'LBL_VIDEO_TUTORIAL' => 'Video vadovėlis',
	'LBL_FEEDBACK' => 'Atsiliepimai',
	'LBL_CHAT_SUPPORT'=>'Pagalba tiesioginiu pokalbiu',
	'LBL_CRM_SETTINGS' => 'CRM nuostatos',
	'LBL_ON_DEMAND_ADMIN' => 'Pridėti / šalinti naudotojus',
	'LBL_ANNOUNCEMENT' => 'Pranešimas',
	'LBL_CALENDAR' => 'Kalendorius',
	'LBL_POST' => 'Išsiųsti',
	'LBL_GUIDER' => 'Vedlys',
	'LBL_VIDEOS' => 'Vaizdo klipai',
	'LBL_DISPLAY_TYPE' => 'Rodinio tipas',
	'LBL_DISPLAY_WIDETYPE' => 'Platus',
	'LBL_DISPLAY_MEDIUMTYPE' => 'Vidutinis',
	'LBL_DISPLAY_NARROWTYPE' => 'Siauras',
	'LBL_TAG_THIS_RECORD' => 'Pažymėti šį įrašą',
	'LBL_SAME_TAG_EXISTS' => 'Tokia pati žyma egzistuoja',
	'LBL_MAKE_PUBLIC' => 'Paviešinti',
	'LBL_PAGE' => 'Psl.',
	'LBL_LISTVIEW_PAGE_JUMP' => 'Šokti į kitą puslapį',
	'LBL_LISTVIEW_JUMP_TO' => 'Jump To',
	'LBL_PROFILE_PASSWORD' => 'Profilis / slaptažodis',
	'LBL_INFO' => 'Info',
	'LBL_CANT_MOVE_FROM_PUBLIC_TO_PRIVATE' => 'Negalima perkelti iš viešos žymos į privačią žymą',
	'LBL_EDIT_TAG'=>'Redaguoti žymą',
	'LBL_NO_TAG_EXISTS' => 'Žymų nėra' ,
	'LBL_RELATED_USERS' => 'Susiję vartotojai',

	// Common Fields
	'LBL_USER' => 'Naudotojas',
	'LBL_GROUP' => 'Grupė',
	'Last Modified By' => 'Paskutinį kartą keitė',
	'Created Time' => 'Sukūrimo laikas',
	'Modified Time' => 'Pakeitimo laikas:',
	'Description' => 'Aprašymas',
	'Assigned To'=>'Priskirtas asmuo',

	//Loading Labels
	'LBL_LOADING' => 'Įkeliama',
	'LBL_LOADING_WIDGET' => 'Įkeliamas valdiklis',
	'LBL_LOADING_LISTVIEW_CONTENTS'	=> 'Įkeliama, prašome palaukti.',

	// Detail View
	'LBL_HISTORY' => 'Žurnalas',
	'LBL_UPDATES' => 'Atnaujinimai',
	'LBL_SHOW_FULL_DETAILS' => 'Rodyti išsamią informaciją',
	'LBL_SUMMARY_DETAILS' => 'Santraukos informacija',
	'LBL_ADD_NEW_COMMENT' =>'Pridėti naują pastabą',
	'LBL_NO_UPDATES' => 'Atnaujinimų nėra',
	'LBL_ACTIVITIES' => 'Veiklos',
	'LBL_NO_PENDING_ACTIVITIES' => 'Laukiančių veiklų nėra',
	'LBL_SUMMARY' => 'Santrauka',
	'LBL_KEY_FIELD' => 'Pagrindinis laukas',
	'LBL_DETAILS' => 'Išsami informacija',
	'LBL_NAME_EMAIL' => 'Vardas ir el. paštas',

	// Popup window
	'LBL_SEARCH_FOR' => 'Ieškoti',
	'LBL_IN' => 'tarp ',
	'LBL_TYPE_SEARCH' => 'Rašykite, jei norite ieškoti',
	'LBL_SEARCH_BUTTON' => 'Ieškoti',
	'LBL_ADVANCE_SEARCH' => 'Išplėstinė paieška',
	'LBL_LOADING_PLEASE_WAIT' => 'Įkeliama, prašome palaukti.',
	'LBL_PLEASE_SELECT_MODULE' => 'Pasirinkite modulį paieškai',

	//DropDown Category
	'LBL_USERS' => 'Naudotojai',
	'LBL_GROUPS' => 'Grupės',

	//EditView Form Links
	'LBL_FULL_FORM' => 'Išsami forma',
	'LBL_SIMPLE_FORM' => 'Paprasta forma',

	//Recent Comments
	'LBL_IS_REMOVED' => 'pašalintas',
	'LBL_ADD_YOUR_COMMENT_HERE' => 'Pridėkite savo pastabą čia…',
	'LBL_REASON_FOR_CHANGING_COMMENT' => 'Pastabos keitimo priežastis',
	'LBL_REPLY' => 'Atsakyti',
	'LBL_VIEW_THREAD' => 'Peržiūrėti giją',
	'LBL_NO_COMMENTS' => 'Pastabų nėra',
	'LBL_REPLIES' => 'atsakymai',
	'LBL_REPLY_ALL' => 'Atsakyti visiems',
	'LBL_INTERNAL_COMMENT_TOOTLTIP' => 'Customers cannot see this comment',
	'LBL_EXTERNAL_COMMENT_TOOTLTIP' => 'Customers might see this comment via notifications or customer portal',

	//Translation for all modules
	'Accounts' => 'Organizacijos',
	'Assets' => 'Įranga',
	'Calendar' => 'Kalendorius',
	'Campaigns' => 'Kampanijos ',
	'Contacts' => 'Adresatai',
	'Documents' => 'Dokumentai',
	'Leads' => 'Užklausos',
	'ModComments' => 'Pastabos',
	'Potentials' => 'Galimybės',
	'PriceBooks' => 'Kainynai',
	'Products' => 'Prekės',
	'Project' => 'Projektai',
	'ProjectMilestone' => 'Projekto etapai',
	'ProjectTask' => 'Projekto užduotys',
	'ServiceContracts' => 'Paslaugų sutartys',
	'Services' => 'Paslaugos',
	'Vendors' => 'Tiekėjai',
	'Rss' => 'RSS',
	'Quotes'=>'Pasiūlymai ',
	'PurchaseOrder'=>'Pirkimo užsakymas',
	'SalesOrder'=>'Pardavimo užsakymas',
	'Invoice'=>'Sąskaitos faktūros',
	'MailManager' => 'Laiškų tvarkytuvė',
	'Activities' => 'Veiklos',
	'Portal' => 'Mūsų svetainės',
	'Email Templates' => 'El. laiškų šablonai',
	'Recycle Bin' => 'Šiukšlinė',

	//Basic String Translation
	'LBL_ADD_RECORD' => 'Pridėti įrašą',
	'LBL_RECENTLY_MODIFIED' => 'Neseniai pakeista',
	'LBL_RECORDS_LIST' => 'Įrašų sąrašas',
	'LBL_RECORD_SUMMARY' => 'Modulio santrauka',
	'LBL_RECORD_SUMMARY' => 'Modulio santrauka',
	'LBL_ACCESS_DENIED_FOR' => 'Prieiga negalima',
	'LBL_GO_BACK' => 'Grįžti atgal',
	'LBL_NO_DATA_AVAILABLE' => 'Prieinamų duomenų nėra',

	// Global Search
	'LBL_GLOBAL_SEARCH' => 'Įrašykite raktinį žodį ir spustelėkite klavišą Įvesti (Enter)',
	'LBL_ALL_RECORDS' => 'Visi įrašai',
	'LBL_NO_RECORDS_FOUND' => 'Įrašų nerasta',

	//Filters & Advance Filter
	'LBL_AND' => 'ir',
	'LBL_OR' => 'arba',
	'LBL_APPLBL_NONEROVE' => 'Patvirtinti',
	'LBL_DENY' => 'Atmesti  ',
	'LBL_EQUALS' => 'lygu',
	'LBL_NOT_EQUAL_TO' => 'nelygu',
	'LBL_STARTS_WITH' => 'prasideda simboliais',
	'LBL_ENDS_WITH' => 'baigiasi simboliais',
	'LBL_CONTAINS' => 'turi simbolius',
	'LBL_DOES_NOT_CONTAIN' => 'Neturi',
	'LBL_LESS_THAN' => 'mažiau nei',
	'LBL_GREATER_THAN' => 'daugiau nei',
	'LBL_LESS_THAN_OR_EQUAL' => 'mažiau arba lygu',
	'LBL_GREATER_OR_EQUAL' => 'daugiau arba lygu',
	'LBL_BEFORE' => 'prieš',
	'LBL_AFTER' => 'po',
	'LBL_BETWEEN' => 'tarp',
	'LBL_SEARCH' => 'Ieškoti',
	'LBL_SEARCH_IN' => 'Ieškoti tarp',
	'LBL_ADD_CONDITION' => 'Pridėti sąlygą',
	'LBL_ADD_GROUP' => 'Pridėti sąlygos grupę',
	'LBL_FILTER_CONDITIONS' => 'Rodyti sąlygas',
	'LBL_ALL_CONDITIONS' => 'Visos sąlygos',
	'LBL_ALL_CONDITIONS_DESC' => 'Visos sąlygos turi būti tenkinamos',
	'LBL_ANY_CONDITIONS' => 'Bet kuri sąlyga',
	'LBL_ANY_CONDITIONS_DESC' => 'Bent viena sąlyga turi būti tenkinama',
	'LBL_SELECT_FIELD' => 'Pasirinkite lauką',
	'LBL_SELECT_MODULE' => 'Pasirinkite modulį',
	'LBL_CREATE_NEW_FILTER' => 'Sukurti naują sąrašą',
	'All' => 'Visi įrašai –',
	'Others' => 'Kiti ',
	'Pending' => 'Laukiama',
	'Public' => 'Viešas',

	//Advance Search
	'LBL_SAVE_FILTER' => 'Išsaugoti sąrašą',
	'LBL_SAVE_MODIFY_FILTER' => 'Įrašyti/keisti paiešką',
	'LBL_SEARCH_RESULTS' => 'Paieškos rezultatai',
	'LBL_SAVE_AS_FILTER' => 'Išsaugoti kaip sąrašą',

	//Exception String Translation
	'LBL_NOT_ACCESSIBLE' => 'Prieiga negalima',

	//Line Items
	'LBL_ITEM_DETAILS'=> 'Elemento išsami informacija',
	'LBL_CURRENCY' => 'Valiuta',
	'LBL_TAX_MODE' => 'Mokesčių skaičiavimas',
	'LBL_INDIVIDUAL' => 'Atskirai',
	'LBL_GROUP' => 'Grupė',
	'LBL_TOOLS' => 'Įrankiai',
	'LBL_ITEM_NAME' => 'Elemento pavadinimas',
	'LBL_QTY_IN_STOCK' => 'Sandėlys',
	'LBL_QTY' => 'Kiekis',
	'LBL_LIST_PRICE' => 'Pardavimo kaina',
	'LBL_TOTAL' => 'Suma',
	'LBL_NET_PRICE' => 'Tarpinė suma',
	'LBL_DISCOUNT' => 'Nuolaida',
	'LBL_TOTAL_AFTER_DISCOUNT' => 'Suma po nuolaidų',
	'LBL_TAX' => 'Mokestis',
	'LBL_ADD_PRODUCT' => 'Pridėti prekę',
	'LBL_ADD_SERVICE' => 'Pridėti paslaugą',
	'LBL_LI_ADD_PRODUCT' => 'Produktas',
	'LBL_LI_ADD_SERVICE' => 'Paslauga',
	'LBL_ITEMS_TOTAL' => 'Eilučių suma',
	'LBL_SHIPPING_AND_HANDLING_CHARGES' => 'Pristatymo ir tvarkymo mokesčiai',
	'LBL_PRE_TAX_TOTAL' => 'Suma be mokesčių',
	'LBL_TAX_FOR_SHIPPING_AND_HANDLING' => 'Pristatymo ir tvarkymo mokesčiai',
	'LBL_SET_SHIPPING_AND_HANDLING_TAXES_FOR' => 'Nustatyti gabenimo ir tvarkymo mokesčius',
	'LBL_ADJUSTMENT' => 'Patikslinimas',
	'LBL_DEDUCT' => 'Atimti',
	'LBL_GRAND_TOTAL' => 'Galutinė suma',
	'LBL_ZERO_DISCOUNT' => 'Nuolaidos nėra',
	'LBL_OF_PRICE' => 'Kaina',
	'LBL_DIRECT_PRICE_REDUCTION' => 'Tiesiogiai sumažinti kainą',
	'LBL_SET_DISCOUNT_FOR' => 'Nustatyti nuolaidą',
	'LBL_STOCK_NOT_ENOUGH' => 'Nepakanka sandėlyje',
	'LBL_MAX_QTY_SELECT' => 'Didžiausia reikšmė yra',
	'LBL_DRAG' => 'Vilkti',
	'LBL_TOTAL_TAX_AMOUNT' => 'Mokesčių suma',
	'LBL_DIRECT_AMOUNT_DISCOUNT' => 'Tiesioginė nuolaida',
	'LBL_FINAL_DISCOUNT_AMOUNT' => 'Galutinės nuolaidos suma',
	'LBL_MORE_CURRENCIES' => 'daugiau valiutų',
	'LBL_SET_TAX_FOR' => 'Nustatyti mokestį',
	'LBL_GROUP_TAX' => 'Grupės mokestis',
	'LBL_BILLING_ADDRESS_FROM' => 'Kopijuoti sąskaitų siuntimo adresą iš',
	'LBL_SHIPPING_ADDRESS_FROM' => 'Kopijuoti pristatymo adresą iš',
	'LBL_COPY_SHIPPING_ADDRESS' => 'Pristatymo adresas',
	'LBL_COPY_BILLING_ADDRESS' => 'Sąskaitų siuntimo adresas',
	'LBL_OVERALL_DISCOUNT' => 'Bendra nuolaida',
	'LBL_CHARGES' => 'Rinkliava',
	'LBL_CHARGES_TOTAL' => 'Rinkliava iš viso',
	'LBL_TAXES_ON_CHARGES' => 'Mokesčiai rinkliavai',
	'LBL_DEDUCTED_TAXES' => 'Atskaičiuoti mokesčiai',
	'LBL_DEDUCTED_TAXES_TOTAL' => 'Atskaičiuoti mokesčiai iš viso',
	'LBL_DEFAULT' => 'Numatytas',
	'LBL_ITEM' => 'Prekė',
	'LBL_ADD_DASHBOARD' =>'Pridėti skydelį',

	//DetailView Actions
	'LBL_CREATE' => 'Kurti',
	'LBL_GENERATE' => 'Generuoti',
	'LBL_DUPLICATE' => 'Dubliuoti',
	'Add Note' => 'Pridėti dokumentą',

	//Dashboard String
	'LBL_ADD_WIDGET' => 'Pridėti valdiklį',
	'LBL_COMMENTS' => 'Pastabos',
	'LBL_REFRESH' => 'Atšviežinti',
	'LBL_CLOSE' => 'Užverti',
	'LBL_ALL' => 'Visi',
	'LBL_UPDATED' => 'atnaujintas',
	'LBL_VIA_TASK' => 'per užduotį',
	'LBL_form' => 'nuo',
	'LBL_FROM' => 'Nuo',
	'LBL_TO' => 'į',
	'LBL_to' => 'į',
	'LBL_ON' => ' ',
	'LBL_OF' => 'iš',
	'LBL_BY' => 'sukūrė',
	'LBL_ADDED' => 'pridėjo',
	'LBL_FOR' => 'for',
	'LBL_CREATED' => 'sukurta',
	'LBL_DELETED' => 'pašalinta',
	'LBL_RESTORED' => 'atstatyta',
	'LBL_COMMENTED' => 'pakomentavo',
	'LBL_REMOVED' => 'pašalinta',
	'LBL_REMOVE' => 'Šalinti',
	'LBL_AT' => ' ',
	'LBL_MINE' => 'Mano',
	'LBL_ME' => 'Mane',
	'History' => 'Žurnalas',
	'Upcoming Tasks' => 'Būsimos užduotys',
	'LBL_YEAR' => 'm.',
	'LBL_YEARS' => 'm.',
	'LBL_MONTH' => 'mėn.',
	'LBL_MONTHS' => 'mėn.',
	'LBL_DAY' => 'diena',
	'LBL_DAYS' => 'd.',
	'LBL_DAY(S)' => 'diena(-os)',
	'LBL_HOUR' => 'val.',
	'LBL_HOURS' => 'val.',
	'LBL_HOUR(S)' => 'valanda(-os)',
	'LBL_MINUTE' => 'min.',
	'LBL_MINUTES' => 'min.',
	'LBL_SECOND' => 'sek.',
	'LBL_SECONDS' => 'sek.',
	'LBL_JUSTNOW' => 'ką tik',
	'LBL_CUSTOM_INFORMATION' => 'Papildoma informacija',
	'LBL_NO_RECENT_UPDATES' => 'Paskiausių pokyčių nėra',
	'LBL_NO_DATA' => 'Duomenų nėra',
	'LBL_PERMISSION_DENIED' => 'Prieiga negalima',
	'LBL_HANDLER_NOT_FOUND' => 'Nerasta, kuo apdoroti užklausą',
	'LBL_FILTER' => 'Sąrašas',
	'LBL_DUE' => 'įsipareigota iki',
	'LBL_DAYS' => 'd.',
	'LBL_COMPLETED' => 'Užbaigtas',
	'LBL_AGO' => 'prieš',
	'LBL_CHANGED' => 'pakeista',
	'SINGLE_Users' => 'Vartotojas',
	'LBL_MATCHED_THIS_CRITERIA'=> 'neatitiko šio kriterijaus',
	'LBL_NO_SCHEDULED_ACTIVITIES' => 'Suplanuotų veiklų nėra',
	'LBL_NO_OVERDUE_ACTIVITIES' => 'Vėluojančių veiklų nėra',
	'LBL_NO_UPDATES_OR_COMMENTS' => 'Atnaujinimų ar pastabų nėra',
	'LBL_MINI_LIST' => 'Mini sąrašas',
	'LBL_NOTEPAD' => 'užrašinę',
	'LBL_NOTEPAD_NAME' => 'Užrašinės pavadinimas',
	'LBL_NOTEPAD_CONTENT' => 'Užrašinės turinys',
	'LBL_LAST_SAVED_ON' => 'Paskutinį kartą įrašyta',
	'Mini List' => 'Mini sąrašas',
	'Notebook' => 'Užrašinė',
	'LBL_RESULT_FOR_THE_TAG' => 'Rezultatai pagal žymę',
	'LBL_ALL_USERS' => 'Visi vartotojai',
	'LBL_BOTH' => 'Abu',
	'LBL_SHOW' => 'Rodyti',
	'LBL_MY' => 'Mano',
	'LBL_SELECT_DATE_RANGE' => 'Pasirinkti datos diapazoną',

	// Basic Strings- custom view
	'LBL_VIEW_NAME' => 'Sąrašo pavadinimas',
	'LBL_CREATE_VIEW' => 'Kuriamas naujas rodinys',
	'LBL_BASIC_DETAILS' => 'Pagrindinė informacija',
	'LBL_CHOOSE_COLUMNS' => 'Pasirinkite stulpelius ir jų tvarką',
	'LBL_MAX_NUMBER_FILTER_COLUMNS' => 'Daugiausiai 15',
	'LBL_FILTER_ON_DATE' => 'Rodyti šiuo laiku',
	'LBL_CHOOSE_FILTER_CONDITIONS' => 'Pasirinkite sąrašo sąlygas',
	'LBL_ADD_CONDITION' => 'Pridėti sąlygą',
	'LBL_SET_AS_DEFAULT' => 'Skirti numatytuoju',
	'LBL_LIST_IN_METRICS' => 'Metrikų sąrašas',
	'LBL_SET_AS_PUBLIC' => 'Nustatyti kaip viešą',
	'LBL_AND' => 'ir',
	'LBL_OR' => 'arba',
	'LBL_ADD_MORE_COLUMNS' => 'Spauskite čia norėdami pasirinkti laukus',
	'LBL_ADD_GROUP' => 'Pridėti sąlygos grupę',

	//DateFilter Conditions
	'LBL_CUSTOM' => 'Tinkintas',
	'LBL_PREVIOUS_FY' => 'Praėję fiskaliniai metai',
	'LBL_CURRENT_FY' => 'Einamieji fiskaliniai metai',
	'LBL_NEXT_FY' => 'Kiti fiskaliniai metai',
	'LBL_PREVIOUS_FQ' => 'Praėjęs fiskalinis ketvirtis',
	'LBL_CURRENT_FQ' => 'Einamasis fiskalinis ketvirtis',
	'LBL_NEXT_FQ' => 'Kitas fiskalinis ketvirtis',
	'LBL_YESTERDAY' => 'Vakar',
	'LBL_TODAY' => 'Šiandien',
	'LBL_TOMORROW' => 'Rytoj',
	'LBL_LAST_WEEK' => 'Praėjusi savaitė',
	'LBL_CURRENT_WEEK' => 'Einamoji savaitė',
	'LBL_NEXT_WEEK' => 'Kita savaitė',
	'LBL_LAST_MONTH' => 'Praėjęs mėnuo',
	'LBL_CURRENT_MONTH' => 'Einamasis mėnuo',
	'LBL_NEXT_MONTH' => 'Kitas mėnuo',
	'LBL_LAST_7_DAYS' => 'Pastarosios 7 dienos',
	'LBL_LAST_14_DAYS' => 'Pastarosios 14 dienų',
	'LBL_LAST_30_DAYS' => 'Pastarosios 30 dienų',
	'LBL_LAST_60_DAYS' => 'Pastarosios 60 dienų',
	'LBL_LAST_90_DAYS' => 'Pastarosios 90 dienų',
	'LBL_LAST_120_DAYS' => 'Pastarosios 120 dienų',
	'LBL_NEXT_30_DAYS' => 'Artimiausios 30 dienų',
	'LBL_NEXT_60_DAYS' => 'Artimiausios 60 dienų',
	'LBL_NEXT_90_DAYS' => 'Artimiausios 90 dienų',
	'LBL_NEXT_120_DAYS' => 'Artimiausios 120 dienų',

	//advanced Filter Options
	'LBL_NONE' => '—',
	'LBL_EQUALS' => 'lygu',
	'LBL_NOT_EQUAL_TO' => 'nelygu',
	'LBL_STARTS_WITH' => 'prasideda simboliais',
	'LBL_ENDS_WITH' => 'baigiasi simboliais',
	'LBL_CONTAINS' => 'turi simbolius',
	'LBL_DOES_NOT_CONTAIN' => 'Neturi',
	'LBL_LESS_THAN' => 'mažiau nei',
	'LBL_GREATER_THAN' => 'daugiau nei',
	'LBL_LESS_THAN_OR_EQUAL' => 'mažiau arba lygu',
	'LBL_GREATER_OR_EQUAL' => 'daugiau arba lygu',
	'LBL_BEFORE' => 'prieš',
	'LBL_AFTER' => 'po',
	'LBL_BETWEEN' => 'tarp',
	'LBL_IS_EMPTY'=> 'tuščias',
	'LBL_IS_NOT_EMPTY' => 'netuščias',
	'LBL_APPROVE' => 'Patvirtinti',
	'LBL_HAS_CHANGED' => 'has changed',
	'LBL_HAS_CHANGED_TO' => 'has changed to',
	'LBL_HAS_CHANGED_FROM' => 'has changed from',
	'LBL_LESS_THAN_OR_EQUAL_TO' => 'less than or equal to',
	'LBL_GREATER_THAN_OR_EQUAL_TO' => 'greater than or equal to',
	'LBL_IS_NOT' => 'is not',
	'LBL_IS_ADDED' => 'is added',
	'LBL_IS_TODAY' => 'is today',
	'LBL_IS_TOMORROW' => 'is tomorrow',
	'LBL_IS_YESTERDAY' => 'is yesterday',
	'LBL_LESS_THAN_DAYS_LATER' => 'less than days later',
	'LBL_MORE_THAN_DAYS_LATER' => 'more than days later',

	//Detail view summary widgets
	'LBL_OWNER' => 'Savininkas',
	'LBL_CREATED_ON' => 'Sukūrimo data',
	'LBL_MODIFIED_ON' => 'Pakeitimo laikas',
	'LBL_MODIFIED' => 'Pakeista',
	'LBL_COMMENTED' => 'pakomentavo',

	//calender set-reminder
	'LBL_BEFORE_EVENT' => ' prieš įvykį',

	//Dashboard widgets
	'History' => 'Žurnalas',
	'Upcoming Activities' => 'Būsimos veiklos',
	'Overdue Activities' => 'Vėluojančios veiklos',
	'Funnel' => 'Piltuvėlis',
	'Potentials by Stage' => 'Galimybės pagal stadiją',
	'Pipelined Amount' => 'Pardavimų srautas',
	'Total Revenue' => 'Pajamų suma',
	'Top Potentials' => 'Didžiausios galimybės',
	'Forecast' => 'Prognozė',
	'Leads Created' => 'Užklausos sukurtos',
	'Leads by Status' => 'Užklausos pagal būseną',
	'Leads by Source' => 'Užklausos pagal šaltinį',
	'Leads by Industry' => 'Užklausos pagal veiklos sritį',
	'Tickets by Status' => 'Užduočių kortelės pagal būseną',
	'Open Tickets' => 'Atviros užduočių kortelės',
	'Funnel Amount' => 'Kiekis pagal pardavimo stadiją',
	'Key Metrics' => 'Pagrindiniai atsvaros taškai',
	'Mini List' => 'Mini sąrašas',
	'Tag Cloud' => 'Debesies žyma',
	'Notebook' => 'Užrašinė',

	//Exports strings
	'LBL_EXPORT_ALL_DATA' => 'Eksportuoti visus duomenis',
	'LBL_EXPORT_DATA_IN_CURRENT_PAGE' => 'Eksportuoti einamojo puslapio duomenis',
	'LBL_EXPORT_SELECTED_RECORDS' => 'Eksportuoti pasirinktus įrašus',
	'LBL_EXPORT_RECORDS' => 'Eksportuoti įrašus',
	'LBL_NO_RECORD_SELECTED' => 'Nepasirinktas joks įrašas.',
	'LBL_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Negalima pašalinti numatytojo valdiklio',
	'LBL_CUSTOM_VIEW_NAME_DUPLICATES_EXIST' => 'Toks sąrašas jau egzistuoja',
	'LBL_TYPE_AND_SEARCH' => 'Rašykite ir ieškokite',
		'LBL_EXPORT_CURRENCY_TOOLTIP_TEXT'=>'Jei norite eksportuoti valiutos vertes eilutėse, „Vtiger“ šį nustatymą naudos kaip šią valiutą. Bet kokios valiutos vertės už eilutės elementų lentelių bus eksportuojamos kaip naudotojo pasirinktoje valiuta (pasirinkta „Mano nuostatos“).',
		'LBL_EXPORT_LINEITEM_CURRENCY'=>'Pasirinkite valiutą (eilutės elementų vertėms)',
		'LBL_EXPORT_USER_CURRENCY' =>'Mano pasirinkta valiuta',
		'LBL_EXPORT_RECORD_CURRENCY'=>'Valiuta pasirinkta įraše',
	'LBL_EXPORT_FORMAT' => 'Eksportuoti formatą',
	'LBL_EXPORT_DATA' => 'Eksportuoti duomenis',

	'LBL_CUSTOMIZE' => 'Tinkinti',
	'LBL_ADD_MANAGE_MODULES' => 'Moduliai',
	'LBL_CUSTOMIZE_MAIN_MENU' => 'Meniu kairėje',
	'LBL_LABELS' => 'Etiketės',
	'LBL_WORKFLOWS' => 'Darbo procesai',
	'LBL_PICKLIST' => 'Parinkčių sąrašas',

	// Added Common Keys for all modules
	'Account Name' => 'Organizacijos pavadinimas',
	'Add Comment' => 'Pridėti pastabą',
	'Adjustment' => 'Patikslinimas',
	'Annual Revenue' => 'Metinės pajamos',
	'Apparel'=>'Apranga',
	'Banking'=>'Bankininkystė',
	'Billing Address' => 'Sąskaitų siuntimo adresas',
	'Billing City' => 'Sąskaitų siuntimo miestas',
	'Billing Code' => 'Sąskaitų siuntimo pašto kodas',
	'Billing Country' => 'Sąskaitų siuntimo šalis',
	'Billing Po Box' => 'Sąskaitų siuntimo pašto dėžutė',
	'Billing State' => 'Sąskaitų siuntimo savivaldybė (valstija)',
	'Biotechnology'=>'Biotechnologijos',

	//for SO PO and Quotes
	'FedEx'=>'FedEx',
	'UPS'=>'UPS',
	'USPS'=>'USPS',
	'DHL'=>'DHL',
	'BlueDart'=>'BlueDart',
	'Carrier' => 'Kurjeris',
	'Category'=>'Kategorija',
	'Chemicals'=>'Chemikalai',
	'City' => 'Miestas',

	'Cold Call'=>'Išeinantis skambutis',
	'Existing Customer'=>'Esamas klientas',
	'Self Generated'=>'Atsirado pats',
	'Employee'=>'Darbuotojas',
	'Partner'=>'Partneris',
	'Public Relations'=>'Viešieji ryšiai',
	'Direct Mail'=>'Tiesioginis laiškas',
	'Conference'=>'Konferencija',
	'Trade Show'=>'Paroda',
	'Web Site'=>'Svetainė',
	'Word of mouth'=>'Rekomendacija',
	'Other'=>'Kita',

	//for leads and accounts
	'--None--'=>'—Nieko—',
	'Acquired'=>'Įsigyta',
	'Active'=>'Aktyvus (-i)',
	'Market Failed'=>'Rinka žlugo',
	'Project Cancelled'=>'Projektas atšauktas',
	'Shutdown'=>'Likvidacija',
	'Apparel'=>'Apranga',
	'Banking'=>'Bankininkystė',
	'Biotechnology'=>'Biotechnologijos',
	'Chemicals'=>'Chemikalai',
	'Communications'=>'Komunikacijos',
	'Construction'=>'Statyba',
	'Consulting'=>'Konsultavimas',
	'Education'=>'Švietimas',
	'Electronics'=>'Elektronika',
	'Energy'=>'Energetika',
	'Engineering'=>'Inžinerija',
	'Entertainment'=>'Pramogos',
	'Environmental'=>'Aplinkos apsauga',
	'Finance'=>'Finansai',
	'Food & Beverage'=>'Maistas ir gėrimai',
	'Government'=>'Vyriausybinė organizacija',
	'Healthcare'=>'Sveikatos apsauga',
	'Hospitality'=>'Labdara',
	'Insurance'=>'Draudimas',
	'Machinery'=>'Mašinos',
	'Manufacturing'=>'Gamyba',
	'Media'=>'Medija',
	'Not For Profit'=>'Ne pelno siekianti',
	'Recreation'=>'Rekreacija',
	'Retail'=>'Mažmeninė prekyba',
	'Shipping'=>'Pristatymas',
	'Technology'=>'Technologijos',
	'Telecommunications'=>'Telekomunikacijos',
	'Transportation'=>'Transportas',
	'Utilities'=>'Komunalinės paslaugos',

	'Contact Name' => 'Adresato vardas',
	'Conversion Rate' => 'Keitimo kursas',

	'Shipping Address' => 'Pristatymo adresas',
	'Shipping City' => 'Pristatymo miestas',
	'Shipping State' => 'Pristatymo savivaldybė (valstija)',
	'Shipping Code' => 'Pristatymo pašto kodas',
	'Shipping Country' => 'Pristatymo šalis',
	'Shipping Po Box' => 'Pristatymo pašto dėžutė',
	'Country' => 'Šalis',
	'Description' => 'Aprašymas',

	'Created'=>'Sukurta',
	'Approved'=>'Patvirtintas (-a)',
	'Delivered'=>'Pristatyta',
	'Cancelled'=>'Atsisakyta',

	'Currency' => 'Valiuta',
	'LBL_BASE_CURRENCY' => 'Numatytoji valiuta',

	'Discount Percent' => 'Nuolaida procentais',
	'Discount Amount' => 'Nuolaidos suma',
	'Item Discount Amount' => 'Eilutės nuolaida',
	'Net Price' => 'Tarpinė suma', 
	'Item Discount Percent' => 'Eilutės nuolaida procentais',

	'Due Date' => 'Įvykdymo terminas',
	'Due Date & Time' => 'Įvykdymo terminas',
	'Email' => 'Pagrindinis el. pašto adresas',
	'Secondary Email' => 'Kitas el. paštas',
	'Other Email' => 'Kitas el. paštas ',
	'Email Opt Out' => 'Atsisakyta laiškų',
	'Is Converted From Lead' => 'Konvertuota užklausa',
	'Expected Close Date' => 'Laukiama užbaigimo data',
	'Fax' => 'Faksas',

	'Last Name' => 'Pavardė',
	'First Name' => 'Vardas',

	'High' => 'Aukštas',
	'Low' => 'Žemas',
	'In Progress' => 'Vykdomas (-a)',

	'Subject' => 'Tema ',
	'Shipping Address'=>'Pristatymo adresas',
	'Shipping Po Box'=>'Pristatymo pašto dėžutė',
	'Shipping City'=>'Pristatymo miestas',
	'Shipping State'=>'Pristatymo savivaldybė (valstija)',
	'Shipping Code'=>'Pristatymo pašto kodas',
	'Shipping Country'=>'Pristatymo šalis',
	'Terms & Conditions' => 'Terminai ir sąlygos',
	'Item Name' => 'Eilutės pavadinimas',
	'Quantity' => 'Kiekis',
	'List Price' => 'Pardavimo kaina',
	'Image' => 'Atvaizdas',
	'Purchase Cost' => 'Pirkimo kaina',
	'Margin' => 'Marža',
	'Item Comment' => 'Eilutės pastaba',
	'Tax1' => '1 mokestis',
	'Tax2' => '2 mokestis',
	'Tax3' => '3 mokestis',
	'Excise Duty' => 'Akcizas',
	'Total' => 'Suma',
	'Sub Total' => 'Tarpinė suma',
	'Tax Type' => 'Mokesčio tipas',
	'S&H Amount' => 'Gabenimo ir tvarkymo mokesčiai',
	'Status' => 'Būsena',
	'Vendor Name'=>'Tiekėjo pavadinimas',

	'LBL_ADDRESS_INFORMATION' => 'Adreso informacija',
	'LBL_DESCRIPTION_INFORMATION' => 'Aprašymas',
	'LBL_TERMS_INFORMATION' => 'Terminai ir sąlygos',
	'LBL_PRICING_INFORMATION' => 'Kainos informacija',
	'LBL_RELATED_PRODUCTS' => 'Prekės išsami informacija',
	'LBL_REMINDER_INFORMATION' => 'Priminimo išsami informacija',

	'LBL_FOLDER_SAVED' => 'Aplankas įrašytas',
	'LBL_FOLDER_EXISTS' => 'Aplankas jau egzistuoja',
	'LBL_FOLDER_DELETED' => 'Aplankas pašalintas',
	'LBL_EDIT_FOLDER' => 'Redaguoti aplanką',

	'Lead Source' => 'Užklausos šaltinis',
	'Mobile' => 'Mobilusis telefonas',

	'Notify Owner' => 'Informuoti savininką',
	'Other Phone' => 'Kitas telefonas',
	'Phone' => 'Pagrindinis telefonas',

	'State' => 'Savivaldybė (valstija)',
	'Po Box' => 'Pašto dėžutė',
	'Postal Code' => 'Pašto kodas',

	'Potential Name' => 'Galimybės pavadinimas',
	'Priority'=>'Prioritetas',

	'Product Name' => 'Prekės pavadinimas',
	'Rating' => 'Įvertinimas',

	'Related To'=>'Susiję su',
	'Type' => 'Tipas',

	'Reviewed'=>'Peržiūrėta',
	'Salutation' => 'Kreipinys',
	'Street' => 'Gatvė',
	'Support Start Date' => 'Aptarnavimo pradžios data',
	'Support Expiry Date' => 'Aptarnavimo pabaigos data',
	'Sales Start Date'=>'Pardavimų pradžios data',
	'Sales End Date'=>'Pardavimų pabaigos data',

	//Dashboard list of widgets translation
	'Open Ticktes' => 'Atviros užduočių kortelės',
	'LBL_SELECT_STATUS' => 'Pasirinkite būseną',
	'LBL_BLANK' => '-Tuščia-',

	//PageTitle translations
	'LBL_VTIGER_CRM_HONEST_OPEN_SOURCE' => '„vtiger CRM On Demand“',

	//Translations used in inventory modules for sopy address
	'SINGLE_Accounts' => 'Organizacija',
	'SINGLE_Contacts' => 'Adresatas',

	//Weekdays in 3 letters translations
	'LBL_Sun' => 'Sekm',
	'LBL_Mon' => 'Pirm',
	'LBL_Tue' => 'Antr',
	'LBL_Wed' => 'Treč',
	'LBL_Thu' => 'Ketv',
	'LBL_Fri' => 'Penkt',
	'LBL_Sat' => 'Šešt',

	//Months in 3 letters translations
	'LBL_Jan' => 'Sau',
	'LBL_Feb' => 'Vas',
	'LBL_Mar' => 'Kov',
	'LBL_Apr' => 'Bal ',
	'LBL_May' => 'Gegužė',
	'LBL_Jun' => 'Bir',
	'LBL_Jul' => 'Lie',
	'LBL_Aug' => 'Rugp',
	'LBL_Sep' => 'Rugs',
	'LBL_Oct' => 'Spa',
	'LBL_Nov' => 'Lap',
	'LBL_Dec' => 'Gruo',

	'LBL_CALENDAR_SETTINGS' => 'Kalendoriaus nuostatos',
	'Reminder Interval' => 'Intervalas tarp priminimų',

	//Translations used in inventory modules for address
	'SINGLE_Accounts' => 'Organizacija',
	'SINGLE_Contacts' => 'Adresatas',
	'HelpDesk' => 'Užduočių kortelės',
	'LBL_TAG_CLOUD' => 'Žymių debesis',

	'LBL_NO_RECORDS' => 'Įrašų nėra',
	'LBL_NO_RELATED' => 'Susijusių nėra',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE' => 'Tik pirmieji 100 rezultatų iš visų modulių rodomi žemiau. Jei norite peržiūrėti konkretaus modulio rezultatus, nurodykite jį paieškos formoje',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE_FOR_MODULE' => 'Tik pirmieji 100 rezultatų rodomi žemiau. Jei norite peržiūrėti daugiau rezultatų, pasinaudokite išplėstine paieška',

	// used in reports detail view
	'LBL_ACTION' => 'Veiksmas',
	'LBL_NOTE' => 'Pastaba',
	'LBL_SELECT_OPTION' => 'Pasirinkite',

	//Module Manager
	'LBL_TOOLTIP' => 'Patarimų tvarkymas',
	'LBL_MODULE_SEQUENCE_NUMBERING' => '%s Numeravimas',
	'LBL_CUSTOM_FIELD_MAPPING' => 'Papildomų laukų susiejimas',
	'LBL_WEBFORMS' => 'Saityno formos',

	//Compose Email Strings
	'SINGLE_Emails' => 'El. paštas',
	'Emails' => 'Laiškai',
	'LBL_SELECT_EMAIL_IDS' => 'Pasirinkite el. pašto adresus',
	'LBL_SUBJECT' => 'Tema ',
	'LBL_ATTACHMENT' => 'Priedas',
	'LBL_BROWSE_CRM' => 'Naršyti CRM',
	'LBL_SEND' => 'Siųsti',
	'LBL_SAVE_AS_DRAFT' => 'Įrašyti kaip juodraštį',
	'LBL_GO_TO_PREVIEW' => 'Eiti į peržiūrą',
	'LBL_SELECT_EMAIL_TEMPLATE' => 'Pasirinkite el. pašto šabloną',
	'LBL_COMPOSE_EMAIL' => 'Kurti laišką',
	'LBL_CC' => 'Kopija',
	'LBL_BCC' => 'Nematomoji kopija:',
	'LBL_ADD_CC' => 'Pridėti kopiją',
	'LBL_ADD_BCC' => 'Pridėti nematomą kopiją',
	'LBL_MAX_UPLOAD_SIZE' => 'Didžiausia leistina įkeliamo failo apimtis yra',
	'LBL_EXCEEDED' => 'Viršyta',
	'LBL_OPERATION_NOT_PERMITTED' => 'Operacija neleidžiama',
	'LBL_MERGE' => 'Sulieti',
	'LBL_FIND_DUPLICATES' => 'Rasti dublikatus',
	'LBL_MERGING_CRITERIA_SELECTION' => 'Suliejimo kriterijų pasirinkimas',
	'LBL_AVAILABLE_FIELDS' => 'Galimi laukai',
	'LBL_MERGE_RECORDS_DESCRIPTION' => 'Pagrindinis įrašas po suliejimo išliks. Galite pasirinkti stulpelį reikšmėms išsaugoti.
									Kitas įrašas bus pašalintas, tačiau susijusi informacija bus sulieta.',
	'LBL_MERGE_RECORDS_IN' => 'Sulieti įrašus esančius',
	'LBL_FIELDS' => 'Laukai',
	'LBL_RECORD' => 'Įrašas',
	'LBL_NO_DUPLICATED_FOUND' => 'Vienodų įrašų nerasta',
	'LBL_MERGE_SELECT' => 'Pasirinkti suliejimui',

	//sbproducts translation
	'LBL_BACK_TO_PRODUCTS' => 'Atgal į prekes',

	//Translations used for Export to Pdf
	'Valid Date' => 'Galiojimo data',
	'Phone: ' => 'Telefonas:',
	'Issued Date' => 'Išrašymo data',
	'Shipping & Handling Charges' => 'Pristatymo ir tvarkymo mokesčiai',
	'Shipping & Handling Tax:' => 'Pristatymo ir tvarkymo mokestis:',
	'Discount'=>'Nuolaida',
	'Net Total' => 'Tarpinė suma',
	'Product Code'=>'Prekės kodas',
	'Customer Name'=>'Kliento pavadinimas',
	'Price'=>'Kaina',
	'Tax:' => 'Mokesčiai:',
	'Contact Name' => 'Adresato vardas',
	'Grand Total:' => 'Galutinė suma:',
	'Fax: ' => 'Faksas:',
	'Website: ' => 'Svetainė:',
	'Tax' => 'Mokesčiai',
	'LBL_ALPHABETS' => 'A,Ą,B,C,Č,D,E,Ę,Ė,F,G,H,I,Į,Y,J,K,L,M,N,O,P,R,S,Š,T,U,Ų,Ū,V,Z,Ž',

	//Realted tab strings
	'Service Contracts' => 'Paslaugų sutartys',
	'Projects' => 'Projektai',
	'Sales Order' => 'Pardavimų užsakymai',
	'Purchase Order' => 'Pirkimo užsakymai',
	'Payments' => 'Mokėjimai',
	'List and Campaigns' => 'Sąrašas ir kampanijos',
	'Project Tasks' => 'Projekto užduotys',
	'Project Milestones' => 'Projekto etapai',

	'Labels Editor' => 'Žymių redaktorius',
	'LBL_IGNORE_EMPTY_VALUES' =>'Nepaisyti neįrašytų verčių',

	//Related tabs of Products
	'Product Bundles' => 'Prekių rinkiniai',
	'Parent Product' => 'Pirminė prekė',
	'LBL_PRODUCT_BUNDLE' => 'Produkto paketas',
	'LBL_EDIT_QUANTITY' => 'Redaguoti kiekį',
	'LBL_ADD_TO_PRODUCTS' => 'Pridėti produktus',

	'LBL_MANAGE_USERS' => 'Tvarkyti naudotojus',
	'LBL_TRANSFER_OWNERSHIP' => 'Perkelti savininkystę',
	'LBL_SELECT_RELATED_MODULES' => 'Pasirinkite susijusius modulius',
	'LBL_ASSIGNED_TO' => 'Priskirtas asmuo',
	//Comments Field Labels for Workflow
	'Comment' => 'Pastaba',
	'Last Comment' => 'Paskutinė pastaba',
	'Last 5 Comments' => 'Paskutinės 5 pastabos',
	'All Comments' => 'Visos pastabos',

	//Feedback on removing old version
	'LBL_OLD_VERSION_REMOVED_SOON' => 'Pridėti pastabą prie senos išvaizdos',
	'LBL_FEEDBACK_ON_REMOVING_OLD_VERSION' => 'Džiaugiamės galėdami pasidalinti tuo, kad sena išvaizda bus prieinama iki 2014 m. Vasario mėn. Neseniai prie šios naujos išvaizdos pridėjome šias funkcijas:<br><br>1. Suvestinės ataskaitos<br>2. Tinkinamos diagramos<br>3. Greita paieška sąrašuose<br><br>Jei turite pasiūlymų dėl naujo išvaizdos, prašome pasidalinti su mumis žemiau.',
	'LBL_FEEDBACK_PLACEHOLDER' => 'Pasidalinkite savo pasiūlymais čia...',
	'LBL_SUBMIT_FEEDBACK' => 'Siūsti atsiliepimą',
	'LBL_DONT_SHOW_AGAIN' => 'Daugiau šito nerodyti',
	'LBL_CONTINUE_TO_OLD_LOOK' => 'Tęsti pasirenkant seną išvaizdą',
	'LBL_LEFT_PANEL_SHOW_HIDE' => 'Kairysis polangis rodyti/slėpti',

	//Products Popup View
	'NOT_A_BUNDLE' => 'Ne rinkinys',
	'LBL_SUB_PRODUCTS' => 'Rinkinio prekės',
	'LBL_MARK_AS_HELD' => 'Žymėti kaip įvykdytą',
	'LBL_MARK_AS_COMPLETED' => 'Žymėti kaip užbaigtą',
	'LBL_SMS_MAX_CHARACTERS_ALLOWED' => 'Žinutėje leidžiama ne daugiau kaip 160 simbolių',
	'LBL_HIDE_COMPLETED_EVENTS' => 'Nerodyti užbaigtų įvykių kalendoriuje',
	'LBL_SETUP_WEBFORMS' => 'Konfigūruoti saityno formas',
	'LBL_SPECIAL_OPTIONS' => 'Specialiosios parinktys',
	'LBL_PARENT_OWNER' => 'Tėvinio įrašo savininkas',
	'LBL_PASSWORD_LINK_EXPIRED_OR_INVALID_PASSWORD' => 'Slaptažodžio atkūrimo saitas nebegalioja, arba jūs įvedėte netinkamą slaptažodį.',

	// Recurring Invoice
	'Half-Yearly' => 'Kas pusmetį',
	'LBL_FULLSCREEN' => 'Visas ekranas',
	'LBL_SETUP_WEBFORMS' => 'Konfigūruoti saityno formas',
	'LBL_MODULE_DISABLED' => 'Modulis išjungtas',
	'Organization Name' => 'Organizacijos pavadinimas',
	'LBL_SOCIAL_TWITTER_WIDGET' => '„Twitter“ veikla',
	'LBL_WEEK' => 'Savaitė ',
	//Convert Lead and Potential
	'CANNOT_CONVERT' => 'Negalima konvertuoti',
	'LBL_CONVERT_ERROR_TITLE' => 'Moduliai išjungti',
	'LBL_FOLLOWING_ARE_POSSIBLE_REASONS' => 'Į galimas priežastis įeina:',
	'LBL_MANDATORY_FIELDS_ARE_EMPTY' => 'Privalomi laukai neužpildyti',

	// SMSNotifier Phone Format Warning
	'LBL_PHONE_FORMAT_WARNING' => 'Įsitikinkite, kad telefono numeris yra tarptautiniame E.164 formate',
	'LBL_PHONEFORMAT_WARNING_CONTENT' => 'E.164 numerių formatavimas gali sudaryti ne daugiau kaip penkiolika skaitmenų ir paprastai rašomas taip: [+] [šalies kodas] [abonento numeris, įskaitant vietovės kodą]
Pavyzdžiui, norint konvertuoti JAV telefono numerį (415 599 2671) į E.164 formatą, prieš numerį reikės pridėti prefiksą "+" ir šalies kodą (kuris yra 1) (+1 415 599 2671 ) Jungtinėje Karalystėje ir daugelyje kitų šalių tarptautiniu mastu vietiniam rinkimui reikia pridėti 0 prie abonento numerio. Tačiau, norint naudoti E.164 formatavimą, šis 0 turi būti pašalintas. Jungtinėje Karalystėje numeris 020 7183 8750 bus suformatuotas kaip +44 20 7183 8750.',
	'LBL_WARNING' => 'Įspėjimas',
	'LBL_ORIGIN' => 'Kilmė',
	'SENT' => 'Išsiųsta',
	'RECEIVED' => 'Gauta',
	'QUEUED'=> 'Eilėje',
	'FAILED'=> 'Nepavyko  ',
	'SAVED' => 'Juodraštis',
	'MailManager' => 'Laiškų tvarkytuvė',
	'MAILSCANNER' => 'Laiškų keitiklis',
	'LBL_SENDER_NAME' => 'Siuntėjo vardas',
	'SMSNotifier'=>'Informavimas SMS žinute',

	'Mobile Call' => 'Mobilus skambutis',
	'LBL_NO_MORE_RESULTS' => 'Daugiau rezultatų nėra!',
	'Related To' => 'Susiję su',

	// Date Conditions
	'LBL_LESS_THAN_DAYS_AGO' => 'Mažiau nei prieš dienas',
	'LBL_MORE_THAN_DAYS_AGO' => 'Daugiau nei dienas',
	'LBL_IN_LESS_THAN' => 'Mažiau nei',
	'LBL_IN_MORE_THAN' => 'Daugiau nei',
	'LBL_DAYS_AGO' => 'Dienas prieš',
	'LBL_DAYS_LATER' => 'Dienas po',
	'LBL_LESS_THAN_HOURS_BEFORE' => 'Mažiau nei valandas prieš',
	'LBL_LESS_THAN_HOURS_LATER' => 'Mažiau nei valandas po',
	'LBL_MORE_THAN_HOURS_BEFORE' => 'Daugiau nei valandas prieš',
	'LBL_MORE_THAN_HOURS_LATER' => 'Daugiau nei valandas po',
	'LBL_INTERNAL_COMMENT' => 'Vidinis komentaras',
	'LBL_NOTE_EXISTING_ATTACHMENTS_WILL_BE_REPLACED' => 'Pastaba: esami priedai (vaizdai / failai) bus pakeisti',

	//common standard fields
	'Created By' => 'Sukurta',
	'LBL_SEND_PDF_FOR_SIGNING' => 'Siūsti PDF pasirašymui',
	'LBL_CLICK_TO_EDIT' => 'Spauskite čia norėdami redaguoti',
	'LBL_SIGNATURE_BLOCK' => 'Parašas',
	'LBL_INCLUDE_SIGNATURE_INFO' => 'Parašas, nurodytas mano parinktyse, bus pridėtas el. laiško apačioje',
	'LBL_INCLUDE_SIGNATURE' => 'Įtraukti parašą',

	// module builder created module first block label 
	'LBL_BASIC_INFORMATION' => 'Pagrindinė informacija',
	'LBL_CLICK_HERE'=>'spauskite čia',

	//Recipient preferences labels
	'LBL_SELCT_EMAIL_RECIPIENTS' => 'Pasirinkite el. pašto gavėjus',
	'LBL_REMEMBER_MY_PREF' => 'Prisiminti mano nuostatas',
	'LBL_RECIPIENT_PREFS'=>'Gavėjo nuostatos',
	'LBL_EMAIL_RECIPIENT_PREFS'=>'El. pašto gavėjo nuostatos',
	'LBL_ERROR_SAVING_PREF' => 'Nepavyko išsaugoti nuostatų. Bandykite dar kartą!',
	'LBL_NO_PREF_GIVEN' => 'Nuostatos nenurodytos!',
	'LBL_PLEASE_ADD_EMAIL_FIELDS' => 'Pridėkite el. pašto laukus ir bandykite dar kartą',
	'LBL_RECIPIENT_SAVE_MESSAGE'=>'Išsaugota sėkmingai. Šios nuostatos bus traktuojamos kaip gavėjo el. pašto adresai, kai siunčiate el. laiškus iš šio modulio.',
	'LBL_PREF_RESET_MESSAGE' => 'Jūsų gavėjo el. pašto nuostatos buvo iš naujo nustatytos!',

	'LBL_COMPANY_DETAILS' => 'Įmonės informacija',
	'COMPANY_LOGO_HELP_TEXT' => 'Įkelkite savo gražų įmonės logotipą.<br> Jis ne tik rodomas „CRM“ sistemoje, bet kartu su<br>
									jūsų įmonės vardu ir adresu yra naudojami <br> el. pašto kampanijose (reikalaujama, kad atitiktų „span“ taisykles)<br>
									 ir pasiūlymuose.',
	'COMPANY_LOGO_HELP_TEXT_2' =>"Galite redaguoti įmonės informaciją vėliau per <br>
										„CRM Nustatymai > Šablonai > Įmonės informacija“ puslapyje",
	'LBL_CHOOSE_PREFERENCES' => 'Pasirinkite savo nuostatas',
	'PREFERENCES_HELP_TEXT' => 'Bazinė valiuta - pasirinkite pagrindinę valiutą. Jei naudojate kelias<br>
								valiutas, visos vertės konvertuojamos į bazinę valiutą ir saugomos,<br>
								naudojant „CRM“ sukonfigūruotą perskaičiavimo kursą.',
	'PREFERENCES_HELP_TEXT_2' => 'Asmeninius nustatymus gali nustatyti kiekvienas komandos narys.<br>
									Tai apima laiko juostą, kalbą, datos formatą, skaičių formatą.<br>
									Numerio formato nuorodos naudojamos valiutoms ir kitiems <br>
									numerių laukams „CRM“<br>
									Galite vėliau redaguoti savo nuostatas iš „Vartotojo vardas > mano nuostatos“',
	'LBL_CANNOT_BE_CHANGED_LATER' => 'Negali būti pakeistas vėliau',
	'IMPORT_CONTACTS_GOOGLE_HELP_TEXT' => 'Mes galime sukurti kontaktus iš „Google“, o taip pat galite įjungti dvikryptę sinchronizaciją<br>
									„Vtiger“ ir "Google" kontaktams (pasirinktoje grupėje) atnaujinti.<br>
									Spustelėkite mygtuką, kad įgalintumėte ir gautumėte „Google“ kontaktus.',
	'IMPORT_CONTACTS_CSV_HELP_TEXT' => 'Galite įkelti kontaktus iš „CSV“ failo.',
	'IMPORT_CONTACTS_CSV_HELP_TEXT2' => 'Norėdami importuoti galimybes, užklausas, užduočių korteles, prašome ieškoti veiksmai > importuoti mygtuko bet kuriame iš
										sąrašo peržiūrų.',
	'LBL_DOEST_FIRST_ROW_HEADER' => 'Ar jūsų failo pirmoji eilutė turi stulpelių antraštes?',
	'LBL_SELECT_CSV_FILE' => 'Pažymėkite CSV failą',
	'LBL_START_IMPORTING' => 'Pradėti importą',
	'LBL_PRIMARY' => 'Pagrindinis',
	'LBL_GOOGLE_SYNC_INTIATED_MSG' => 'Jūsų importas yra suplanuotas, jūsų kontaktai bus netrukus importuoti.<br> Tolesniame žingsnyje importas nebus pertrauktas.',
	'LBL_IMPORT_SYNC_INTIATED_MSG' => 'Jūsų importas vykdomas. Kai importas bus baigtas, gausite el. laišką. <br>Tolesniame žingsnyje importas nebus pertrauktas. ',
	'LBL_TELL_US_ABOUT_YOU' => 'Padėkite mums susipažinti su jūsų įmone',
	'TELL_US_ABOUT_YOU_HELP_TEXT' => 'Mes ir toliau tobuliname „CRM“ ir <br>
									geriau suprasdami mūsų naudotojus, padėsime suteikti prioritetus patobulinimams.',
	'TELL_US_ABOUT_YOU_HELP_TEXT_2' => 'Čia pateikti duomenys niekam nebus atskleisti <Br>
										už „Vtiger“ ribų.',
	'LBL_INVALID_IMAGE' => 'Paveikslas netinkamas arba sugadintas',
	'LBL_IMPORT_CONTACTS' => 'Importuoti kontaktus',
	'LBL_FROM_GOOGLE' => 'iš „Google“',
	'LBL_FROM_CSV' => 'iš „CSV“ failo',
	'LBL_NEXT' => 'Toliau',
	'LBL_FINISH' => 'Užbaigti',
	'LBL_GET_CONTACTS_FROM_GOOGLE' => 'Gauti kontaktus iš „Google“',
	'LBL_PHONE_NUMBER' => 'Telefono numeris',
	'LBL_NUMBER_OF_EMPLOYEES' => 'Darbuotojų skaičius',
	'LBL_INDUSTRY' => 'Veiklos sritis',
	'LBL_HELP_DESK_EMAIL_HELP_TEXT' => 'Su užduočių kortelėmis susiję pranešimai bus siunčiami iš šio el. pašto adreso',
	'LBL_SOCIAL_DETAILS' => 'Susiekite su socialiniais tinklais, kad rastumėte naujų klientų ir atsakytumėte į užklausas',
	'LBL_SOCIAL_AUTHORIZE_HELP'=>'Susiekite su savo „Twitter“ paskyra, kad paskelbtumėte savo pranešimus ir stebėtumėte įtraukimą',
	'LBL_SOCIAL_AUTHORIZE' => 'Susiekite su „Twitter“',
	'LBL_SOCIAL_LINKED' => 'Jūsų „Vtiger“ dabar yra susietas su',
	'LBL_ENTER_KEYWORDS_HELP'=>'„Vtiger“ nuskaitys twitter ir suras pranešimus su šiais žodžiais',
	'LBL_ENTER_KEYWORDS' => 'Įveskite raktažodžius',

	 // Social Module Strings
	'LBL_TWEETS' => '„Tweets“',
	'LBL_FAVOURITES' => 'Mėgstamiausi',
	'LBL_FOLLOWING' => 'Sekami',
	'LBL_FOLLOWERS' => 'Sekėjai',
	'LBL_VIEW_FULL_PROFILE' => 'Peržiūrėti pilną profilį',
	'LBL_LOCATION' => 'Vieta',
	'LBL_DESCRIPTION' => 'Aprašymas',
	'LBL_JOINED' => 'Prisijungė',
	'LBL_SEARCH_PROFILES_IN_TWITTER' => 'Iškoti profilių „Twitter“',
	'LBL_CHOOSE_ANOTHER_PROFILE' => 'Pasirinkite kitą profilį',
	'LBL_ADD_TICKET' => 'Pridėti užduoties kortelę',
	'LBL_ADD_OPPORTUNITY' => 'Pridėti galimybę',
	'LBL_RETWEET' => '„Retweet“',
	'LBL_RETWEETS' => '„Retweets“',
	'LBL_UNDO_RETWEET' => 'anuliuoti „Retweet“',
	'LBL_FAVOURITE' => 'Mėgstamiausias',
	'LBL_UNDO_FAVOURITE' => 'anuliuoti mėgstamiausią',
	'LBL_TWITTER_HANDLER_MSG' => 'Jei norite pamatyti šio kontaktinio asmens profilio santrauką ir istoriją, pridėkite savo „Twitter“ naudotojo vardą ar paieškos profilį naudodami toliau pateiktą nuorodą.',
	'LBL_ADD_EVENT_OR_TODO' => 'Pridėti įvykį / užduotį',
	'LBL_ADD_TICKET_CONTACT' => 'Pridėti užduočties kortelę + adresatą',
	'LBL_ADD_CASE_CONTACT' => 'Pridėti bylą + adresatą',
	'LBL_ADD_OPPORTUNITY_CONTACT' => 'Pridėti galimybę + adrestą',
	'LBL_TWITTER_HANDLER_DETAILS' => '„Twitter“ vartotojo informacija',
	'LBL_PRIMARY_TWITTER' => '„Twitter“ vartotojo vardas',
	'LBL_ADD_TWITTER_HANDLER' => 'Pridėti „Twitter“ vartotojo vardą',
	'LBL_VIEW_TICKET' => 'Peržiūrėti užduoties kortelę',
	'LBL_VIEW_CASE' => 'Peržiūrėti bylą',
	'LBL_VIEW_OPPORTUNITY' => 'Peržiūrėti galimybę',
	'LBL_CLICK_TO_SELECT_PROFILE' => 'Spauskite čia norėdami pasirinkti profilį',
	'LBL_INVALID_IMAGE' => 'Paveikslas netinkamas arba sugadintas',
	'LBL_NEXT' => 'Toliau',
	'LBL_FINISH' => 'Užbaigti',
	// Module field to store Source of Record
	'Source' => 'Šaltinis',

	'LBL_DEFAULT_REPLY_TO' => 'Numatytas „atsakyti kam“ siunčiant  el. paštą', 
	'outgoing_server_from_email' => 'Laiškų siuntimo serverio „nuo“ el. paštas', 
	'hepldesk_support_email' => 'Pagalbos tarnybos el. pašto adresas', 
	'user_primary_email' => 'Vartotojo pagrindinis el. paštas', 
	'LBL_DEFAULT_REPLY_TO_INFO' => 'Šis nustatymas taikomas tik tiesioginiams el. laiškams iš „CRM“. Tai neturi įtakos el. paštui siunčiamam iš darbo eigos, el. pašto kampanijų ir t.t.', 
	'search_in_all_fields'=>'Ieškoti visuose laukuose',
	'search_in_name_field'=>'Ieškoti vardo lauke',
	'LBL_LOOKUP_SEARCH_MODE_INFO'=>'Pvz: Kontaktų kūrimo formoje, kai įvedate tekstą organizacijos pavadinimo lauke, šis nustatymas valdys, kokius organizacijos laukus reikia ieškoti',

	'VAT' => 'PVM',
	'Sales' => 'Pardavimai',
	'Service' => 'Paslauga',
	'Pre Tax Total' => 'Suma be mokesčių',
	'Received' => 'Gauta',
	'Balance' => 'Likutis',
	'S&H Amount' => 'Gabenimo ir tvarkymo mokesčiai',
	'S&H Percent' => 'Mokesčiai rinkliavai',
	'Tax Region' => 'Mokesčių regionas',

	//Singular Modulenames
	'SINGLE_Potentials' => 'Galimybė',
	'SINGLE_HelpDesk' => 'Užduočties kortelė',
	'SINGLE_Accounts' => 'Organizacija',
	'SINGLE_Contacts' => 'Adresatas',
	'SINGLE_Project' => 'Projektas',
	'LBL_ROLLUP_COMMENTS_INFO' => "Jei sugrupuoti kontaktai nustatymas įjungtas, bus rodomi komentarai apie susijusius įrašus.
								Pavyzdžiui, jei peržiūrite komentarus organizacijos įraše, taip pat bus rodomi komentarai, pridėti prie susijusių kontaktų, galimybių, užduočių kortelių ir t.t.",
	'LBL_ROLLUP_COMMENTS' => "Sugrupuoti komentarai",

	//others
	'Engagement Score' => 'Įtraukimo balas',
	'group' => 'Grupė',
	'individual' => 'Individualus',
	'LBL_VIEW_FILE'=>'Peržiūrėti failą',
	'LBL_DOWNLOAD_FILE' => 'Parsisiųsti failą',
	'LBL_PREVIEW_NOT_AVAILABLE' => 'Peržiūra negalima',
	'LBL_PREVIEW_SUPPORTED_FILES' => '<b><strong>Palaikomi failų tipai: </strong></b><br><br><b>„PDF“, </b><br><b>tekstiniai failai - </b>„txt“, „csv“, „ics“ <br><b>„Open Document“ failus - „open document text“ („odt“), „open document spreadsheet“ („ods“) ir „open document presentation“ („odp“). Daugialypės terpės failai - atvaizdų, garso ir vaizdo failai',
	'Mailing Address' => 'Laiškų siuntimo adresas',
	'Other Address' => 'Kitas adresas',
	'LBL_PREVIOUS' => 'Praeitas',
	'LBL_NEXT' => 'Toliau',
	'Workflows' => 'Darbo procesai',
	'Primary Twitter' => '„Twitter“ vartotojo vardas',

	/* Vtiger7 Language Strings */
	'LBL_CLICK_HERE_TO_SELECT_ALL_RECORDS'=>'Pažymėti visus įrašus šiame puslapyje',
	'LBL_CLICK_HERE_TO_MANAGE_LIST_COLUMNS'=>'Spauskite čia norėdami valdyti sąrašo stulpelius',
	'LBL_SHOW_MORE' =>'Rodyti daugiau',
	'LBL_DISPLAYING_RESULTS' => 'Rodomi rezultatai',
	'LBL_ADD_STAR' => 'Pridėti žvaigždę',
	'LBL_REMOVE_STAR' => 'Pašalinti žvaigždę',
	'LBL_UPDATE_LIST' => 'Atnaujinti sąrašą',
	'LBL_SHARE_THIS_LIST' => 'Pasidalinti šiuo sąrašu',
	'LBL_ADD_USERS_ROLES' => 'Pridėti vartotojus ir pareigybes',
	'LBL_LISTS' => 'Sąrašas',
	'LBL_SEARCH_FOR_LIST' => 'Ieškoti sąrašu',
	'LBL_MY_LIST' => 'Mano sąrašas',
	'LBL_SHARED_LIST' => 'Bendras sąrašas',
	'LBL_MERGE_SELECTED_RECORDS' => 'Sulieti pažymėtus įrašus',
	'LBL_MATCH_CRITERIA' => 'Pasikartojantys paieškos kriterijai',
	'LBL_MATCH_FIELDS' => 'Sutapatinti laukus',
	'LBL_EDIT_CUSTOM'=>'Redaguoti sąrašą',
	'LBL_SHOW_MAP'=>'Rodyti žemėlapį',
	'LBL_ADD_TAB'=>'Pridėti skiltį',
	'LBL_TAB_NAME'=>'Skydelio pavadinimas',
	'LBL_SHARED_TAGS_ACCESS'=>'Bendros žymos yra prieinamos visiems „Vtiger“ vartotojams',
	'LBL_GOTO_TAGS'=>'Eikite į Nustatymai > Mano nustatymai > Mano žymos norint redaguoti arba pašalinti privačias žymas',
	'LBL_UNLINK'=>'Atsieti',
	'LBL_SWITCH_TO_OLD'=>'Perjungti į seną versiją',
	'LBL_SLA_INFORMATION' => '„SLA“ informacija',

	//configure columns
	'LBL_UPDATE_LIST' => 'Atnaujinti sąrašą',
	'LBL_CONFIG_COLUMNS' => 'Konfiguruoti stulpelius',
	'LBL_SELECTED_FIELDS' => 'Pasirinkti laukai',
	'LBL_AVAILABLE_FIELDS' => 'Galimi laukai',
	'LBL_SEARCH_FIELDS' => 'Paieškos laukai',

	// Extensions
	'ExtensionStore' =>'Priedų parduotuvė',
	'LBL_EXTENSIONS' => 'Priedai',
	'LBL_SYNC_LOG' => 'Sinchronizuoti žurnalą',
	'LBL_SYNC_SETTINGS' => 'Sinchronizuoti nustatymus',
	'LBL_SYNC_NOW' => 'Sinchronizuoti dabar',
	'LBL_DATE' => 'Data',
	'LBL_TIME' => 'Laikas',
	'LBL_SKIPPED' => 'Praleisti',
	'vt_create' => 'Įrašai sukurti „Vtiger“',
	'vt_update' => 'Įrašai atnaujinti „Vtiger“',
	'vt_delete' => 'Įrašai pašalinti iš „Vtiger“',
	'vt_skip' => 'Įrašai praleisti „Vtiger“',
	'app_create' => 'Įrašai sukurti %s',
	'app_update' => 'Įrašai atnaujinti %s',
	'app_delete' => 'Įrašai pašalinti iš %s',
	'app_skip' => 'Įrašai praleisti %s',
	'LBL_DOWNLOAD_AS_CSV' => 'Parsiūsti kaip „CSV“',
	'LBL_SOURCE_MODULE' => 'Šaltinio modulis',
	'LBL_RECORD_NAME' => 'Įrašo pavadinimas',
	'LBL_REASON' => 'Priežastis',
	'LBL_SELECT_MODULES_TO_SYNC' => 'Pasirinkti modulius sinchronizavimui',
	'LBL_DATA' => 'Duomenys',
	'LBL_ENABLE_SYNC' => 'Įgalinti sinchronizaciją',
	'LBL_FIELD_MAPPING' => 'Laukų susiejimas',
	'LBL_SYNC_DIRECTION' => 'Sinchronizacijos kryptis',
	'LBL_SYNC_BOTH_WAYS' => 'Sinchronizuoti abiejom kryptim',
	'LBL_SAVE_SETTINGS' => 'Išsaugoti nustatymus',
	'LBL_CONFIGURE' => 'Konfiguruoti',
	'LBL_VIEW' => 'Peržiūrėti',
	'LBL_CHANGE_USER' => 'Keisti vartotoją',

	'LBL_CREATE_LIST' => 'Sukurti naują sąrašą',
	'sent' => 'Išsiųsta',
	'accepted' => 'Priimtas',
	'SINGLE_Users' => 'Vartotojas',
	'LBL_RECENT_COMMENTS' => 'Naujausi komentarai',
	'LBL_ENGAGEMENT_HISTORY' => 'Įtraukimo istorija',
	'LBL_NO_ENGAGEMENTS_FOUND' => 'Nėra susijusių lietimo taškų',
	'LBL_MARKETING' => 'RINKODARA',
	'LBL_SALES' => 'PARDAVIMAI',
	'LBL_PROJECT' => 'PROJEKTAI',
	'LBL_TOOLS' => 'Įrankiai',
	'LBL_TAGS' => 'Žymos',
	'LBL_SHARE_TAGS' => 'Viešos žymos',
	'LBL_SHARE_TAG' => 'Bendra žyma (-os)',
	'private' => 'privatus',
	'Tags' => 'Žymos',
	'public' => 'bendras',
	'Private/Shared' => 'Privatus/Bendras',
	'LBL_TAG_FOR' => 'Žymos %s',
	'LBL_CURRENT_TAGS' => 'Dabartinės žymos',
	'LBL_CREATE_NEW_TAG'=> 'Sukurti naują žymą',
	'LBL_ADD_TAG' => 'Pridėti žymą',
	'LBL_REMOVE_TAG' => 'Pašalinti žymą',
	'LBL_TAG_SEPARATOR_DESC' => 'Naudokite kablelį, kad atskirti žymas',
	'LBL_ENTER_TAG_NAME'=> 'Įrašyke žymos pavadinimą',

	'LBL_SELECT_COLOR' => 'Pasirinkti spalvą',
	'LBL_NO_TAG_EXISTS' => 'Žymų nėra',
	'LBL_ADD_NEW_TAG' => 'Pridėti žymą',
	'LBL_SELECT_EXISTING_TAG' => 'Rašykite čia norėdami pasirinkti egzistuojančią žymą',
	'LBL_CREATE_NEW_TAG' => 'Sukurti naują žymą',
	'LBL_ADD_OR_SELECT_TAG' => 'Pridėti/Pasirinkti žymą',
	'LBL_SELECT_FROM_AVAIL_TAG' => 'Pasirinkti iš esamų žymų',
	'LBL_MARKET_PLACE' => 'Turgus',

	'LBL_SHARE_THIS_LIST' => 'Pasidalinti šiuo sąrašu',
	'LBL_ADD_USERS_ROLES' => 'Pridėti vartotojus ir pareigybes',
	'EmailTemplates' => 'El. laiškų šablonai',
	'LBL_BILLING' => 'Atsiskaitymas',
	'LBL_ENABLED' => 'Įjungta',

	//Title added for buttons
	'LBL_CREATE_FILTER' => 'Sukurti filtrus',
	'LBL_IS' => 'yra',
	'LBL_CREATION' => 'kūryba',
	'LBL_UPLOAD' => 'Įkelti',
	'LBL_ATTACH_FILES' => 'Pridėti failai',
	'LBL_KEY_FIELDS' => "Pagrindiniai laukai",
	'LBL_ADD_TODO' => 'Pridėti užduotį',

	"LBL_VIEW_DETAILS" => "Peržiūrėti išsamią informaciją",

	//Engagements History
	"LBL_HAPPENED_ON" => "Įvyko",
	"LBL_HAPPENED" => 'Įvyko',
	"LBL_TYPE" => "Tipas",
	"LBL_STATUS" => "Būsena",
	"LBL_CUSTOMER" => "Susiję su",
	"LBL_SUMMARY" => "Santrauka",
	"LBL_ENGAGEMENTS" => "Lietimo taškai",

	'LBL_PLEASE_SELECT_ATLEAST_ONE_OPTION' => 'Pasirinkie bent vieną parinktį',
	'LBL_STARRED' => 'Nebesekti',
	'LBL_UNSTARRED' => 'Sekti',
	'LBL_EDIT_EMAIL_PREFERENCE_TOOLTIP' => 'Redaguokite šias nuostatas išskleidžiamojo meniu nustatymuose modulių informacija ar sąrašo peržiūros',
	'LBL_SYSTEM' =>'Sistema',
	'LBL_SHOW_MAP' => 'Rodyti žemėlapį',
	'LBL_GOOGLE_MAP' => '„Google“ žemėlapis',
	'LBL_CREATION' => 'kūryba',
	'LBL_ADD_TODO' => 'Pridėti užduotį',

	'LBL_KEY_METRICS' => 'Pagrindiniai skaitikliai',

	//Print template strings
	'LBL_TEMPLATE_NAME' => 'Šablono pavadinimas',
	'LBL_MODULE' => 'Modulis',
	'LBL_IS_DEFAULT' => 'Numatytas šablonas',
	'LBL_SELECT_RECORD_FIELD' => 'Pasirinkti įrašo lauką',
	'LBL_PREVIEW' => 'Peržiūra',
	'LBL_UNLINKED' => 'Atsieti',

	'LBL_FOLLOW' => 'Sekti',
	'LBL_UNFOLLOW' => 'Nebesekti',
	'Any' => 'Bet koks',
	'LBL_NA' => '---',
	'LBL_DISABLED' => 'Išjungta',

	//help
	'LBL_HELP_ANSWERS' => 'Atsakymai',
	'LBL_HELP_ARTICLES' => 'Straipsniai',
	'LBL_HELP_TOUR' => 'Turas',
	'LBL_NO_HELP_ARTICLE_FOUND' => 'Atsiprašome, jokio straipsnio nerasta',
	'LBL_HELP_SEARCH' => 'Paieškos pagalba',
	'LBL_HELP_BROWSE_ALL' => 'Naršykite visus',

	'LBL_EXPORT_FILE_NAME' => 'Eksportuoti failo pavadinimą',
	'LBL_EXTENSION_NOT_ALLOWED_FOR_NONADMIN' => '%s Sinchronizacija galima tik administratoriams',
	'SINGLE_Invoice' => 'Sąskaita faktūra',
	'SINGLE_SalesOrder' => 'Pardavimo užsakymai',
	'SINGLE_PurchaseOrder' => 'Pirkimo užsakymai',
	'SINGLE_Quotes' => 'Pasiūlymas',
	'LBL_POST_YOUR_COMMENT_HERE' => 'Paskelbkite savo komentarą čia',
	// Phone Calls
	'LBL_CLICK_TO_CALL' => 'Spauskite norėdami paskambinti',
	'LBL_SHOW_TOTAL_NUMBER_OF_RECORDS' => 'Spustelėkite šį sąrašo dydį',

	'LBL_GENERAL_FIELDS' => 'Pagrindiniai laukai',
	'LBL_ROLL_UP' => 'Sugrupuoti',

	'LBL_TOUCH_POINTS' => 'Lietimo taškai',
	'LBL_HISTORY' => 'Žurnalas',
	'LBL_ENGAGEMENT_HISTORY' => 'Įtraukimo istorija',
	'LBL_SETTINGS' => 'Nuostatos',

	//List View and thumbnail view button labels
	'LBL_LIST_VIEW'=>'Sąrašo rodinys',
	'LBL_THUMBNAIL_VIEW'=>'Miniatiūros rodinys',
	'LBL_CHART_VIEW'=>'Diagramos vaizdas',
	'LBL_EMAIL_SUPPORT' => 'Pagalba el. paštu',
	'LBL_NO_ENTITIES_FOUND' => 'Jokių %s nerasta',

	'LBL_TRANSFER_ALL_CASES_TO' => 'Perkelti visas bylas į',
	'LBL_SLA_TO_BE_DELETED' => '„SLA“ turi būti ištrinta',
	'LBL_TO_USE_SWITCH_TO_NEW_LOOK' => 'Norint naudoti <b>%s</b>, rekomenduojame naudoti naują išvaizdą',
	'LBL_INTERNAL_COMMENT_INFO' => 'Komentarus matys tik „CRM“ vartotojai, jei įjungtas vidinis komentaras. Jei norite pranešti klientams (konfigūruojamomis darbo eigomis ar klientų portale) palikite šį žymimąjį laukelį išjungtą',
	'LBL_CHANGE' => 'Keisti',
	'LBL_REVOKE_ACCESS' => 'Atšaukti prieigą',
	'GOOGLE_REVOKE_ACCESS_MESSAGE' => 'Paspaudus šią nuorodą bus pašalinta esama „Google“ autentifikacija, skirta kontaktams ir kalendoriui. Ji neištrins jokių jau sinchronizuotų įrašų.',
	'OFFICE_REVOKE_ACCESS_MESSAGE' => 'Paspaudus šią nuorodą bus pašalinta esama „Office365“ autentifikacija, skirta kontaktams ir kalendoriui. Ji neištrins jokių jau sinchronizuotų įrašų.',
	'LBL_START_GUIDED_TOUR' => 'Pradėkite kelionę su gidu',
	'LBL_MENU' => 'Meniu',
	'LBL_EMAIL_DOMAIN_HELPTEXT'=>'Email Domain field will be used to match Cases and Contacts created from Emails. '
	. 'For example, if a new support email comes from john@company.com, it would be linked to Organization that has '
	. 'company.com in the Email domain field. Multiple domains should be separated by commas',

	'LBL_SHARED_LIST_NON_ADMIN_MESSAGE' => 'Tai bendrai naudojamas sąrašas. Susisiekite su savo „CRM“ administratoriumi, kad sukonfigūruotumėte stulpelius visam sąrašui',
	'LBL_SHARED_LIST_OWNER_MESSAGE' => 'Tai bendrai naudojamas sąrašas. Susisiekite su savo %s, kad sukonfigūruotumėte stulpelius visam sąrašui',

	'Mr.' => 'Ponas',
	'Ms.' => 'Panelė',
	'Mrs.' => 'Ponia',
	'Dr.' => 'Daktaras',
	'Prof.' => 'Profesorius',
	'SINGLE_Cases'=>'Byla',
	'LBL_TAX_MODE_INFO' =>'Jei individualūs, mokesčiai bus atrinkti iš produktų įrašo. Jei grupiniai, mokesčiai bus atrinkti iš globalių nustatymų.',
	'LBL_CURRENCY_INFO' =>'Vertės bus pakeistos į pasirinktą valiutą, atsižvelgiant į sukonfigūruotą konversijų rodiklį.',
	'LBL_TAX_REGION_INFO' =>'Kintamųjų mokesčių atveju mokesčio procentas bus grindžiamas pasirinktu mokesčių regionu.',
	'LBL_TAX_CONFIGURE' =>'Konfiguruoti mekesčių regioną',
	'LBL_SEND_MSG_TO_SUPPORT' => 'Siųsti el. laišką pagalbai',
	'LBL_CHAT_WITH_SUPPORT' => 'Tiesioginis pokalbis su „CRM“ ekspertu',

	'LBL_ROLES' => 'Vaidmenys',
	'LBL_ROLEANDSUBORDINATE' => 'Vaidmuo ir pavaldiniai',
	'LBL_YOUR_LEARNING_SCORE' => 'Jūsų „CRM“ mokymosi rezultatas',
	'LBL_SWITCH_TO_VTIGER7_NOW' => 'Perjunkite į „Vtiger7“ iki vasario 15 d',
	'LBL_VTIGER6_RETIREMENT_NOTICE' => 'Ši versija bus nurašyta 2016 m. Vasario 15 d',
	'ModTracker' => 'Atnaujinimai',
	'LBL_MAIL_SENT_SUCCESSFULLY' => 'Laiškas išsiųstas sėkmingai',
        'LBL_MAIL_SAVED_SUCCESSFULLY' => 'Mail Saved Successfully',
	'LBL_FAILED_TO_SEND' => 'Nepavyko išsiųsti',

	'LBL_ESSENTIALS' => 'Būtinieji dalykai',
	'LBL_ALL_SETTINGS' => 'Visi nustatymai',
	'On' => 'Įjungta',
	'LBL_OPEN_IN_NEW_TAB' => 'Atidaryti naujame skirtuke',
	'LBL_DELETE_FOREVER'=>'Ištrinti visam laikui',
	'LBL_PLEASE_CLICK_ON_EDIT_TO_ADD_NOTE' =>'Paspauskite redaguoti, jei norite pridėti pastabas čia ...',
	'LBL_PLEASE_ENTER_YOUR_NOTE' => 'Prašome įvesti savo pastabas čia ...',
	'LBL_PORTAL' => 'Portalas',
	'LBL_SESSION' =>'Sesija',
	'LBL_SESSIONS' => 'Sesijos',
	'week days later' => 'savaitės dienos po',
	'more than week days later' => 'Daugiau nei savaitės dienos po',
	'less than week days later' => 'Mažiau nei savaitės dienos po',
	'week days ago' => 'savaitės dienos prieš',
	'more than week days ago' => 'Daugiau nei savaitės dienos prieš',
	'less than week days ago' => 'Mažiau nei savaitės dienos prieš',

	'LBL_DUPLICATES' => 'Dublikatai',
	'LBL_DUPLICATES_DETECTED' => 'Dublikatas(-ai) aptikti!',
	'LBL_DUPLICATES_FOUND_MESSAGE' => 'Šis %s negali būti išsaugotas, nes dublikatas %s jau yra „Vtiger“ su atitinkančiomis verybėmis %s.',
	'LBL_VTIGER_NOTIFICATION' => 'Pranešimas nuo: „Vtiger“ pranešimų sistemos',
	'LBL_DUPLICATION_FAILURE_FROM_WORKFLOWS' => 'Šie %s negali būti išsaugoti nuo „%s“ darbo eigų, nes kiti %s egzistuoja su tokiomis pačiomis vertybėmis.',
	'LBL_DUPLICATION_FAILURE_FROM_WEBFORMS' => 'Šie %s negali būti išsaugoti nuo „%s“ žiniatinklio formų, nes kiti %s egzistuoja su tokiomis pačiomis vertybėmis.',
	'LBL_DUPLICATION_FAILURE_FOR_ADMIN' => 'Galite %s norėdami keisti pasikartojančias prevencijos taisykles.',
	'LBL_DUPLICATION_FAILURE_FOR_NON_ADMIN' => 'Susisiekite su administratoriumi, kad galėtumėte peržiūrėti taisyklių kopijas',
	'LBL_DUPLICATE_RECORD_LISTS' =>'Duplicate %s(s) :',
	'LBL_COLUMNS_ADDED'=>'%s sulpeliai pridėti',
	'LBL_SHOW_ALL'=>'Rodyti viską',
	'LBL_LanguageEditor_WEBTITLE' => 'Žymių redaktorius',
	'LBL_TAX_CALCULATIONS_WEBTITLE' => 'Mokesčių valdymas',
	'LBL_Tags_WEBTITLE' => 'Mano žymos',
	'LBL_HIDE' => 'Paslėpti',
	'LBL_PRINT' => 'Spausdinti',
	'LBL_FORWARD' => 'Persiųsti',
	'LBL_NO_DEDUCTED_TAX'=>'Nėra atskaičiuotų mekesčių',
	'LBL_CLICK_TO_CONFIGURE'=>'Pauskite čia jeigu norite sukonfiguruoti',
	'LBL_KANBAN_VIEW_INFO' => '„Kanban“ vaizdas rodo tik tas galimybes, kurios atitinka šio sąrašo sąlygas',
	'LBL_CUSTOM_FIELDS_MAX_LIMIT' => 'Galite pridėti ne daugiau kaip %s pasirinktinų laukų',
	'LBL_EXCEEDED_MODULE_RECORD_LIMIT' => '%s įrašų limitas (%s) viršytas',
	'LBL_EXCEEDED_MODULE_RECORD_LIMIT_TEXT' =>'Mes nustatėme, kad turite daugiau nei %s įrašų %s. <br> Viršijamas šio leidimo didžiausia riba. <br> Pašalinkite perteklinius įrašus ir bandykite dar kartą',
	'LBL_TEMPLATE_INFO_PART1'=>'Norėdami pamatyti visus šablonus ar kitų modulių šablonus, įveskite modulio pavadinimą arba „Visi“ modulio pavadinimo paieškos laukelyje.', 
	'LBL_TEMPLATE_INFO_PART2'=>'Jei gavėjo lauke „KAM“ nėra tokio paties modulio kaip ir šablono, stebėjimas nebus įjungtas tiems gavėjams, o jungtiniai laukai nebus sujungti.',
	'LBL_HIDDEN_BECAUSE_OF_DEPENDENCY' => 'Laukas yra paslėptas dėl priklausomybės taisyklės',
	'MAILCHIMP_REVOKE_ACCESS_MESSAGE' => 'Paspaudus šią parinktį pašalinsite esamą „MailChimp“ autentifikavimą. Jis neištrins jokių jau sinchronizuotų įrašų.',
	// Added for Event Forms
	'LBL_VIEW_ANSWERS' => 'Peržiūrėti atsakymus',
	'LBL_ANSWERS' => 'Atsakymai',

	//Default sort order translations
	'LBL_DEFAULT_SORT_ORDER' => 'Numatytas rūšiavimo stulpelis ir rūšiavimo tvarka',
	'LBL_SELECT_COLUMN' => 'Pasirinkite stulpelį',
	'LBL_SELECT_SORT_ORDER' => 'Pasirinkite rikiavimo tvarką',
	'LBL_ASCENDING' => 'Didėjimo tvarka',
	'LBL_DESCENDING' => 'Mažėjimo tvarka',
	'LBL_DEFAULT_SORT_MESSAGE' => 'Sąrašas visada yra rūšiuojamas pagal šį stulpelį pagal nutylėjimą kiekvienai naujai vartotojo sesijai.',
	'LBL_QUEUED' => 'Eilėje',
	// End
	//Added for Inbox
	'LBL_EMAILS'=>'El. laiškai',
	'LBL_CONVERSATIONS'=>'Pokalbiai',
	'LBL_FROM_DISABLED_MESSAGE'=>'Išsiuntimo serverio nustatymų puslapyje pasirinktas pašto serveris neleidžia keisti „Nuo“ adreso.',
	// End
	'LBL_MODULE_MANDATORY' => 'Modulis yra privalomas',
	'Online' => 'Prisijungęs',
	'Busy' => 'Užimtas',
	'LBL_BETA'=>'„BETA“',
	'JS_SHARED_WITH'=>'Pasidalino su',
	 'LBL_REPLY_TO' =>'Atsakyti',
	'LBL_MODULE_ASSIGNMENT_RULES' => '%sPriskyrimo taisyklės ',

	'LBL_RECENT_UPDATES' => 'Naujausi Atnaujinimai',
	'LBL_VIEW_UPDATES_IN_DETAIL' => 'Skaityti daugiau ...',
	'LBL_DEFAULT_DASHBOARD_TOOLTIP'=>'Padarykite šį skydelį kaip numatytą, pertvarkydami jį kaip pirmąjį skirtuką!',
	'LBL_RELATED_MODULES_PERMISSION_DENIED' => 'Related modules permission is denied',
	'LBL_RECORD_PERMISSION_DENIED' => 'Record permissions denied',
	'LBL_MASS_SELECT' => 'Mass Select',
);

$jsLanguageStrings = array(
	'JS_EMAIL_SERVER_CONFIGURATION' => 'Sukonfigūruokite savo siunčiamų laiškų serverį nuostatose',
	'JS_SMS_SERVER_CONFIGURATION' => 'Sukonfigūruokite savo SMS paslaugos teikėją informavimo SMS žinutėmis nuostatose',
	'JS_PLEASE_SELECT_ONE_RECORD' => 'Pasirinkite bent vieną įrašą',
	//dropdown categary
	'JS_USERS' => 'Vartotojai',
	'JS_GROUPS' => 'Grupės',
	'JS_ALL' => 'Visi',
	//Validation Error Message
	'JS_PLEASE_ENTER_VALID_VALUE' => 'Įveskite teisingą vertę',
	'JS_PLEASE_ENTER_VALID_TAG_NAME' => 'Įverskite teisingą žymos pavadinimą',
	'JS_TAG_SAVED_SUCCESSFULLY' => 'Žyma išsaugota sėkmingai',
	'JS_PLEASE_ENTER_VALID_EMAIL_ADDRESS' => 'Įveskite galiojantį el. pašto adresą',
	'JS_CONTAINS_ILLEGAL_CHARACTERS' => 'Turi negalimų simbolių',
	'JS_PHONE_NUMBER_LENGTH_EXCEEDED' => 'Telefono numeris viršija galimą skaitmenų skaičių',
	'JS_ACCEPT_POSITIVE_NUMBER' => 'Leidžiami tik teigiami skaičiai',
	'JS_ACCEPT_WHOLE_NUMBERS' => 'Priima tik sveikus skaičius',
	'JS_VALUE_SHOULD_BE_GREATER_THAN_ZERO' => 'Reikšmė turi būt didesnė už nulį',
	'JS_NUMBER_SHOULD_BE_LESS_THAN_32' => 'Skaičius turi būti mažesnis nei 32',
	'JS_PLEASE_ENTER_VALID_DATE' => 'Įveskite galiojančią datą',
	'JS_PLEASE_ENTER_VALID_TIME' => 'Įveskite galiojantį laiką',
	'JS_INVALID_PAGE_NUMBER' => 'Netinkamas puslapio numeris',
	'JS_SUBJECT_VALUE_CANT_BE_EMPTY' => 'Temos reikšmė negali būti tuščia',
	'JS_PERCENTAGE_SHOULD_BE_LESS_THAN_100' => 'Procentinė reikšmė negali viršyti 100',


	'INVALID_NUMBER_OF' => 'Netinkamas kiekis: ',
	'INVALID_NUMBER' => 'Netinkamas numeris',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Ar tikrai norite pašalinti?',

	'OVERWRITE_EXISTING_MSG1' => 'Pakeisti dabartinį adresą pažymėtuoju',
	'OVERWRITE_EXISTING_MSG2' => 'adreso informacija?',
	'SINGLE_Accounts' => 'Organizacija',
	'SINGLE_Contacts' => 'Adresatas',
	'SINGLE_Project' => 'Projektas',
	'SINGLE_ProjectMilestone' => 'Projekto etapas',

	'LBL_DELETE_CONFIRMATION' => 'Ar tikrai norite pašalinti?', // This is added as duplicate as we need to show different message for different modules. Ex:Accounts has different message
	'LBL_UNLINK_CONFIRMATION' => 'Ar tikrai norite atsieti?',
	'LBL_DELETE_USER_CONFIRMATION' => 'Pašalinus naudotoją, jis bus pažymėtas kaip neaktyvus, nebegalės prisijungti, ir jam nebebus galima priskirti jokių naujų įrašų. Ar tikrai norite pašalinti?',
	'LBL_DELETE_CONFIRMATION_NOTE' => 'Pastaba: ištrinti įrašai bus saugomi šiukšlių dėžėje ir išvalomi po %s dienų',
	'LBL_MASS_DELETE_CONFIRMATION' => 'Ar tikrai norite pašalinti pasirinktus įrašus?',
	'JS_LBL_SAVE' => 'Įrašyti',
	'JS_LBL_CANCEL' => 'Atsisakyti',
	'JS_DUPLICTAE_CREATION_CONFIRMATION' => 'Organizacija tokiu pavadinimu jau egzistuoja. Ar norite sukurti dar vieną tokį pat įrašą?',

	'SHOULD_BE_LESS_THAN_TODAY' => 'Turi įvykti iki šiandien',
	'JS_PLEASE_SELECT_ATLEAST_ONE_OPTION' => 'Pasirinkite bent vieną parinktį',
	'JS_SELECT_MODULE' => 'Pasirinkite modulį',
	'JS_PLEASE_SELECT_ATLEAST_ONE_MANDATORY_FIELD' => 'Pasirinkite bent vieną privalomą lauką',
	'JS_SELECT_MODULE' => 'Pasirinkite modulį',
	'JS_PLEASE_ENTER_INTEGER_VALUE' => 'Įrašykite sveiką skaičių',
	'JS_PLEASE_ENTER_DECIMAL_VALUE' => 'Įrašykite dešimtainę vertę',
	'JS_PLEASE_ENTER_POSITIVE_DECIMAL_VALUE' => 'Įrašykite teigiamą dešimtinę vertę',

	'JS_START_TIME_SHOULD_BE_GREATER_THAN_CURRENT_TIME' => 'Pradžios laikas turi būti vėlesnis negu dabartinis laikas',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'turi būti ankstesnė nei einamoji data',
	'JS_SHOULD_BE_GREATER_THAN_CURRENT_DATE' => 'turi būti vėlesnė nei einamoji data',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'turi būti daugiau arba lygu',
	'JS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO' => 'turi būti mažiau arba lygu',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'turi būti daugiau arba lygu',
	'JS_CURRENT_DATE' => 'Esama data',
	'JS_PERCENTAGE_VALUE_SHOULD_BE_LESS_THAN_100' => 'Procentinė reikšmė negali viršyti 100',
	'JS_ACCEPT_ONLY_NUMBER' => 'Leidžiami tik skaičiai',
	'JS_THIS_FILE_HAS_ALREADY_BEEN_SELECTED' => 'Šis failas jau buvo pasirinktas',
	'JS_MAX_FILE_UPLOAD_EXCEEDS' => 'viršytas didžiausias leistinas įkeliamo failo dydis',
	'JS_THIS_DOCUMENT_HAS_ALREADY_BEEN_SELECTED' => 'Šis dokumentas jau buvo pridėtas',
	'JS_LIST_EXIST' => 'Toks sąrašas jau egzistuoja',


	//Roles
	'JS_FAILED_TO_SAVE' => 'Nepavyko įrašyti pakeitimų serveryje',

	//Import Translations
	'JS_IMPORT_FILE_CAN_NOT_BE_EMPTY' => 'Importuojamas failas negali būti tuščias',
	'JS_PLEASE_SELECT_ONE_FIELD_FOR_MERGE' => 'Pasirinkite bent vieną atitinkamą lauką',
	'JS_MAP_NAME_CAN_NOT_BE_EMPTY' => 'Susiejimo pavadinimas turi būti įrašytas',
	'JS_MAP_NAME_ALREADY_EXISTS' => 'Toks susiejimo vardas jau egzistuoja',
	'JS_SELECT_FILE_EXTENSION' => 'Pasirinkite failą su šiuo prievardžiu:',
	'JS_UPLOADED_FILE_SIZE_SHOULD_BE_LESS_THAN' => 'Įkeliamas failas turi būti mažesnis nei',
	'JS_UPLOADED_FILE_SIZE_EXCEEDS' => 'Įkeltas failas viršija',
	'JS_PLEASE_SPLIT_FILE_AND_IMPORT_AGAIN' => 'Padalinkite failą į mažesnius ir importuokite dar kartą.',
	'JS_FIELD_MAPPED_MORE_THAN_ONCE' => 'Laukas susietas daugiau nei vieną kartą',
	'JS_MAP_MANDATORY_FIELDS' => 'Susiekite privalomus laukus',
	'JS_MAP_MERGE_CRITERIA_FIELDS' => 'Susiekite atitinkamus laukus',
	'JS_PLEASE_ENTER_SOME_VALUE' => 'Įrašykite ieškomą tekstą',
	'JS_VCF_FILE_IMPORT_WARNING' => 'Pasirinkote „VCF“ failą. Iš „VCF“ failo galima importuoti tik kontaktus. Norėdami importuoti šį failą, inicijuokite importą iš kontaktinio modulio',
	'JS_ICS_FILE_IMPORT_WARNING' => 'Jūs pasirinkote „ICS“ failą. Iš „ICS“ failo galima importuoti tik kalendorių. Norėdami importuoti šį failą, inicijuokite importą iš kalendoriaus modulio',
	//Select2 elements validation message
	'JS_YOU_CAN_SELECT_ONLY'=> 'Galima pasirinkti tik',
	'JS_ITEMS' => 'elementai',

	'JS_LBL_PERMISSION' => 'Laidimai',
	'JS_CHECK_FILE_INTEGRITY' => 'Patikrinti failų nepažeistumą',
	'JS_DUPLICATE_RECORD' => 'Dubliuoti įrašą',

	//advance filter checkbox type condition values
	'JS_IS_ENABLED' => 'įjungtas',
	'JS_IS_DISABLED' => 'išjungtas',

	'JS_PLEASE_ENTER_SOME_TEXT_FOR_COMMENT' => 'Įrašykite pastabos tekstą',
	'JS_LBL_COMMENT_VALUE_CANT_BE_EMPTY' => 'Pastaba negali būti tuščia',
	'JS_REQUIRED_FIELD' => 'Šis laukas yra privalomas',
	'JS_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Negalima pašalinti numatytojo valdiklio',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'turi būti ankstesnė nei einamoji data',
	'JS_NO_CREATE_OR_NOT_QUICK_CREATE_ENABLED' => 'Nėra teisių kurti arba neįgalintas greitasis kūrimas',

	//Image Action
	'LBL_IMAGE_DELETED_SUCCESSFULLY' => 'Paveikslas pašalintas sėkmingai',
	'LBL_IMAGE_NOT_DELETED' => 'Paveikslas nebuvo pašalintas',
	'LBL_YES' => 'Taip',
	'LBL_NO' => 'Ne',
	'AM' => 'AM',
	'PM' => 'PM',
	'JS_ERROR' => 'Klaida',
	'JS_INFORMATION' => 'Informacija',
	'JS_DO_NOT_HAVE_AN_EMAIL_ID' => 'neturi el. pašto',
	'NONE_OF_THE_FIELD_VALUES_ARE_CHANGED_IN_MASS_EDIT' => 'Per dauginį redagavimą jokių laukų reikšmės nepakeistos',

	//Notification messages for inventory module
	'JS_PLEASE_SELECT_AN_ACCOUNT_TO_COPY_ADDRESS' => 'Jei norite nukopijuoti adresą, pasirinkite organizaciją',
	'JS_PLEASE_SELECT_AN_CONTACT_TO_COPY_ADDRESS' => 'Jei norite nukopijuoti adresą, pasirinkite adresatą',
	'JS_SELECTED_ACCOUNT_DOES_NOT_HAVE_AN_ADDRESS' => 'Pažymėta organizacija neturi kopijuotino adreso',
	'JS_SELECTED_CONTACT_DOES_NOT_HAVE_AN_ADDRESS' => 'Pažymėtas adresatas neturi kopijuotino adreso',
	'JS_PLEASE_ENTER_PRIMARY_EMAIL_VALUE_TO_ENABLE_PORTAL_USER' => 'Jei norite įgalinti portalo naudotoją, įrašykite pagrindinį el. pašto adresą',
	'JS_PRIMARY_EMAIL_FIELD_DOES_NOT_EXISTS' => 'Nenurodytas pagrindinis el. pašto adresas. Jis būtinas portalo naudotojui įgalinti',

	//Tag Cloud validation messages
	'JS_PLEASE_ENTER_A_TAG' => 'Įveskite žymę',
	'JS_TAG_NAME_ALREADY_EXIST' => 'Tokia žymė jau egzistuoja',
	'JS_MAX_TAG_LENGTH_EXCEEDS' => 'Žymės ilgis viršija leistiną',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'Sukūrę šį įrašą, nebeturėsite leidimo jį peržiūrėti. Ar norite tęsti?',
	'JS_NO_RECORDS_RELATED_TO_THIS_FILTER' => 'Įrašų, susijusių su šiuo sąrašu, nėra',

	// Calendar Reminder popup
	'JS_START_DATE_TIME' => 'Pradžios data ir laikas',
	'JS_END_DATE_TIME' => 'Pabaigos data ir laikas',
	'JS_POSTPONE' => 'Atidėti',
	'JS_MESSAGE' => 'Pranešimas',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'Sukūrę šį įrašą, nebeturėsite leidimo jį peržiūrėti. Ar norite tęsti?',

	//Settings page translations
	'JS_SUCCESSFULLY_PINNED' => 'Nuoroda pridėta sėkmingai',
	'JS_SUCCESSFULLY_UNPINNED' => 'Nuoroda pašalinta sėkmingai',
	'JS_SHORTCUT_ALREADY_ADDED' => 'Ši nuoroda jau pridėta',
	'JS_MESSAGE' => 'Pranešimas',
	'JS_MASS_EDIT_LIMIT' => 'Dauginis redagavimas gali būti atliekamas su ne daugiau kaip 500 įrašų vienu metu',

	//Module Manager
	'JS_MODULE_ENABLED' => 'Modulis įjungtas',
	'JS_MODULE_DISABLED' => 'Modulis išjungtas',

	//Crom tasks
	'JS_VALUE_SHOULD_NOT_BE_LESS_THAN' => 'Periodinis darbas neturi kartotis rečiau nei',
	'JS_MINUTES' => 'min.',

	//PickList
	'JS_ITEM_RENAMED_SUCCESSFULLY' => 'Elementas pervadintas sėkmingai',
	'JS_ITEM_ADDED_SUCCESSFULLY' => 'Elementas pridėtas sėkmingai',
	'JS_NO_ITEM_SELECTED' => 'Nepasirinktas elementas',
	'JS_MORE_THAN_ONE_ITEM_SELECTED' => 'Pasirinktas daugiau nei vienas elementas',
	'JS_ITEMS_DELETED_SUCCESSFULLY' => 'Elementai pašalinti sėkmingai',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Rasti du vienodi šios reikšmės įrašai',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'Suliejimui turite pasirinkti tos pačios grupės įrašus.',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => 'Pasirinkite bent du įrašus suliejimui',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => 'Galima pasirinkti iki 3 įrašų.',
	//Notification message for dashboard widget delete
	'JS_ARE_YOU_SURE_TO_DELETE_WIDGET' => 'Ar tikrai norite ištrinti valdiklį - %s?',
	'JS_ARE_YOU_SURE_TO_DELETE_DASHBOARDTAB' => 'Ar tikrai norite ištrinti šį skydelio skirtuką - %s?',
	'JS_TABS_LIMIT_EXCEEDED' => 'Apgailestaujame!  Negalite pridėti daugiau nei 10 stulpelių',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Rasti du vienodi šios reikšmės įrašai',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'Suliejimui turite pasirinkti tos pačios grupės įrašus.',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => 'Pasirinkite bent du įrašus suliejimui',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => 'Galima pasirinkti iki 3 įrašų.',
	'JS_TOTAL_RECORDS' => 'Iš viso įrašų',
	'JS_PAGE_NOT_EXIST' => 'Puslapis neegzistuoja',
	'JS_YOU_ARE_IN_PAGE_NUMBER' => 'Esate puslapyje Nr.',

	//More currencies message
	'JS_PLEASE_ENABLE_BASE_CURRENCY_FOR_PRODUCT' => 'Nustatykite bazinę valiutą prekei',
	'JS_PLEASE_SELECT_BASE_CURRENCY_FOR_PRODUCT' => 'Pasirinkite bazinę valiutą prekei',
	'JS_BASE_CURRENCY_CHANGED_TO_DISABLE_CURRENCY' => 'Bazinė valiuta turi būti pakeista, kad būtų išjungta',

	//Delete Records message
	'JS_RECORDS_ARE_GETTING_DELETED' => 'Įrašai šalinami',
	'JS_RECORD_GETTING_DELETED' => 'Įrašas šalinamas',
	'JS_NO_RESULTS_FOUND' => 'Rezultatų nerasta',

	'JS_RECORDS TRANSFERRED SUCCESSFULLY' => 'Įrašų nuosavybė sėkmingai perkelta',

	//TextSearch Language String
	'LBL_SEARCHING' => 'Ieškoma',
	'JS_RECORDS_TRANSFERRED_SUCCESSFULLY' => 'Įrašų savininkystė sėkmingai pakeista.',
	'JS_USER_DELETED_SUCCESSFULLY' => 'Vartotojas sėkmingai pašalintas',

	'JS_MAX_RECORDS_LIMIT' => 'Maksimalus įrašų kiekis spausdinimui:',
	'JS_USER_EXISTS' => 'Toks naudotojas jas egzistuoja',
	'JS_REENTER_PASSWORDS' => 'Įveskite slaptažodžius iš naujo',
	'LBL_SIGN_IN_AS_USER'=>'Prisijungdami kaip kitas vartotojas nutraukia dabartinį seansą. Ar tikrai norite tęsti?',
	'JS_REENTER_PASSWORDS' => 'Įveskite slaptažodžius iš naujo',
	'SINGLE_Vendors' => 'Tiekėjas',

	//Feedback on removing old version
	'JS_PLEASE_GIVE_YOUR_FEEDBACK' => 'Prašome užpildyti atsiliepimą',
	'JS_PBX_CALL_FROM' => 'Skambutis iš',
	'JS_PBX_INCOMING_CALL' => 'Įeinantis skambutis',
	'JS_PBX_OUTGOING_SUCCESS'=>'Pick up the extension receiver to dial the number',
	'JS_PBX_OUTGOING_FAILURE'=>'Skambutis nepavyko',
	'JS_PBX_FILL_ALL_FIELDS'=>'Prašome užpildyti visus laukus',
	'JS_PBX_CAMPAIGN_NAME' => 'Kampanijos pavadinimas',
	'JS_PBX_CAMPAIGN_NUMBER' => 'Kampanijos numeris',
	'JS_MIN_SEARCH_KEY_LENGTH' => 'Paieškos raktažodis turi būti bent 3 simboliai',
	'JS_NO_MATCH' => 'Jokių atitinkančių įrašų nerasta.',
	'JS_PBX_OUTGOING_CALL' => 'Išeinantis skambutis',
	'JS_PBX_CALL_TO' => 'Skambinta į',
	'JS_REQUIRED' => 'Privaloma',
	'JS_PHONE_NUMBER' => 'Telefono numeris',
	'JS_NO_CREATE_PERMISSION' => 'Prieš pradėdami kurti įrašą turite atsiliepti',
	'HelpDesk' => 'Užduočių kortelės',
	'Potentials' => 'Galimybės',
	'JS_CALL_NOT_ANSWERED_UPDATE_PERMISSION' => "Prieš pradėdami įrašo susiejimą turite atsiliepti", 
	'JS_CALL_NOT_ANSWERED' => "Prieš pradėdami kažkokį veiksmą turite atsiliepti",
	// ends
	'JS_NO_EDIT_PERMISSION' => 'Jūs neturite leidimo redaguoti šio įvykio',

	//Google Synchronization
	'SYNC_REMOVED_SUCCESSFULLY' => '„Google“ sinchronizavimas sėkmingai pašalintas.',
	'REMOVE_SYNCHRONIZATION_MESSAGE' => 'Paspaudus šią nuorodą bus pašalinta esama „Gmail“ autentifikacija. Ji neištrins jokių jau sinchronizuotų įrašų.',
	'REMOVE_SYNCHRONIZATION' => 'Panaikinti sinchronizaciją',
	'FIELD_MAPPING' => 'Laukų susiejimas',
	'LBL_SYNC_BUTTON' => 'Sinchronizuoti dabar',
	'LBL_SYNCRONIZING' => 'Sinchronizuojama…',
	'LBL_NOT_SYNCRONIZED' => 'Dar nesate sinchronizavę',
	'LBL_FIELD_MAPPING' => 'Laukų susiejimas',

	'LBL_RESTORE_CONFIRMATION' => 'Ar tikrai norite atkurti šį vartotoją?',
	'LBL_DELETE_USER_PERMANENT_CONFIRMATION' => 'Pašalinus, naudotojo nebebus galima atkurti. Ar tikrai norite negrįžtamai pašalinti šį naudotoją?',

	'LBL_LANGUAGE_LABEL_VALIDATION' => 'Etiketės vertė negali būti tuščia. Turite įvesti tam tikrą vertę.',
	'JS_CHANGES_WILL_BE_LOST' => 'Jūsų pakeitimai nebus įrašyti!',
	'JS_RECORD_DELETED' => 'Įrašas pašalintas',
	'JS_NO_DELETE_PERMISSION' => 'Neturite leidimo ištrynti',
	'JS_CONFIRM_MARK_AS_HELD' => 'Ar tikrai norite pažymėti įvykį kaip įvykusį?',
	'JS_CONFIRM_MARK_AS_COMPLETED' => 'Ar tikrai norite pažymėti užduotį kaip įvykdytą?',
	'JS_TODO_MARKED_AS_COMPLETED' => 'Užduotis pažymėta kaip įvykdyta',
	'JS_EVENT_MARKED_AS_HELD' => 'Įvykis pažymėtas kaip įvykęs',
	'JS_FUTURE_EVENT_CANNOT_BE_MARKED_AS_HELD' => 'Ateities įvykis negali būti pažymėtas kaip įvykęs',
	'JS_PERMISSION_DENIED' => 'Leidimas nesuteiktas',
	'LBL_SMS_MAX_CHARACTERS_ALLOWED' => 'Žinutėje leidžiama ne daugiau kaip 160 simbolių',
	'JS_VIEWNAME_ALERT' => 'Daugiausia 40 simbolių leidžiama sąrašo pavadinimui',
	'JS_EXCEEDS_MAX_UPLOAD_SIZE' => 'Viršytas didžiausias įkėlimo dydis',
	'JS_FUTURE_EVENT_CANNOT_BE_HELD' => 'Negali būti įvykęs ateityje',
	'LBL_WARNING' => 'Įspėjimas',
	'DELETE_USER_PERMANENT_WARNING' => 'Šalinant naudotoją negrįžtamai, visi jo priklausiniai, įskaitant komentarus ir žurnalo įrašus, bus priskirti nurodytam naudotojui.',
	'JS_DECIMAL_SEPARATOR_AND_GROUPING_SEPARATOR_CANT_BE_SAME' => 'Trupmenos skirtukas ir grupių skirtukas negali sutapti',
	'JS_FUTURE_EVENT_CANNOT_BE_HELD' => 'Negali būti įvykęs ateityje',
	'JS_CLOSE' => 'Uždaryti',

	// For Line Iteam Currency Symbol select while Import
	'JS_CURRENCY_TOOLTIP_CONTENT_TITLE' => 'Eilutės daikto valiuta',
	'JS_CURRENCY_TOOLTIP_CONTENT_MESSAGE' => 'Jei norite importuoti valiutos vertes eilutėse, „Vtiger“ šį nustatymą naudos kaip šią valiutą. Bet kokios valiutos vertės už eilutės elementų lentelių bus pasirinktos pagal naudotojo pasirinkta valiuta (pasirinkta „Mano nuostatos“).',
	'LBL_CANT_SELECT_CONTACT_FROM_LEADS' => 'Negalima pasirinkti susijusių kontaktų, susijusių su potencialiais klientais',
	'JS_TRY_LATER' => 'Prašome pabandyti vėliau!',
	'JS_FILE_NAME' => 'Failo pavadinimas',
	'JS_EXTERNAL_FILE_URL' => 'Failo „URL“',
	'JS_PLEASE_SELECT_A_FILE' => 'Pasirinkite failą',
	// SMSNotifier Phone Format Warning
	'JS_PHONEFORMAT_ERROR' => 'Patikrinkite, ar telefono numeris yra tarptautiniame E.164 formate su priedeliu "+" ir šalies kodu pvz.: +1 415 599 2671',

	// Leads and Potentials Field Mapping
	'JS_NONE' => 'Nėra',
	'JS_IS_ALREADY_BEEN_MAPPED' => 'Jau buvo susietas',
	'JS_CANT_MAP' => 'Nepavyko susieti',
	'JS_WITH' => 'su',
	'JS_MAPPING_DELETED_SUCCESSFULLY' => 'Susiejimas sėkmingai pašalintas',

	//JS Field Type Translation
	'JS_phone' => 'Telefonas',
	'JS_picklist' => 'Parinkčių sąrašas',
	'JS_email' => 'El. paštas',
	'JS_text' => 'Eilutė',
	'JS_currency' => 'Valiuta',
	'JS_multiSelectCombo' => 'Daugiareikšmis jungtinis langelis',
	'JS_time' => 'Laikas',
	'JS_textArea' => 'Teksto vieta',
	'JS_url' => '„URL“',
	'JS_string' => 'Eilutė',
	'JS_checkBox' => 'Žymimasis langelis',
	'JS_date' => 'Data',
	'JS_decimal' => 'Dešimtainė',
	'JS_percent' => 'Procentas',
	'JS_skype' => '„Skype“',
	'JS_None' => 'Nėra',
	'JS_integer' => 'Sveikasis skaitmuo',
	'JS_double' => 'Dešimtainė',
	'JS_reference' => 'Nuoroda',
	'JS_image' => 'Atvaizdas',

	// AutoFill Overwriting message
	'JS_OVERWRITE_AUTOFILL_MSG1' => 'Ar norėtumėte perrašyti esamą',
	'JS_OVERWRITE_AUTOFILL_MSG2' => 'su pažymėtu',

	//Demo Data Module Translatios
	'JS_ADD_DEMO_DATA_CONFIRMATION'=> 'Ar tikrai norite pridėti demonstracinius įrašus į visus modulius?',
	'JS_ADD_DEMO_DATA_INFO'=> 'Demonstracinius įrašus galima ištrinti paspaudus mygtuką "Išvalyti demonstracinius duomenis".',
	'JS_CLEAR_DEMO_DATA_CONFIRMATION'=> 'Ar tikrai norite išvalyti demonstracinius duomenis visuose moduliuose?',
	'JS_CLEAR_DEMO_DATA_INFO'=> 'Demonstraciniai įrašai gali būti įtraukti paspaudę mygtuką "Pridėti demomenstracinius duomenis".',
	'JS_DEMO_DATA_GETTING_POPULATED'=> 'Įkeliami demonstraciniai duomenys, prašome palaukti...',
	'JS_DEMO_DATA_GETTING_CLEARED'=> 'Šalinami demonstraciniai duomenys, prašome palaukti...',
	'JS_DEMO_DATA_ADDED' => 'Demonstraciniai duomenys pridėti prie visų modulių.',
	'JS_DEMO_DATA_CLEARED' => 'Demonstraciniai duomenys pašalinti iš visų modulių.',
	'JS_HOME_DASH_BOARD_CLEAR_INFO'=>'Pastaba: demonstracinius duomenis galite iš naujo įjungti per',
	'JS_SETTINGS_PATH'=>'Nustatymai > Konfigūracija > Konfigūracijos redaktorius.',
	'JS_PRINT' => 'Spausdinti',
	'JS_SAVE_AS_IMAGE' => 'Išsaugoti kaip atvaizdą',
	'JS_DIRECTORY_IS_EMPTY' => 'Katalogas yra tuščias',
	'JS_PLEASE_SELECT_AN_RELATED_TO_COPY_ADDRESS' => 'Prašome pasirinkti užklausos arba kontaktų modulį iš kurio kopijuoti adresą',
	'SINGLE_Leads' => 'Užklausa',
	'JS_SELECTED_LEAD_DOES_NOT_HAVE_AN_ADDRESS' => 'Pasirinktoje užklausoje nėra adreso kurį būtu galima kopijuoti',
	'JS_INVALID_EMAILS' => 'Netinkamas el. pašto adresas',
	'JS_DIRECTORY_IS_EMPTY' => 'Katalogas yra tuščias',
	'JS_NO_LINE_ITEM' =>'Eilutės elementai negali būti tušti.',
	'JS_INTERNAL_COMMENT' => 'Vidinis komentaras',
	'JS_INTERNAL_COMMENT_INFO' => 'Komentarus matys tik „CRM“ vartotojai, jei įjungtas vidinis komentaras. Jei norite pranešti klientams (konfigūruojamomis darbo eigomis ar klientų portale) palikite šį žymimąjį laukelį išjungtą',

	'JS_NO_TAXES_EXISTS' => 'Mokesčiau neegzistuoja',
	'JS_CONFIRM_TAXES_AND_CHARGES_REPLACE' => 'Ar norite atnaujinti mokesčių ir rinkliavos sumas, atitinkančias pasirinktą regioną?',
	'JS_PRINTTEMPLATEMODULE_DISABLED' => 'Modulis spausdinti šablonus yra išjungtas. Neįmanoma atlikti operacijos',
	'JS_SENT_FOR_SIGNATURE' => 'Išsiūsta pasirašymui',
	'JS_FAILED_TO_SEND_FOR_SIGNATURE' => 'Nepavyko išsiūsti pasirašymui',
	'JS_SUITABLE_VTIGER_FIELD_NOT_AVAILABLE_FOR_MAPPING' => 'Tinkamas „Vtiger“ laukas nėra prieinamas susiejumams',
	'JS_SAVED_SUCCESSFULLY' => 'Nustatymai išsaugoti sėkmingai',
	'phone' => 'Telefonas',
	'email' => 'El. paštas',
	'url' => 'Nuoroda',
	'home' => 'Namų',
	'work' => 'Darbo',
	'custom' => 'Tinkintas',
	'mobile' => 'Mobilus',
	'main' => 'Pagrindinis',
	'work_fax' => 'Faksas',
	'home_fax' => 'Namų faksas',
	'pager' => 'Pranešimų gaviklis',
	'profile' => 'Profilis',
	'blog' => 'Tinklaraštis',
	'home-page' => 'Asmeninė svetainė',
	'address' => 'Adresas',

	// Cron
	'JS_NONE_OF_THE_VALUES_ARE_CHANGED' => 'Nė viena vertė nėra pakeista',
	'JS_REMOVE_SYNC_CONFIRMATION' => 'Sinchronizavimo pašalinimas, pašalins esamą autentifikavimą, jis neištrins sinchronizuotų įrašų. Jei vėl sinchronizuosite tą pačią „Google“ paskyrą, sukursite pasikartojančius įrašus. Ar tikrai norite pašalinti sinchronizavimą?',

	//Recipient preferences labels
	'JS_LBL_GETTING_RECIPIENT_PREFS' => 'Gaunamos gavėjo nuostatos...',
	'JS_LBL_SAVING_PREFERENCES' => 'Išsaugomi nustatymai...',
	// Social Module Strings
	'JS_PLEASE_WAIT' => 'Prašome palaukti…',
	'JS_SOCIAL_FIELD_ERROR' => 'laukas yra privalomas',
	// Twitter Specific
	'JS_ADD_FAVOURITE_SUCCESS_MSG' => '„Tweet“ pridėtas į mėgstamiausių sąrašą sėkmingai',
	'JS_UNDO_FAVOURITE_SUCCESS_MSG' => '„Tweet“ pašalintas iš mėgstamiausių sąrašo sėkmingai',
	'JS_UNDO_RETWEET_SUCCESS_MSG' => '„Tweet“ atšauktas sėkmingai',
	'JS_STATUS_UPDATE_SUCCESS_MSG' => 'Atnaujinta sėkmingai',
	'JS_TWEET_DELETE_MSG' => 'Būsena pašalinta sėkmingai',
	'JS_INVALID_TWITTER_HANDLER_NAME' => 'Neteisingas „Twitter“ vartotojo vardas',
	'JS_RELATION_ADDED_SUCESSFULLY' => 'Santykis sėkmingai pridėtas',
	'JS_FAILED_TO_ADD_RELATION' => 'Nepavyko pridėti santykio',
	'JS_SOCIAL_POST_DELETE_CONFIRMATION' => 'Ar tikrai norite pašalinti?',
	'JS_EVENT_OR_TODO_ADDED_SUCCESS_MSG' => 'Įvykis/užduotis pridėta sėkmingai',
	'JS_LEAD_ADDED_SUCCESS_MSG' => 'Užklausa pridėta sėkmingai',
	'JS_OPPORTUNITY_ADDED_SUCESS_MSG' => 'Galimybė pridėta sėkmingai',
	'JS_TICKET_ADDED_SUCESS_MSG' => 'Užduoties kortelė pridėta sėkmingai',
	'JS_CASE_ADDED_SUCESS_MSG' => 'Byla pridėta sėkmingai',
	'JS_SELECT_OPTION' => 'Pažymėkite parinktį',

	'JS_LOADING_PLEASE_WAIT' => 'Įkeliama... Prašome palaukti...',
	'JS_SAVING_PLEASE_WAIT' => 'Išsaugoma... Prašome palaukti...',
	'JS_DUPLICATE_EMAILS_PLEASE_CHECK' => 'Pasikartojantys el. pašto adresai. Prašome patikrinti',
	'JS_USER_EXISTS' => 'Toks naudotojas jas egzistuoja',
	'JS_ALERT' => 'Įspėjimas',
	'JS_SUCCESS' => 'Atlikta',
	'JS_REMOVE_MASS_TAG_WARNING' => 'Ar tikrai norite pašalinti %s žymą pasirinktiems įrašams',
	'JS_VIEW_ALREADY_EXISTS' => 'Rodinys jau egzistuoja',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE' => 'Įveskite vertę diapazone',
	'JS_UPLOAD' => 'Įkelti',
	'JS_TODO_ADDED_SUCCESS_MSG' => 'Užduotis pridėta sėkmingai',
	'JS_EVENT_ADDED_SUCCESS_MSG' => 'Įvykis pridėtas sėkmingai',
	'JS_ACTIVE' => 'Aktyvus',
	'JS_SNOOZED' => 'Atidėtas',
	'JS_INVALID_URL' => 'Neteisinga nuoroda',
	'JS_MAX_ALLOWED_CHARACTERS' => 'Maksimalus leistinas simbolių skaičius yra',
	'JS_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Ar tikrai norite pašalinti?',
	'JS_TAB_LABEL_EXCEEDS_CHARS' => 'Skirtuko etiketės ilgis turėtų būti mažesnis nei %s simboliui',
	'JS_STARRED' => 'Nebesekti',
	'JS_NOT_STARRED' => 'Sekti',
	//Tags
	'JS_NO_TAG_EXISTS' => 'Žymų nėra' ,
	//help wizard
	'JS_HELP_AND_SUPPORT' => 'Pagalba ir palaikymas',
	'JS_WHAT_DO_YOU_NEED_HELP_WITH' => 'Kuo galėtume jums padėti?',
	'JS_SUBMIT' => 'Pateikti',

	/** Vtiger7 translations **/
	'JS_ADD_MAX_15_ITEMS' => 'Galite pridėti tik 15 elementų',
	'SINGLE_SLA' => '„SLA“',

	'JS_DEFAULT_ENABLED' => 'Numatytas įjungtas',
	'JS_DEFAULT_DISABLED' => 'Numatytas išjungtas',
	'JS_EDIT_FIELDS' => '%s laukai ir išdėstymas',
	'JS_MORE_VTIGER' => '„Vtiger“ sistemoje yra daugiau nesinchronizuotų įrašų',
	'JS_MORE_GOOGLE' => '„Google“ yra daugiau nesinchronizuotų įrašų',
	'JS_MORE_OFFICE365' => '„Office365“ yra daugiau nesinchronizuotų įrašų',
	'JS_TOKEN_EXPIRED' => 'Pasibaigė „Office365“ autentiškumo patvirtinimas. Paspauskite prisijungti, naudodami „Office365“ mygtuką, kad galėtumėte dar kartą patvirtinti.',
	'JS_EDIT_FIELDS' => '%s laukai ir išdėstymas',
	'JS_WISH_TO_PROCEED' =>"Ar tikrai norite tęsti?",
	'JS_SWITCH_TO_OLD_LOOK_CONFIRMATION_MESSAGE' => 'Kai kurios funkcijos, įskaitant pranešimus, piktogramų spalvas, įrašų sekimas, negalimi senoje versijoje. Galite grįžti į naują versiją pasirinkdami naują versiją iš viršutinio dešiniojo meniu.',
	'JS_PROCEED_OLD_VERSION' => 'Tęsti į seną versiją',
	'JS_STAY_WITH_NEW_VERSION' => 'Palikti naują versiją',

	//TimeAgo plugin Strings
	'JS_AGO' => 'prieš',
	'JS_FROM_NOW' => 'nuo dabar',
	'JS_LESSTHAN_A_MINUTE' => 'mažiau nei minutę',
	'JS_A_MINUTE' =>'minutė',
	'JS_MINUTES' => 'min.',
	'JS_AN_HOUR' => 'valanda',
	'JS_HOURS' => 'valandos',
	'JS_A_DAY' => 'diena',
	'JS_DAYS' => 'Dienos',
	'JS_A_MONTH' => 'mėnesis',
	'JS_MONTHS' => 'mėnesiai',
	'JS_A_YEAR' => 'Metai',
	'JS_YEARS' => 'Metai',
	'JS_TODAY' => 'šiandien',
	'JS_TOMORROW' => 'rytoj',
	'JS_YESTERDAY' => 'vakar',

	'JS_CREATE_TASK' => 'Sukurti užduotį',

	//Notifications
	'JS_MENTION_ATLEAST_ONE_USER' => 'Paminėti bent vieną vartotoją',
	'JS_LOADING' => 'Keliama...',
	'JS_CASE_ACCEPTED_SUCCESSFULLY' => 'Byla priimta sėkmingai',

	'JS_UPLOAD_SUCCESSFUL' => 'Failas įkeltas sėkmingai',
	'JS_UPLOAD_FAILED' => 'Failo įkelti nepavyko',
	'JS_FAILED_TO_UPLOAD_FILE' => 'Failo įkelti nepavyko',
	'JS_DOCUMENT_CREATED' => 'Dokumentas sukurtas',
	'JS_DOCUMENT_CREATION_FAILED' => 'Dokumento sukurti nepavyko',

	'JS_TEMPLATE_TEXT_EXCEEDS_LIMIT' => 'Šablono dydis viršija maksimalų leistiną 100 KB dydį. Pašalinkite kai kuriuos tekstus šablone ir dar kartą pabandykite',
	'JS_PLEASE_SELECT_IMAGE' => 'Pasirinkite atvaizdą',

	'JS_LBL_MY_PREFERENCES' => 'Mano nuostatos',
	'JS_LBL_MY_PREFERENCES_TEXT' => 'Konfigūruokite savo asmenines nuostatas, įskaitant laiko juostą, valiutą, datos formatą. Taip pat galite įkelti profilio nuotrauką iš „Mano nuostatos“.',
	'JS_LBL_HELP' => 'Pagalba',
	'JS_LBL_HELP_TEXT' => 'Spauskite pagalbos mygtuką, jei norite rasti vadovus, DUK, ir pasinaudokite išskleidžiamojo meniu pagalba, kad gautumėte pagalbos iš „Vtiger" palaikymo komandos',
	'JS_LBL_RESTART_TOUR' => 'Pakartoti kelionę su gidu',
	'JS_LBL_RESTART_TOUR_TEXT' => 'Spauskite čia norėdami vėl pradėti turą',
	'JS_GOOGLE_REMOVE_SYNC_CONFIRMATION' => 'Prieigos atšaukimas pašalins tik esamą „Google“ autentifikavimą, skirtą kontaktams, kalendoriui ir el. paštui, todėl neištrins sinchronizuotų įrašų. Jei vėl sinchronizuosite su ta pačia „Google“ paskyra, sukursite pasikartojančius įrašus. Ar tikrai norite atšaukti prieigą?',
	'JS_OFFICE_REMOVE_SYNC_CONFIRMATION' => 'Prieigos atšaukimas pašalins tik esamą „Office365“ autentifikavimą, skirtą kontaktams, kalendoriui ir el. paštui, todėl neištrins sinchronizuotų įrašų. Jei vėl sinchronizuosite su ta pačia „Office365“ paskyra, sukursite pasikartojančius įrašus. Ar tikrai norite atšaukti prieigą?',
	'JS_FOLLOW_RECORD' => 'Įrašas sekamas',
	'JS_FOLLOWING' => 'Sekami',
	'JS_UNFOLLOW_RECORD' => 'Įrašas nebesekamas',
	'JS_UNFOLLOWING' => 'Nebesekama',
	'JS_RECORD_CREATED' => 'Įrašas sukurtas',
	'JS_RECORD_UPDATED' => 'Įrašas atnaujintas',
	'JS_LIST_SAVED' => 'Sąrašas išsaugotas',
	'JS_TAB_DELETED' => 'pašalinta',
	'JS_TAB_RENAMED' => 'Pervardintas',
	'JS_TAB_REORDERED' => 'Perrikiuotas',
	'JS_RECIPIENT_PREFERENCES_SAVED' => 'Gavėjo nuostatos išsaugotos',
	'JS_TASK_ADDED' => 'Užduotis pridėta',
	'JS_MARKED_COMPLETED' => 'Žymėti kaip užbaigtą',
	'JS_TASK_PRIORITY_CHANGED' => 'Užduoties prioritetas pasikeitė',
	'JS_NO_PERMISSION_TO_MARK_AS_HELD' => 'Jūs neturite teisės pažymėti šį įvykį kaip praėjusį',
	'JS_TAG_ADDED' => 'Žyma pridėta',
	'JS_TAB_DELETED' => 'pašalinta',
	'JS_TAB_RENAMED' => 'Pervardintas',
	'JS_TAB_REORDERED' =>'Perrikiuotas',
	//Convert Lead
	'JS_CONVERT_LEAD_ERROR' => 'Jei norite konvertuoti užklausą, turite įjungti Organizacijų arba Adresatų modulį.',

	'JS_CHECK_START_AND_END_DATE'=>'Pabaigos data ir laikas turi būti vėlesni arba lygūs pradžios datai ir laikui',
	'JS_CHECK_START_AND_END_DATE_SHOULD_BE_GREATER'=> 'Pabaigos data ir laikas turėtų būti vėlesni negu pradžios data ir laikas',
	'JS_HOLD_FOLLOW_UP_SHOULD_BE_LESS_THAN_CURRENT_DATE'=> 'Tolimesnių veiksmų priminimas turi būti vėliasnis arba lygus pradžios datai ir laikui',
	'JS_DUPLICATES_DETECTED' => 'Duplikatas(-ai) aptikti!',

	'JS_IS' => 'yra',
	'JS_IS_NOT' => 'nėra',
	'JS_EQUALS' => 'lygu',
	'JS_NOT_EQUALS_TO' => 'nelygu',
	'JS_ONLY_LETTERS_AND_NUMBERS_ALLOWED' => 'Leidžiamos tik raidės (a-ž), skaičiai (0-9) ir tarpai',
	'JS_WIDGET_RESIZING_WAIT_MSG' => 'Valdiklio turinys bus įkeltas po dydžio keitimo.',
	'JS_SLA_FULFILLMENT_RATE' => '„SLA“ PATENKINIMO RITMAS',
	'JS_TICKET_COUNT' => 'BYLŲ SKAIČIUS',
	'JS_CASES_AGE_HOURS'=>'BYLOS LAIKAS (Valandos)',
	'JS_BACKLOG'=> 'Atgalinis žurnalas',
	'JS_AND' => 'ir',
	'JS_SEQUENCE_UPDATED_SUCCESSFULLY'=>'Eilės tvarka atnaujinta sėkmingai',
	'JS_VIEW_RECORD' => 'Peržiūrėti įrašą',
	'JS_HIDE'=>'Nerodyti',
	'JS_SHOW_ALL'=>'Rodyti viską',
	'JS_SHOW_LESS' => 'Rodyti mažiau',
	'JS_SHOW_MORE' => 'Rodyti daugiau',

	'JS_KANBAN_ANCHORS_LIMIT_MESSAGE' => 'Galite pasirinkti tik iki 10 etapų', 
	'JS_KANBAN_NO_MORE_RECORDS' => 'Daugiau įrašų nerasta',
	'JS_DELETED' => 'pašalinta',
	'JS_CLEAR_TEMPLATE_CONTENT_RECIPIENTS'=>'Modulio pakeitimas pašalins pasirinktą šabloną ir gavėjus iš „KAM“ lauko. Ar norite testi?',
	'JS_WORKFLOW_ACTIONS_LIMIT_EXCEEDED' => 'Viršyta maksimali šio leidimo veiksmų riba.',
	'JS_RECORD_CREATION_LIMIT_EXCEEDED' => 'Sukurti įrašą - viršyta šio leidimo maksimali riba.',
	'JS_KANBAN_NO_ANCHORS_CONFIGURED' => "Jūs neturite pardavimo etapų, kurie apibrėžtų jūsų pardavimų lubas.",
	'JS_KANBAN_NO_ANCHORS_CONFIGURED_NON_ADMIN' => "Jūs neturite pardavimo etapų, kurie apibrėžtų jūsų pardavimų lubas. Susisiekite su savo administratoriumi, kad apibrėžtumėte pardavimo etapus pagal savo pardavimo procesą.",
	'JS_UPDATE_MAPPING_CONFIRMATION' => '„CSV“ faile yra keletas pasikartojančių stulpelių, kurie nėra išsaugoti šiame susiejime. Ar norite atnaujinti šį susiejimą naujais stulpeliais?',
	'JS_MAPPING_UPDATED' => 'Nauji susiejimai atnaujinti.',
	'JS_MAILCHIMP_REMOVE_SYNC_CONFIRMATION' => 'Prieigos atšaukimas pašalins esamą „MailChimp“ autentifikavimą, jis neištrins sinchronizuotų įrašų. Ar tikrai norite atšaukti prieigą?',
	'JS_WARNING' => 'Įspėjimas',
	'JS_CANT_SELECT_LEAD' => 'Nepavyko pasirinkti susijusios užklausos',
	'JS_CANT_SELECT_CONTACT' => 'Nepavyko pasirinkti susijusio kontakto',
	'JS_MSG_EMPTY_RB_CONFIRMATION' => 'Ar tikrai norite negrįžtamai pašalinti visus šiuos įrašus iš duomenų bazės?',
	'JS_LBL_RESTORE_RECORDS_CONFIRMATION' => 'Ar tikrai norite atkurti šiuos įrašus?',
	'JS_COMMENT_POSTED_SUCCESSFULLY'=>'Komentaras išsiųstas sėkmingai',
	'JS_SHARED_PUBLICLY_WITH'=>'Pasidalintas viešai su',
	'JS_SHARED_PRIVATELY_WITH'=>'Pasidalintas privačiai su',
	'JS_MAIL_SENT_SUCCESSFULLY'=>'Laiškas išsiųstas sėkmingai',
	'JS_SHARED_PUBLICLY_TITLE'=>'Viešąjį pokalbį taip pat gali peržiūrėti naudotojai, kurie nėra susieti su sisijusiomis pašto dėžutėmis, jei jie turi prieigą prie susijusių kontaktų, galimybių ir t.t.',
	'JS_SHARED_PRIVATELY_TITLE'=>'Privatų pokalbį gali peržiūrėti tik tie pašto dėžutės nariai, su kuriais ji yra susieta.',
	'JS_LINKED_RECORDS_SUCCESS'=>'Susieti įrašai sėkmingai atnaujinti',
	'JS_MAIL_DRAFTED_SUCCESSFULLY'=>'Paštas parengtas sėkmingai',

	//Custom view default sort translations.
	'JS_PLEASE_REMOVE_ONE_FIELD_FROM_CHOOSE_COLUMNS_LIST_TO_ADD_DEFAULT_SORT_FIELD' => 'Sąrašo rodinyje leidžiami tik 16 stulpelių įskaitant rūšiuotus stulpelius.',
	'JS_DEFAULT_SORT_NOTIFY' => 'Dabar sąrašas yra surūšiuotas pagal numatytąjį rūšiavimo stulpelį',
	'JS_ENABLED' => 'Įjungta',
	'JS_DISABLED' => 'Išjungta',
	'JS_ONLY_ALLOWED_USERS_ARE_ALLOWED_TO_DO_ACTION'=>'Nepavyko pažymėti pokalbio (-ų) kaip neskaitytą / skaitytą / ištrintą / atliktą / privatų / viešą, nes jis jum nepriklauso.',
	'JS_SHARED_WITH'=>'Pasidalino su',
	'JS_DEFAULT_DASHBOARD_TOOLTIP' => 'Padarykite šį skydelį kaip numatytą, pertvarkydami jį kaip pirmąjį skirtuką!',
	'JS_SET_DEFAULT_TAB' => 'nustatytas kaip numatytą skydelį',
	'JS_PASSWORD_MISMATCH_ERROR' => 'Please re-enter passwords. The "new password" and "confirm password" values do not match.',
	'LBL_LIST_DELETE_CONFIRMATION' => 'Are you sure you want to delete?',
	'JS_WIDGET_RESIZING_WAIT_MSG' => 'Valdiklio turinys bus įkeltas po dydžio keitimo.',
        'JS_COPIED_SUCCESSFULLY' => 'Copied successfully',
        'JS_ATLEAST_SELECT_ONE_FIELD' => 'At least one field should be selected',
        'JS_RELATED_ACCOUNT_IS_NOT_AVAILABLE' => 'Related Organization record is not available',
        'JS_RELATED_CONTACT_IS_NOT_AVAILABLE' => 'Related Contact record is not available',
        'JS_REPEAT_DATE_SHOULD_BE_GREATER_THAN_START_DATE' => 'Repeat date should be greater than or equal to Start Date',
        'JS_PASSWORD_NOT_STRONG' => 'To keep your data safe, we suggest that you use a strong password &lt;br&gt; &lt;ul&gt; &lt;li&gt;Password should be at least 8 characters long &lt;/li&gt; &lt;li&gt;Include at least one number &lt;/li&gt; &lt;li&gt;Include at least one lowercase alphabet &lt;/li&gt; &lt;li&gt;Include at least one uppercase alphabet &lt;/li&gt; &lt;li&gt;Include at least one special character in the password &lt;/li&gt; &lt;/ul&gt;',
);
