<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(

	// Footer
	'APPTITLE'=>'Vtiger',
	'POWEREDBY'=>'Veikia Vtiger sistemoje',
	'LBL_READ_LICENSE'=>'Skaitykite licenciją',
	'LBL_PRIVACY_POLICY'=>'Privatumo politika',

	// Common Actions
	'LBL_SELECT_ALL'=>'Žymėti viską -',
	'LBL_SELECT_TO_LOAD_LIST'=>'Norėdami įkelti sąrašą, pasirinkite',
	'LBL_CREATING_NEW'=>'Kuriamas naujas įrašas - ',
	'LBL_EDITING'=>'Vartotojo redagavimas',
	'LBL_SAVE'=>'Įrašyti',
	'LBL_CANCEL'=>'Atsisakyti',
	'LBL_BACK'=>'Atgal',
	'LBL_IMPORT'=>'Importuoti',
	'LBL_EXPORT'=>'Eksportuoti',
	'LBL_FIND_DUPLICATES'=>'Rasti dublikatus',
	'LBL_MORE'=>'Daugiau...',
	'LBL_ACTIONS'=>'Veiksmai',
    'LBL_ADD'=>'Pridėti',
	'LBL_EDIT'=>'Redaguoti',
	'LBL_DELETE'=>'Pašalinti',
	'LBL_SETTINGS'=>'Nuostatos',
	'LBL_ADD_COMMENT'=>'Pridėti pastabą',
	'LBL_EDIT_FIELDS'=>'Redaguoti laukus',
	'LBL_EDIT_WORKFLOWS'=>'Redaguoti darbo eigas',
	'LBL_EDIT_PICKLIST_VALUES'=>'Redaguoti atrinkčių sąrašo reikšmes',
	'LBL_EDIT_MAILSCANNER'=>'Laiškų keitiklis',
	'LBL_RECORD_DELETE'=>'Įrašas, kurį norite peržiūrėti, pašalintas.',
	'LBL_RECORD_NOT_FOUND'=>'Įrašas, kurį norite pasiekti nerastas',
	'LBL_EDIT_REASON'=>'Redaguoti priežastį',

	//'LBL_EDIT_CURRENT_FILTER'=>'Edit Current Filter',
	//'LBL_DELETE_CURRENT_FILTER'=>'Delete Current Filter',
	'LBL_SELECT'=>'Pasirinkti',
	'LBL_CLEAR'=>'Išvalyti',
	'LBL_YES'=>'Taip',
	'LBL_NO'=>'Jokie',
	'LBL_SHOW_COMPLETE_DETAILS'=>'Užpildyti išsamią informaciją',
    'LBL_MASS_EDITING'=>'Dauginis redagavimas',
	'LBL_DESELECT_ALL_RECORDS'=>'Nužymėti visus įrašus',
	'LBL_QUICK_CREATE'=>'Greitasis kūrimas',
	'LBL_SEND_EMAIL'=>'Siųsti laišką  ',
	//SEND EMAIL translations
	'LBL_ALL_EMAILS'=>'Visos el. pašto paskyros',
	'LBL_MUTIPLE_EMAIL_SELECT_ONE'=>'Pasirinkite vieną iš toliau pateiktų parinkčių',
	//SEND EMAIL translations
	'LBL_GO_TO_FULL_FORM'=>'Eiti į pilną formą',
	'LBL_SEND_SMS'=>'Siųsti žinutę',
	'LBL_FOUND'=>'nerasti',
	'LBL_CLICK_ADD'=>'Spustelėkite "Pridėti"',
	'LBL_ADD_MORE_FIELDS'=>'Pridėti daugiau laukų',
	'LBL_ADD_NOTE'=>'Pridėti pastabą',
	'LBL_CREATE_NEW'=>'Sukurti naują',
    'LBL_ADD_EVENT'=>'Pridėti įvykį',
    'LBL_ADD_TASK'=>'Pridėti užduotį',
	'LBL_MARKETING_AND_SALES'=>'Rinkodara ir pardavimai',
	'LBL_TOOLS_HEADER'=>'Įrankiai',
	'LBL_SUPPORT'=>'Palaikymas',
	'LBL_INVENTORY'=>'Inventorius',
	'LBL_ANALYTICS'=>'Analizė',
	'LBL_HOME'=>'Pradžia',

	// Common Link Labels
	'LBL_LAST_VIEWED_RECORDS'=>'Paskiausiai peržūrėti įrašai',
	'LBL_DASHBOARD'=>'Ataskaitų skyrius',
	'LBL_USER_SETTINGS'=>'Vartotojo nuostatos',
	'LBL_MY_PREFERENCES'=>'Mano pirmenybės',
	'LBL_SIGN_OUT'=>'Atsijungti',
	'LBL_HELP'=>'Pagalba',
	'LBL_DOCUMENTATION'=>'Dokumentacija',
	'LBL_VIDEO_TUTORIAL'=>'Video vadovėlis',
	'LBL_FEEDBACK'=>'Atsiliepimai',
	'LBL_CRM_SETTINGS'=>'Nuostatos',
	'LBL_ON_DEMAND_ADMIN'=>'Pridėti / Pašalinti vartotojus',
	'LBL_ANNOUNCEMENT'=>'Skelbimai',
	'LBL_CALENDAR'=>'Kalendorius',
	'LBL_POST'=>'Išsiųsti',
	'LBL_GUIDER'=>'Vedlys',
	'LBL_DISPLAY_TYPE'=>'Rodyti tipą',
	'LBL_DISPLAY_WIDETYPE'=>'Platus',
	'LBL_DISPLAY_MEDIUMTYPE'=>'Vidutinis',
	'LBL_DISPLAY_NARROWTYPE'=>'Siauras',
	'LBL_TAG_THIS_RECORD'=>'Pažymėti šį įrašą',
	'LBL_PAGE'=>'Puslapis',
	'LBL_LISTVIEW_PAGE_JUMP'=>'Puslapio šuolis',
	'LBL_PROFILE_PASSWORD'=>'Profilis/Slaptažodis',

	// Common Fields
	'LBL_USER'=>'Vartotojas',
	'LBL_GROUP'=>'Grupė',
	'Last Modified By'=>'Paskutiniį kartą keitė',
	'Created Time'=>'Sukūrimo laikas',
	'Modified Time'=>'Pakeitimo laikas:',
	'Description'=>'Aprašymas',
	'Assigned To'=>'Priskirta',

	//Loading Labels
	'LBL_LOADING'=>'Keliama...',
	'LBL_LOADING_WIDGET'=>'Keliamas valdiklis',
	'LBL_LOADING_LISTVIEW_CONTENTS'=>'Keliama, prašome palaukti',

	// Detail View
	'LBL_UPDATES'=>'Atnaujinimai',
	'LBL_SHOW_FULL_DETAILS'=>'Rodyti visą išsamią informaciją',
	'LBL_SUMMARY_DETAILS'=>'Santraukos išsami informacija',
	'LBL_ADD_NEW_COMMENT'=>'Pridėti naują komentarą',
	'LBL_NO_UPDATES'=>'Atnaujinimų nėra',
	'LBL_ACTIVITIES'=>'Veiklos',
	'LBL_NO_PENDING_ACTIVITIES'=>'Laukiančiųjų veiklų nėra',
	'LBL_SUMMARY'=>'Santrauka',
	'LBL_DETAILS'=>'Išsami informacija',

	// Popup window
	'LBL_SEARCH_FOR'=>'Ieškoti',
	'LBL_IN'=>'tarp ',
	'LBL_TYPE_SEARCH'=>'Rašykite, norėdami pasinaudoti paieška',
	'LBL_SEARCH_BUTTON'=>'Paieškos mygtukas',
	'LBL_ADVANCE_SEARCH'=>'Plačiau',
	'LBL_LOADING_PLEASE_WAIT'=>'Keliama, prašome palaukti',
	'LBL_PLEASE_SELECT_MODULE'=>'Pasirinkite modulį',

	//DropDown Category
	'LBL_USERS'=>'Vartotojai',
	'LBL_GROUPS'=>'Grupės',

	//EditView Form Links
	'LBL_FULL_FORM'=>'Pilna forma',
	'LBL_SIMPLE_FORM'=>'Paprasta forma',

	//Recent Comments
	'LBL_ADD_YOUR_COMMENT_HERE'=>'Pridėkite savo komentarą čia…',
	'LBL_REASON_FOR_CHANGING_COMMENT'=>'Priežastis pastabai pakeisti',
	'LBL_REPLY'=>'Atsakyti',
	'LBL_VIEW_THREAD'=>'Peržiūrėti giją',
	'LBL_NO_COMMENTS'=>'Jokių komentarų',
	'LBL_REPLIES'=>'atsakymai',

	//Translation for all modules
	'Accounts'=>'Organizacijos',
	'Assets'=>'Turtas',
	'Calendar'=>'Kalendorius',
	'Campaigns'=>'Kampanijos ',
	'Contacts'=>'Adresatai',
	'Documents'=>'Dokumentai',
	'Leads'=>'Galimi klientai',
	'ModComments'=>'Pastabos',
	'Potentials'=>'Galimybės',
	'PriceBooks'=>'Kainoraščiai',
	'Products'=>'Prekės',
	'Project'=>'Projektai',
	'ProjectMilestone'=>'Projekto svarbiausi įvykiai',
	'ProjectTask'=>'Projekto užduotys',
	'ServiceContracts'=>'Paslaugų kontraktai',
	'Services'=>'Paslaugos',
	'Vendors'=>'Tiekėjai',
	'Rss'=>'RSS',
	'Quotes'=>'Pasiūlymai ',
	'PurchaseOrder'=>'Pirkimo užsakymai',
	'SalesOrder'=>'Pardavimo užsakymai',
	'Invoice'=>'Važtaraščiai',
	'MailManager'=>'Laiškų tvarkyklė',
	'Activities'=>'Veiklos',


	//Basic String Translation
	'LBL_ADD_RECORD'=>'Pridėti įrašą',
	'LBL_RECENTLY_MODIFIED'=>'Neseniai pakeista',
	'LBL_RECORDS_LIST'=>'Įrašų sąrašas',
	'LBL_RECORD_SUMMARY'=>'Modulio santrauka',
	'LBL_RECORD_SUMMARY'=>'Modulio išsami informacija',
	'LBL_ACCESS_DENIED_FOR'=>'Prieiga negalima',
	'LBL_GO_BACK'=>'Grįžti atgal',
	'LBL_NO_DATA_AVAILABLE'=>'Duomenų nėra',

	// Global Search
	'LBL_GLOBAL_SEARCH'=>'Įrašykite raktinį žodį ir paspauskite "ENTER"',
	'LBL_ALL_RECORDS'=>'Visi įrašai',
	'LBL_NO_RECORDS_FOUND'=>'Įrašų nerasta',

	//Filters & Advance Filter
	'LBL_AND'=>'ir',
	'LBL_OR'=>'Arba',
	'LBL_NONE'=>'N',
	'LBL_APPROVE'=>'Patvirtinti',
	'LBL_DENY'=>'Atmesti  ',
	'LBL_EQUALS'=>'lygu',
	'LBL_NOT_EQUAL_TO'=>'nelygu',
	'LBL_STARTS_WITH'=>'Prasideda nuo',
	'LBL_ENDS_WITH'=>'baigiasi simboliais:',
	'LBL_CONTAINS'=>'turi simbolius:',
	'LBL_DOES_NOT_CONTAIN'=>'neturi simbolių:',
	'LBL_LESS_THAN'=>'mažiau nei',
	'LBL_GREATER_THAN'=>'daugiau nei',
	'LBL_LESS_THAN_OR_EQUAL'=>'mažiau arba lygu',
	'LBL_GREATER_OR_EQUAL'=>'daugiau arba lygu',
	'LBL_BEFORE'=>'Prieš',
	'LBL_AFTER'=>'Po',
	'LBL_BETWEEN'=>'tarp',
	'LBL_SEARCH'=>'Paieška',
	'LBL_SEARCH_IN'=>'Ieškoti tarp',
	'LBL_ADD_CONDITION'=>'Pridėti sąlygą',
	'LBL_ADD_GROUP'=>'Pridėti sąlygų grupę',
	'LBL_FILTER_CONDITIONS'=>'Filtro sąlygos',
	'LBL_ALL_CONDITIONS'=>'Visos sąlygos',
	'LBL_ALL_CONDITIONS_DESC'=>'Visos sąlygos turi būti tenkinamos',
	'LBL_ANY_CONDITIONS'=>'Bet kokios sąlygos',
	'LBL_ANY_CONDITIONS_DESC'=>'Bent viena sąlyga turi būti tenkinama',
	'LBL_SELECT_FIELD'=>'Pasirinkite lauką',
	'LBL_SELECT_MODULE'=>'Pasirinkite modulį',
	'LBL_CREATE_NEW_FILTER'=>'Sukurti naują filtrą',
	'All'=>'Visi įrašai - ',
	'Others'=>'Kiti ',
	'Pending'=>'Laukiama',
	'Public'=>'Viešas',

	//Advance Search
	'LBL_SAVE_FILTER'=>'Įrašyti filtrą',
	'LBL_SAVE_MODIFY_FILTER'=>'Įrašyti/Redaguoti filtrą',
	'LBL_SEARCH_RESULTS'=>'Paieškos rezultatai',
	'LBL_SAVE_AS_FILTER'=>'Įrašyti kaip filtrą',

	//Exception String Translation
	'LBL_NOT_ACCESSIBLE'=>'Prieiga negalima',

	//Line Items
	'LBL_ITEM_DETAILS'=>'Elemento išsami informacija',
	'LBL_CURRENCY'=>'Valiuta',
	'LBL_TAX_MODE'=>'Mokesčio veiksena',
	'LBL_INDIVIDUAL'=>'Individuas',
	'LBL_GROUP'=>'Grupė',
	'LBL_TOOLS'=>'Įrankiai',
	'LBL_ITEM_NAME'=>'Elemento pavadinimas',
	'LBL_QTY_IN_STOCK'=>'Sandėlys',
	'LBL_QTY'=>'Kiekis',
	'LBL_LIST_PRICE'=>'Kaina sąraše',
	'LBL_TOTAL'=>'Suma:',
	'LBL_NET_PRICE'=>'Tarpinė kaina',
	'LBL_DISCOUNT'=>'Nuolaida',
	'LBL_TOTAL_AFTER_DISCOUNT'=>'Suma po nuolaidų',
	'LBL_TAX'=>'Mokestis',
	'LBL_ADD_PRODUCT'=>'Pridėti prekę',
	'LBL_ADD_SERVICE'=>'Pridėti paslaugą',
	'LBL_ITEMS_TOTAL'=>'Elemento suma',
	'LBL_SHIPPING_AND_HANDLING_CHARGES'=>'Pristatymo ir tvarkymo mokesčiai',
	'LBL_PRE_TAX_TOTAL'=>'Suma neatskaičius mokesčių',
	'LBL_TAX_FOR_SHIPPING_AND_HANDLING'=>'Pristatymo ir tvarkymo mokesčiai',
	'LBL_SET_SHIPPING_AND_HANDLING_TAXES_FOR'=>'Nustatyti gabenimo ir tvarkymo mokesčius',
	'LBL_ADJUSTMENT'=>'Koregavimas',
	'LBL_DEDUCT'=>'Atimti',
	'LBL_GRAND_TOTAL'=>'Galutinė suma',
	'LBL_ZERO_DISCOUNT' => 'Jokios nuolaidos',
	'LBL_OF_PRICE'=>'Kaina',
	'LBL_DIRECT_PRICE_REDUCTION'=>'Tiesioginis kainos mažinimas',
	'LBL_SET_DISCOUNT_FOR'=>'Nustatyti nuoaidą',
	'LBL_STOCK_NOT_ENOUGH'=>'Nepakanka sandėlyje',
	'LBL_MAX_QTY_SELECT'=>'Didžiausia reikšmė yra',
	'LBL_DRAG'=>'Vilkti',
	'LBL_TOTAL_TAX_AMOUNT'=>'Mokesčių suma',
	'LBL_DIRECT_AMOUNT_DISCOUNT'=>'Tieisoginė nuolaida',
	'LBL_FINAL_DISCOUNT_AMOUNT'=>'Galutinės nuolaidos suma',
	'LBL_MORE_CURRENCIES'=>'daugiau valiutų',
	'LBL_SET_TAX_FOR'=>'Nustatyti mokestį',
	'LBL_GROUP_TAX'=>'Grupės mokestis',
	'LBL_BILLING_ADDRESS_FROM'=>'Kopijuoti sąskaitų siuntimo adresą iš',
	'LBL_SHIPPING_ADDRESS_FROM'=>'Kopijuoti pristatymo adresą iš',
	'LBL_COPY_SHIPPING_ADDRESS'=>'Pristatymo adresas',
	'LBL_COPY_BILLING_ADDRESS'=>'Sąskaitų siuntimo adresas',

	//DetailView Actions
	'LBL_CREATE'=>'Sukurti įrašą - ',
	'LBL_GENERATE'=>'Generuoti',
    'LBL_DUPLICATE'=>'Dublikatas',
	'Add Note'=>'Pridėti pastabą',

	//Dashboard String
	'LBL_ADD_WIDGET'=>'Pridėti valdiklį',
	'LBL_COMMENTS'=>'Pastabos',
	'LBL_REFRESH'=>'Atšviežinti',
	'LBL_CLOSE'=>'Užverti',
	'LBL_ALL'=>'Visi',
	'LBL_UPDATED'=>'atnaujintas',
	'LBL_FROM'=>'nuo',
	'LBL_TO'=>'to',
	'LBL_to'=>'to',
	'LBL_ON'=>'Įjungta',
	'LBL_OF'=>'iš',
	'LBL_BY'=>'pagal',
	'LBL_ADDED'=>'pridėjo',
	'LBL_FOR'=>'for',
	'LBL_CREATED'=>'Sukurta',
	'LBL_DELETED'=>'Pašalinta',
	'LBL_RESTORED'=>'atstatyta',
	'LBL_COMMENTED'=>'pakomentuota',
	'LBL_REMOVED'=>'Pašalinta',
	'LBL_REMOVE'=>'Pašalinti',
	'LBL_AT'=>'at',
	'LBL_MINE'=>'Mano',
	'History'=>'Registras',
	'Upcoming Tasks'=>'Būsimos užduotys',
	'LBL_YEAR'=>'Metai',
	'LBL_YEARS'=>'Metai',
	'LBL_MONTH'=>'mėnesis',
	'LBL_MONTHS'=>'Mėnesis (iai)',
	'LBL_DAY'=>'diena',
	'LBL_DAYS'=>'diena (os)',
	'LBL_HOUR'=>'valanda',
	'LBL_HOURS'=>'Valandos',
	'LBL_MINUTE'=>'min.',
	'LBL_MINUTES'=>'min.',
	'LBL_SECOND'=>'sek.',
	'LBL_SECONDS'=>'sek.',
	'LBL_JUSTNOW'=>'ką tik',
	'LBL_CUSTOM_INFORMATION'=>'Individualizuota informacija',
	'LBL_NO_RECENT_UPDATES'=>'Paskiausių pokyčių nėra',
	'LBL_NO_DATA'=>'Duomenų nėra',
	'LBL_PERMISSION_DENIED'=>'Prieiga negalima',
	'LBL_HANDLER_NOT_FOUND'=>'Tvarkytojas nerastas',
	'LBL_FILTER'=>'Filtras',
	'LBL_DUE'=>'įsipareigota iki:',
	'LBL_DAYS'=>'diena (os)',
	'LBL_COMPLETED'=>'Žymėti kaip užbaigtą',
	'LBL_AGO'=>'prieš',
	'LBL_CHANGED'=>'pakeista',
	'Single_Users'=>'Vartotojas',
	'LBL_MATCHED_THIS_CRITERIA'=>'neatitiko šio kriterijaus.',
	'LBL_NO_SCHEDULED_ACTIVITIES'=>'Suplanuotų veiklų nėra',
	'LBL_NO_OVERDUE_ACTIVITIES'=>'Vėluojančių veiklų nėra',
	'LBL_NO_UPDATES_OR_COMMENTS'=>'Atnaujinimų ar pastabų nėra',
	'LBL_MINI_LIST'=>'Mini sąrašas',
	'LBL_NOTEPAD'=>'užrašinę',
	'LBL_NOTEPAD_NAME'=>'Užrašinės pavadinimas',
	'LBL_NOTEPAD_CONTENT'=>'Užrašinės turinys',
	'LBL_LAST_SAVED_ON'=>'Paskutinį kartą įrašyta',
	'Mini List'=>'Mini sąrašas',
	'Notebook'=>'Užrašinė',
	'LBL_RESULT_FOR_THE_TAG'=>'Rezultatai pagal žymę',

	// Basic Strings- custom view
	'LBL_VIEW_NAME'=>'Peržiūrėti pavadinimą',
	'LBL_CREATE_VIEW'=>'Kuriama nauja peržiūra',
	'LBL_BASIC_DETAILS'=>'Pagrindinė informacija',
	'LBL_CHOOSE_COLUMNS'=>'Pasirinkti stulpelius ir tvarką',
	'LBL_MAX_NUMBER_FILTER_COLUMNS'=>'Daugiausiai 12',
	'LBL_FILTER_ON_DATE'=>'Datos filtras',
	'LBL_CHOOSE_FILTER_CONDITIONS'=>'Pasirinkti filtro sąlygas',
	'LBL_ADD_CONDITION'=>'Pridėti sąlygą',
	'LBL_SET_AS_DEFAULT'=>'Nustatyti kaip numatytąjį',
	'LBL_LIST_IN_METRICS'=>'Metrikų sąrašas',
	'LBL_SET_AS_PUBLIC'=>'Nustatyti kaip viešą',
	'LBL_AND'=>'ir',
	'LBL_OR'=>'Arba',
	'LBL_ADD_MORE_COLUMNS'=>'Pridėti daugiau stulpelių',
	'LBL_ADD_GROUP'=>'Pridėti grupę',


	//DateFilter Conditions
	'LBL_CUSTOM'=>'Individualizuotas',
	'LBL_PREVIOUS_FY'=>'Praeitas ',
	'LBL_CURRENT_FY'=>'Current FY',
	'LBL_NEXT_FY'=>'Next FY',
	'LBL_PREVIOUS_FQ'=>'Praeiti DUK',
	'LBL_CURRENT_FQ'=>'Esami DUK',
	'LBL_NEXT_FQ'=>'Kiti DUK',
	'LBL_YESTERDAY'=>'Vakar',
	'LBL_TODAY'=>'Šiandien',
	'LBL_TOMORROW'=>'Rytoj',
	'LBL_LAST_WEEK'=>'Praeita savaitė',
	'LBL_CURRENT_WEEK'=>'Einamoji savaitė',
	'LBL_NEXT_WEEK'=>'Kita savaitė',
	'LBL_LAST_MONTH'=>'Praeitas mėnesis',
	'LBL_CURRENT_MONTH'=>'Einamasis mėnesis',
	'LBL_NEXT_MONTH'=>'Kitas mėnesis',
	'LBL_LAST_7_DAYS'=>'Paskutinės 7 dienos',
	'LBL_LAST_30_DAYS'=>'Paskutinės 30 dienų',
	'LBL_LAST_60_DAYS'=>'Paskutinės 60 dienų',
	'LBL_LAST_90_DAYS'=>'Paskutinės 90 dienų',
	'LBL_LAST_120_DAYS'=>'Paskutinės 120 dienų',
	'LBL_NEXT_30_DAYS'=>'Kitas 30 dienų',
	'LBL_NEXT_60_DAYS'=>'Kitas 60 dienų',
	'LBL_NEXT_90_DAYS'=>'Kitas 90 dienų',
	'LBL_NEXT_120_DAYS'=>'Kitas 120 dienų',

	//advanced Filter Options
	'LBL_NONE'=>'N',
	'LBL_EQUALS'=>'lygu',
	'LBL_NOT_EQUAL_TO'=>'nelygu',
	'LBL_STARTS_WITH'=>'Prasideda nuo',
	'LBL_ENDS_WITH'=>'baigiasi simboliais:',
	'LBL_CONTAINS'=>'turi simbolius:',
	'LBL_DOES_NOT_CONTAIN'=>'neturi simbolių:',
	'LBL_LESS_THAN'=>'mažiau nei',
	'LBL_GREATER_THAN'=>'daugiau nei',
	'LBL_LESS_THAN_OR_EQUAL'=>'mažiau arba lygu',
	'LBL_GREATER_OR_EQUAL'=>'daugiau arba lygu',
	'LBL_BEFORE'=>'Prieš',
	'LBL_AFTER'=>'Po',
	'LBL_BETWEEN'=>'tarp',
	'LBL_IS_EMPTY'=>'tuščias',

	//Detail view summary widgets
	'LBL_OWNER'=>'Savininkas',
	'LBL_CREATED_ON'=>'Paskutinį kartą vykdyta',
	'LBL_MODIFIED_ON'=>'Pakeitimo laikas:',
	'LBL_MODIFIED'=>'Pakeista',
	'LBL_COMMENTED'=>'Pakomentuota',

    //calender set-reminder
    'LBL_BEFORE_EVENT'=>'Prieš įvykį',

	//Dashboard widgets
	'History'=>'Registras',
	'Upcoming Activities'=>'Būsimos veiklos',
	'Overdue Activities'=>'Vėluojančios veiklos',
	'Funnel'=>'Piltuvėlis',
	'Potentials by Stage'=>'Galimybės pagal lygmenį',
	'Pipelined Amount'=>'Pardavimų srautas',
	'Total Revenue'=>'Pajamų suma',
	'Top Potentials'=>'Aukščiausio prioriteto galimybės',
	'Forecast'=>'Prognozė',
	'Leads Created'=>'Galimi klientai sukurti',
	'Leads by Status'=>'Galimi klientai pagal būseną',
	'Leads by Source'=>'Galimi klientai pagal kilmę',
	'Leads by Industry'=>'Galimi klientai pagal pramonę',
	'Tickets by Status'=>'Kortelės pagal būseną',
	'Open Tickets'=>'Atviros kortelės',
	'Funnel Amount'=>'Kiekis pagal pardavimų lygmenį',

	//Exports strings
	'LBL_EXPORT_ALL_DATA'=>'Eksportuoti visus duomenis',
	'LBL_EXPORT_DATA_IN_CURRENT_PAGE'=>'Eksportuote esamo puslapio duomenis',
	'LBL_EXPORT_SELECTED_RECORDS'=>'Eksportuoti pasirinktus įrašus',
	'LBL_EXPORT_RECORDS'=>'Eksportuoti įrašus',
	'LBL_NO_RECORD_SELECTED'=>'Įrašų nepasirinkta',
	'LBL_CAN_NOT_REMOVE_DEFAULT_WIDGET'=>'Negalima pašalinti numatytojo valdiklio',
	'LBL_CUSTOM_VIEW_NAME_DUPLICATES_EXIST'=>'filtras jau egzistuoja',

	'LBL_ADD_MANAGE_MODULES'=>'Pridėti / Tvarkyti modulius',
	'LBL_CUSTOMIZE_MAIN_MENU'=>'Individualizuoti pagrindinį meniu',

	// Added Common Keys for all modules
	'Account Name'=>'Organizacijos pavadinimas',
	'Add Comment'=>'Pridėti pastabą',
	'Adjustment'=>'Koregavimas',
	'Annual Revenue'=>'Metinės pajamos',
	'Apparel'=>'Papuošalai',
	'Banking'=>'Bankininkystė',
	'Billing Address'=>'Sąskaitų siuntimo adresas',
	'Billing City'=>'Sąskaitų siuntimo miestas',
	'Billing Code'=>'Sąskaitų siuntimo pašto kodas',
	'Billing Country'=>'Sąskaitų siuntimo šalis',
	'Billing Po Box'=>'Sąskaitų siuntimo pašto dėžutė',
	'Billing State'=>'Sąskaitų siuntimo savivaldybė',
	'Biotechnology'=>'Biotechnologijos',

	//for SO PO and Quotes
	'FedEx'=>'FedEx',
	'UPS'=>'UPS',
	'USPS'=>'USPS',
	'DHL'=>'DHL',
	'BlueDart'=>'Mėlyna',
	'Carrier'=>'Kurjeris',
	'Category'=>'Kategorija',
	'Chemicals'=>'Chemikalai',
	'City'=>'Miestas',

	'Cold Call'=>'Skambutis nepažįstamam',
	'Existing Customer'=>'Esamas klientas',
	'Self Generated'=>'Savarankiškai atsiradęs',
	'Employee'=>'Darbuotojas',
	'Partner'=>'Partneris',
	'Public Relations'=>'Viešieji ryšiai',
	'Direct Mail'=>'Tiesioginis laiškas',
	'Conference'=>'Konferencija',
	'Trade Show'=>'Paroda',
	'Web Site'=>'Svetainė',
	'Word of mouth'=>'Iš lūpų į lūpas',
	'Other'=>'Kita',

	//for leads and accounts
	'--None--'=>'N',
	'Acquired'=>'Įgyta',
	'Active'=>'Aktyvus',
	'Market Failed'=>'Rinka žlugo',
	'Project Cancelled'=>'Projektas atšauktas',
	'Shutdown'=>'Stabdyti',
	'Apparel'=>'Papuošalai',
	'Banking'=>'Bankininkystė',
	'Biotechnology'=>'Biotechnologijos',
	'Chemicals'=>'Chemikalai',
	'Communications'=>'Komunikacijos',
	'Construction'=>'Konstrukcija',
	'Consulting'=>'Konsultavimas',
	'Education'=>'Švietimas',
	'Electronics'=>'Elektronika',
	'Energy'=>'Energija',
	'Engineering'=>'Inžinerija',
	'Entertainment'=>'Pramogos',
	'Environmental'=>'Aplinkos',
	'Finance'=>'Finansai',
	'Food & Beverage'=>'Maistas ir gėrimai',
	'Government'=>'Valdžia',
	'Healthcare'=>'Sveikatos apsauga',
	'Hospitality'=>'Labdara',
	'Insurance'=>'Draudimas',
	'Machinery'=>'Mašinos',
	'Manufacturing'=>'Gamyba',
	'Media'=>'Medija',
	'Not For Profit'=>'Ne pelno siekianti',
	'Recreation'=>'Atkūrimas',
	'Retail'=>'Mažmeninė prekyba',
	'Shipping'=>'Pristatymas',
	'Technology'=>'Technologijos',
	'Telecommunications'=>'Telekomunikacijos',
	'Transportation'=>'Transportas',
	'Utilities'=>'Paslaugų programos',

	'Contact Name'=>'Adresato vardas',
	'Conversion Rate'=>'Konvertavimo kursas',

	'Shipping Address'=>'Pristatymo adresas',
	'Shipping City'=>'Pristatymo miestas',
	'Shipping State'=>'Pristatymo savivaldybė',
	'Shipping Code'=>'Pristatymo pašto kodas',
	'Shipping Country'=>'Pristatymo šalis',
	'Shipping Po Box'=>'Pristatymo pašto dėžutė',
	'Country'=>'Šalis',
	'Description'=>'Aprašymas',

	'Created'=>'Sukurta',
	'Approved'=>'Patvirtinta',
	'Delivered'=>'Pristatyta',
	'Cancelled'=>'Atsisakyta',

	'Currency'=>'Valiuta',
	'LBL_BASE_CURRENCY'=>'Pagrindinė valiuta -',

	'Discount Percent'=>'Nuolaida procentais',
	'Discount Amount'=>'Nuolaidos suma',
	'Item Discount Amount'=>'Elemento nuolaida ',
	'Item Discount Percent'=>'Elemento nuolaida procentais',

	'Due Date'=>'Įsipareigojimo data',
	'Due Date & Time'=>'Įsipareigojimo data ir laikas',
	'Email'=>'Pradinis el. pašto adresas',
	'Secondary Email'=>'Atsarginis el. paštas',
	'Other Email'=>'Kitas el. paštas ',
	'Email Opt Out'=>'Atsisakyta laiškų',

	'Expected Close Date'=>'Laukiama užbaigimo data',

	'Fax'=>'Faksas',

	'Last Name'=>'Pavardė',
	'First Name'=>'Vardas',

	'High'=>'Aukštas',
	'Low'=>'Žemas',

	'In Progress'=>'Nebaigta',


	'Subject'=>'Tema ',
	'Shipping Address'=>'Pristatymo adresas',
	'Shipping Po Box'=>'Pristatymo pašto dėžutė',
	'Shipping City'=>'Pristatymo miestas',
	'Shipping State'=>'Pristatymo savivaldybė',
	'Shipping Code'=>'Pristatymo pašto kodas',
	'Shipping Country'=>'Pristatymo šalis',
	'Terms & Conditions'=>'Terminai ir sąlygos',
	'Item Name'=>'Elemento pavadinimas',
	'Quantity'=>'Kiekis',
	'List Price'=>'Kainų sąrašas',
	'Item Comment'=>'Elemento pastaba',
	'Tax1'=>'1 mokestis',
	'Tax2'=>'2 mokestis',
	'Tax3'=>'3 mokestis',
	'Excise Duty'=>'Akcizas',
	'Total'=>'Suma',
	'Sub Total'=>'Tarpinė suma',
	'Tax Type'=>'Mokesčio tipas',
	'S&H Amount'=>'Gabenimo ir tvarkymo mokesčiai',
	'Status'=>'Būsena',
	'Vendor Name'=>'Tiekėjo pavadinimas',

	'LBL_ADDRESS_INFORMATION'=>'Vartotojo adresas',
	'LBL_DESCRIPTION_INFORMATION'=>'Aprašymo pavadinimas:',
	'LBL_TERMS_INFORMATION'=>'Terminai ir sąlygos',
	'LBL_PRICING_INFORMATION'=>'Kainos informacija',
	'LBL_RELATED_PRODUCTS'=>'Prekės išsami informacija',
	'LBL_REMINDER_INFORMATION'=>'Priminimo išsami informacija',

	'LBL_FOLDER_SAVED'=>'Katalogas įrašytas',
	'LBL_FOLDER_EXISTS'=>'Katalogas jau egzistuoja',
	'LBL_FOLDER_DELETED'=>'Katalogas pašalintas',

	'Lead Source'=>'Galimų klientų šaltinis',
	'Mobile'=>'Mobilus telefonas',

	'Notify Owner'=>'Informuoti savininką',
	'Other Phone'=>'Kitas telefonas',
	'Phone'=>'Telefonas',

	'State'=>'Savivaldybė',
	'Po Box'=>'Pašto dėžutė',
	'Postal Code'=>'Pašto kodas',

	'Potential Name'=>'Galimybės pavadinimas',
	'Priority'=>'Prioritetas',

	'Product Name'=>'Prekės pavadinimas',
	'Rating'=>'Įvertinimas',

	'Related To'=>'Susiję su',
	'Type'=>'Tipas',

	'Reviewed'=>'Peržiūrėta',
	'Salutation'=>'Sveikinimas',
	'Street'=>'Gatvė',
	'Support Start Date'=>'Palaikymo pradžios data',
	'Support Expiry Date'=>'Palaikymo pabaigos data',
	'Sales Start Date'=>'Pardavimų pradžios data',
	'Sales End Date'=>'Pardavimų pabaigos data',

	//Dashboard list of widgets translation
	'Open Tickets'=>'Atviros kortelės',
	'LBL_SELECT_STATUS'=>'Žymėti būseną',
	'LBL_BLANK'=>'Tuščia',

	//PageTitle translations
	'LBL_VTIGER_CRM_HONEST_OPEN_SOURCE'=>'Vtiger atviras kodas',

	//Translations used in inventory modules for sopy address
	'SINGLE_Accounts'=>'Organizacija',
	'SINGLE_Contacts'=>'Adresatas',

	//Weekdays in 3 letters translations
	'LBL_Sun'=>'Sekm',
	'LBL_Mon'=>'Pirm',
	'LBL_Tue'=>'Antr',
	'LBL_Wed'=>'Treč',
	'LBL_Thu'=>'Ketv',
	'LBL_Fri'=>'Penkt',
	'LBL_Sat'=>'Šešt',

	//Months in 3 letters translations
	'LBL_Jan'=>'Sau',
	'LBL_Feb'=>'Vas',
	'LBL_Mar'=>'Kov',
	'LBL_Apr'=>'Bal ',
	'LBL_May'=>'Gegužė',
	'LBL_Jun'=>'Bir',
	'LBL_Jul'=>'Lie',
	'LBL_Aug'=>'Rugp',
	'LBL_Sep'=>'Rugs',
	'LBL_Oct'=>'Spa',
	'LBL_Nov'=>'Lap',
	'LBL_Dec'=>'Gruo',

	'LBL_CALENDAR_SETTINGS'=>'Kalendoriaus nuostatos',

	//Translations used in inventory modules for address
	'SINGLE_Accounts'=>'Organizacija',
	'SINGLE_Contacts'=>'Adresatas',
	'HelpDesk'=>'Kortelės',
	'LBL_TAG_CLOUD'=>'Žymių debesis',

	'LBL_NO_RECORDS'=>'Įrašų nėra.',
	'LBL_NO_RELATED'=>'Susijusių nėra',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE'=>'Tik pirmieji 100 rezultatų iš visų modulių rodomi. Jei norite peržiūrėti konkretaus modulio rezultatus, nurodykite jį ir pasinaudokite paieška. ',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE_FOR_MODULE'=>'Tik pirmieji 100 rezultatų rodomi. Jei norite peržiūrėti daugiau, naudokitės paieška.',

	// used in reports detail view
	'LBL_ACTION'=>'Veiksmas',
	'LBL_NOTE'=>'Pastaba',
	'LBL_SELECT_OPTION'=>'Pasirinkite',

	//Module Manager
	'LBL_TOOLTIP'=>'Patarimų tvarkymas',
	'LBL_MODULE_SEQUENCE_NUMBERING'=>'Numeruoti modulių seką',
	'LBL_CUSTOM_FIELD_MAPPING'=>'Individualizuotų laukų atvaizdavimas',
	'LBL_WEBFORMS'=>'Saityno formos',

	//Compose Email Strings
	'SINGLE_Emails'=>'El. paštas',
	'Emails'=>'Laiškai',
	'LBL_SELECT_EMAIL_IDS'=>'Pasirinkite el. pašto adresus',
	'LBL_SUBJECT'=>'Tema ',
	'LBL_ATTACHMENT'=>'Priedas',
	'LBL_BROWSE_CRM'=>'Naršyti KRV',
	'LBL_SEND'=>'Siųsti',
	'LBL_SAVE_AS_DRAFT'=>'Įrašyti kaip juodraštį',
	'LBL_GO_TO_PREVIEW'=>'Eiti į atvaizdavimą',
	'LBL_SELECT_EMAIL_TEMPLATE'=>'Pasirinkite el. pašto šabloną',
	'LBL_COMPOSE_EMAIL'=>'Kurti laišką',
 	'LBL_CC'=>'Kopija:',
   	'LBL_BCC'=>'Namatomoji kopija:',
   	'LBL_ADD_CC'=>'Pridėti kopiją',
   	'LBL_ADD_BCC'=>'Pridėti nematomą kopiją',
	'LBL_MAX_UPLOAD_SIZE'=>'Didžiausia galima išsiunčiamo failo apimtis yra',
	'LBL_EXCEEDED'=>'Viršyta',
	'LBL_OPERATION_NOT_PERMITTED'=>'Operacija neleidžiama',
    'LBL_MERGE'=>'Sulieti',
	'LBL_MERGING_CRITERIA_SELECTION'=>'Suliejimo kriterijaus pasirinkimas',
	'LBL_AVAILABLE_FIELDS'=>'Galimi laukai',
	'LBL_MERGE_RECORDS_DESCRIPTION'=>'The primary record will be retained after the merge. You can select the column to retain the values.
										The other record will be deleted but the related information will be merged.',
	'LBL_MERGE_RECORDS_IN'=>'Sulieti įrašus esančius',
	'LBL_FIELDS'=>'Laukai',
	'LBL_RECORD'=>'Įrašas, kurį norite pasiekti nerastas',
	'LBL_NO_DUPLICATED_FOUND'=>'Vienodų įrašų nerasta',
	'LBL_MERGE_SELECT'=>'Pasirinkti suliejimui',

	//sbproducts translation
	'LBL_BACK_TO_PRODUCTS'=>'Atgal į prekes',

	//Translations used for Export to Pdf
	'Valid Date'=>'Galiojimo data',
	'Phone: '=>'Telefonas:',
	'Issued Date'=>'Išleidimo data',
	'Shipping & Handling Charges'=>'Pristatymo ir tvarkymo mokesčiai',
	'Shipping & Handling Tax:'=>'Pristatymo ir tvarkymo mokestis:',
	'Discount'=>'Nuolaida',
	'Net Total'=>'Tarpinė suma',
	'Product Code'=>'Prekės kodas',
	'Customer Name'=>'Kliento pavadinimas',
	'Price'=>'Kaina',
	'Tax:'=>'Mokestis',
	'Contact Name'=>'Adresato vardas',
	'Grand Total:'=>'Galutinė suma:',
	'Fax: '=>'Faksas:',
	'Website: '=>'Svetainė:',
	'Tax'=>'Mokesčiai',
	'LBL_ALPHABETS'=>'A,B,C,Č,D,E,Ę,Ė,F,G,H,I,Į,Y,J,K,L,M,N,O,P,R,S,Š,T,U,Ų,Ū,V,Z,Ž',

	//Realted tab strings
	'Service Contracts'=>'Paslaugų kontraktai',
	'Projects'=>'Projektai',
	'Sales Order'=>'Pardavimo užsakymas',
	'Purchase Order'=>'Pirkimo užsakymas',
	'List and Campaigns'=>'Sąrašas ir kampanijos',
	'Project Tasks'=>'Projekto užduotys',
	'Project Milestones'=>'Projekto svarbiausi įvykiai',

	'Labels Editor'=>'Žymių redaktorius',
	'LBL_IGNORE_EMPTY_VALUES'=>'Nepaisyti neįrašytų verčių',

	//Related tabs of Products
	'Product Bundles'=>'Prekių ryšulys',
	'Parent Product'=>'Pirminė prekė',

	'LBL_MANAGE_USERS'=>'Tvarkyti vartotojus',
	'LBL_TRANSFER_OWNERSHIP'=>'Perkelti savininkystę',
	'LBL_SELECT_RELATED_MODULES'=>'Pažymėkite susijusius modulius',
	'LBL_ASSIGNED_TO'=>'Priskirta:',

	//Report Detail View
	'LBL_VIEW_DETAILS'=>'Peržiūrėti išsamią infromaciją',
	//Comments Field Labels for Workflow
	'Comment'=>'Pastaba',
	'Last Comment'=>'Paskutinė pastaba',
	'Last 5 Comments'=>'Paskutinės 5 pastabos',
	'All Comments'=>'Visi komentarai',
);

$jsLanguageStrings = array(
	'JS_EMAIL_SERVER_CONFIGURATION'=>'Sukonfigūruokite savo siunčiamų laiškų severį nuostatų puslapyje',
	'JS_SMS_SERVER_CONFIGURATION'=>'Sukonfigūruokite savo informavimą žinute nuostatų puslapyje',
	'JS_PLEASE_SELECT_ONE_RECORD'=>'Pasirinkite bent vieną įrašą',

	//Validation Error Message
	'JS_PLEASE_ENTER_VALID_EMAIL_ADDRESS'=>'Įveskite galiojantį el. pašto adresą',
	'JS_CONTAINS_ILLEGAL_CHARACTERS'=>'turi negalimų simbolių',
	'JS_PHONE_NUMBER_LENGTH_EXCEEDED'=>'telefono nr. Viršija galimą skaitmenų skaičių',
	'JS_ACCEPT_POSITIVE_NUMBER'=>'Priimti tik teigiamus skaičius',
	'JS_VALUE_SHOULD_BE_GREATER_THAN_ZERO'=>'reikšmė turi būt didesnė už 0',
	'JS_NUMBER_SHOULD_BE_LESS_THAN_32'=>'Skaičius turi būti mažesnis nei 32',
	'JS_PLEASE_ENTER_VALID_DATE'=>'Įveskite galiojančią datą',
	'JS_PLEASE_ENTER_VALID_TIME'=>'Įveskite galiojantį laiką',
	'JS_INVALID_PAGE_NUMBER'=>'Netinkamas puslapio numeris',


	'INVALID_NUMBER_OF'=>'Netinkamas numeris',
	'INVALID_NUMBER'=>'Netinkamas numeris',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE'=>'Ar tikrai norite pašalinti?',

	'OVERWRITE_EXISTING_MSG1'=>'Pakeisti dabartinį adresą pažymėtuoju',
	'OVERWRITE_EXISTING_MSG2'=>'adreso informacija?',
	'SINGLE_Accounts'=>'Organizacija',
	'SINGLE_Contacts'=>'Adresatas',

	'LBL_DELETE_CONFIRMATION'=>'Ar tikrai norite pašalinti?', // This is added as duplicate as we need to show different message for different modules. Ex:Accounts has different message
	'LBL_MASS_DELETE_CONFIRMATION'=>'Ar tikrai norite pašalinti pasirinktus įrašus?',
	'JS_LBL_SAVE'=>'Įrašyti',
	'JS_LBL_CANCEL'=>'Atsisakyti',
	'JS_DUPLICTAE_CREATION_CONFIRMATION'=>'Toks organizacijos pavadinimas jau egzistuoja. Ar norite sukurti dar vieną tokį pat įrašą?',

	'SHOULD_BE_LESS_THAN_TODAY'=>'Turi pasirodyti iki šiandien',
	'JS_PLEASE_SELECT_ATLEAST_ONE_OPTION'=>'Pasirinkie bent vieną parinktį',
	'JS_SELECT_MODULE'=>'Pasirinkite modulį',
	'JS_PLEASE_SELECT_ATLEAST_ONE_MANDATORY_FIELD'=>'Pasirinkite bent vieną privalomą lauką',
	'JS_SELECT_MODULE'=>'Pasirinkite modulį',
	'JS_PLEASE_ENTER_INTEGER_VALUE'=>'Įrašykite sveiką skaičių',
	'JS_PLEASE_ENTER_DECIMAL_VALUE'=>'Įrašykite dešimtainę vertę',

	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE'=>'turi būti ankstesnė nei einamoji data',
	'JS_SHOULD_BE_GREATER_THAN_CURRENT_DATE'=>'turi būti vėlesnė nei einamoji data',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO'=>'turi būti daugiau arba lygu:',
    'JS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO'=>'turi būti mažiau arba lygu:',
	'JS_PERCENTAGE_VALUE_SHOULD_BE_LESS_THAN_100'=>'Procentų reikšmė negali viršyti 100',
	'JS_ACCEPT_ONLY_NUMBER'=>'Priimti tik skaičius',
	'JS_THIS_FILE_HAS_ALREADY_BEEN_SELECTED'=>'Šis failas jau buvo pasirinktas',
	'JS_MAX_FILE_UPLOAD_EXCEEDS'=>'viršytas didžiausias galimas įkeliamo failo dydis',
	'JS_THIS_DOCUMENT_HAS_ALREADY_BEEN_SELECTED'=>'Šis dokumentas jau buvo pridėtas',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO'=>'Turi būti daugiau arba lygu:',


	//Roles
	'JS_FAILED_TO_SAVE'=>'Nepavyko įrašyti pakeitimų serveryje',

	//Import Translations
	'JS_IMPORT_FILE_CAN_NOT_BE_EMPTY'=>'Importuojamas failas negali būti tuščias',
	'JS_PLEASE_SELECT_ONE_FIELD_FOR_MERGE'=>'Pasirinkite bent vieną lauką suliejimo kriterijui',
	'JS_MAP_NAME_CAN_NOT_BE_EMPTY'=>'Žemėlapio pavadinimas turi būti įrašytas',
	'JS_MAP_NAME_ALREADY_EXISTS'=>'Toks žemėlapio pavadinimas jau egzistuoja',
	'JS_SELECT_FILE_EXTENSION'=>'Pasirinkite failą su šiuo plėtiniu:',
	'JS_UPLOADED_FILE_SIZE_SHOULD_BE_LESS_THAN'=>'Siunčiams failas turi būti mažesnis nei',
	'JS_UPLOADED_FILE_SIZE_EXCEEDS'=>'Išsiųstas failas viršija',
	'JS_PLEASE_SPLIT_FILE_AND_IMPORT_AGAIN'=>'Padalinkite failą į mažesnius ir importuokite dar kartą.',
	'JS_FIELD_MAPPED_MORE_THAN_ONCE'=>'Laukas atvaizduotas daugiau nei vieną kartą',
	'JS_MAP_MANDATORY_FIELDS'=>'Atvaizduokite privalomus laukus',
	'JS_PLEASE_ENTER_SOME_VALUE'=>'Įrašykite žodį norėdami atlikti paiešką',

	//Select2 elements validation message
	'JS_YOU_CAN_SELECT_ONLY'=>'Galima pažymėti tik',
	'JS_ITEMS'=>'elementai',

	'JS_LBL_PERMISSION'=>'Laidimai',
	'JS_CHECK_FILE_INTEGRITY'=>'Patikrinti failų integraciją',
	'JS_DUPLICATE_RECORD'=>'Dubliuoti įrašą',

	//advance filter checkbox type condition values
	'JS_IS_ENABLED'=>'įjungtas',
	'JS_IS_DISABLED'=>'išjungtas',

	'JS_PLEASE_ENTER_SOME_TEXT_FOR_COMMENT'=>'Įrašykite komentaro tekstą',
	'JS_LBL_COMMENT_VALUE_CANT_BE_EMPTY'=>'Pastaba turi būti įrašyta',
	'JS_REQUIRED_FIELD'=>'* šį lauką užpildyti būtina',
	'JS_CAN_NOT_REMOVE_DEFAULT_WIDGET'=>'Negalima pašalinti numatytojo valdiklio',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE'=>'turi būti ankstesnė nei einamoji data',
	'JS_NO_CREATE_OR_NOT_QUICK_CREATE_ENABLED'=>'Nėra teisių kurti arba neįjungtas greitasis kūrimas',

	//Image Action
	'LBL_IMAGE_DELETED_SUCCESSFULLY'=>'Paveikslėlis pašalintas sėkmingai',
	'LBL_IMAGE_NOT_DELETED'=>'Paveikslėlis nebuvo pašalintas',
	'LBL_YES'=>'Taip',
	'LBL_NO'=>'Jokie',
	'AM'=>'AM',
	'PM'=>'Po pietų',
 	'JS_ERROR'=>'Klaida',
	'JS_INFORMATION'=>'Informacija',
	'JS_DO_NOT_HAVE_AN_EMAIL_ID'=>'neturi el. pašto',
	'NONE_OF_THE_FIELD_VALUES_ARE_CHANGED_IN_MASS_EDIT'=>'Per dauginį redagavimą jokių laukų reikšmės nepakeistos.',

	//Notification messages for inventory module
	'JS_PLEASE_SELECT_AN_ACCOUNT_TO_COPY_ADDRESS'=>'Norėdami nukopijuoti adresą, pasirinkite organizaciją',
	'JS_PLEASE_SELECT_AN_CONTACT_TO_COPY_ADDRESS'=>'Norėdami nukopijuoti adresą, pasirinkite adresatą',
	'JS_SELECTED_ACCOUNT_DOES_NOT_HAVE_AN_ADDRESS'=>'Pažymėta organizacija neturi adreso nukopijuoti',
	'JS_SELECTED_CONTACT_DOES_NOT_HAVE_AN_ADDRESS'=>'Pažymėtas adresatas neturi adreso nukopijuoti',
	'JS_PLEASE_ENTER_PRIMARY_EMAIL_VALUE_TO_ENABLE_PORTAL_USER'=>'Norėdami įgalinti portalo vartotoją, įrašykite pirminį el. pašto adresą.',
	'JS_PRIMARY_EMAIL_FIELD_DOES_NOT_EXISTS'=>'Pradinis el. pašto adresas neegzistuoja',

	//Tag Cloud validation messages
	'JS_PLEASE_ENTER_A_TAG'=>'Įveskite žymę',
	'JS_TAG_NAME_ALREADY_EXIST'=>'Žymės pavadinimas jau egzistuoja',
	'JS_MAX_TAG_LENGTH_EXCEEDS'=>'Žymės ilgis viršija leistiną',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=>'Įrašę šį įrašą nebeturėsite leidimo jį peržiūrėti. Ar norite tęsti?',
	'JS_NO_RECORDS_RELATED_TO_THIS_FILTER'=>'Įrašų, susijusių su šiuo filtru, nėra',

	// Calendar Reminder popup
	'JS_START_DATE_TIME'=>'Pradžios data ir laikas',
	'JS_END_DATE_TIME'=>'Pabaigos data ir laikas',
	'JS_POSTPONE'=>'Nukelti',
	'JS_MESSAGE'=>'Pranešimas',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=>'Įrašę šį įrašą nebeturėsite leidimo jį peržiūrėti. Ar norite tęsti?',

	//Settings page translations
	'JS_SUCCESSFULLY_PINNED'=>'Nuoroda pridėta sėkmingai',
	'JS_SUCCESSFULLY_UNPINNED'=>'Nuoroda pašalinta sėkmingai',
	'JS_SHORTCUT_ALREADY_ADDED'=>'Ši nuoroda jau pridėta',
	'JS_MESSAGE'=>'Pranešimas',

	//Module Manager
	'JS_MODULE_ENABLED'=>'Modulis įjungtas',
	'JS_MODULE_DISABLED'=>'Modulis išjungtas',

	//Crom tasks
	'JS_VALUE_SHOULD_NOT_BE_LESS_THAN'=>'Periodinis darbas neturi kartotis rečiau nei',
	'JS_MINUTES'=>'min.',

	//PickList
	'JS_ITEM_RENAMED_SUCCESSFULLY'=>'Elementas pervadintas sėkmingai',
	'JS_ITEM_ADDED_SUCCESSFULLY'=>'Elementas pridėtas sėkmingai',
	'JS_NO_ITEM_SELECTED'=>'Nepasirinktas elementas',
	'JS_MORE_THAN_ONE_ITEM_SELECTED'=>'Pasirinkta daugiau nei vienas elementas',
	'JS_ITEMS_DELETED_SUCCESSFULLY'=>'Elementai pašalinti sėkmingai',
	'JS_DUPLIACATE_ENTRIES_FOUND_FOR_THE_VALUE'=>'Rasti du vienodi šios reikšmės įrašai',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP'=>'Suliejimui turite pasirinkti tos pačios grupės įrašus.',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING'=>'Pasirinkite bent du įrašus suliejimui',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS'=>'Galima pasirinkti iki 3 įrašų.',
	//Notification message for dashboard widget delete
	'JS_ARE_YOU_SURE_TO_DELETE_WIDGET'=>'Ar tikrai norite pašalinti valdiklį?',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE'=>'Rasti du vienodi šios reikšmės įrašai',
	'JS_TOTAL_RECORDS'=>'Iš viso įrašų',
	'JS_PAGE_NOT_EXIST'=>'Puslapis neegzistuoja',
	'JS_YOU_ARE_IN_PAGE_NUMBER'=>'Esate puslapyje nr.',

	//More currencies message
	'JS_PLEASE_ENABLE_BASE_CURRENCY_FOR_PRODUCT'=>'Nustatykite bazinę valiutą prekei',
	'JS_PLEASE_SELECT_BASE_CURRENCY_FOR_PRODUCT'=>'Pasirinkite pagrindinę valiutą prekei',

	//Delete Records message
	'JS_RECORDS_ARE_GETTING_DELETED'=>'Įrašai šalinami',
	'JS_RECORD_GETTING_DELETED'=>'Įrašas šalinamas',
	'JS_NO_RESULTS_FOUND'=>'Rezultatų nerasta',

	'JS_RECORDS TRANSFERRED SUCCESSFULLY'=>'Įrašo savininkystė perduota sėkmingai',

	'JS_USER_EXISTS'=>'Toks vartotojas jas egzistuoja',
	'JS_REENTER_PASSWORDS'=>'Įvesti slaptažodžius',
);
